### PR TITLE
Vulcan: Add list styles

### PR DESCRIPTION
**Pull request by andyg0808**
This makes them look much nicer and line up well with the rest of the text.

## QA Notes
There's no mockup for lists, so please just confirm that this looks reasonable to you.

This may be a helpful link:
https://react-commerce-git-vulcan-add-list-styles-ifixit.vercel.app/Vulcan/troubleshooting-test

Closes https://github.com/iFixit/ifixit/issues/46306

### CODE REVIEW

**Comment by andyg0808** [comment]
deploy_block :+1: on https://github.com/iFixit/react-commerce/pull/1305

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by jordycosta** [comment]
QA 🟢 

The list style(s) look good to me 👍

**Comment by jordycosta** [comment]
QA 🟢

The list styles still look good to me 👍 
[View page tested](https://react-commerce-git-vulcan-add-list-styles-ifixit.vercel.app/Vulcan/troubleshooting-test)

**Comment by andyg0808** [comment]
un_deploy_block :+1: 
https://github.com/iFixit/react-commerce/pull/1305 went out.

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Pull request merged**
