### PR TITLE
Upgrade strapi version

### PR DESCRIPTION
**Pull request by dhmacs**
I had implemented this before #555 was opened. This one also converts the project to use Typescript.

cc @masonmcelvain 

## Changelog

- Upgrade Strapi to v4.3.0
- Refactor `backend` folder to use Typescript (excluding the seeding plugin that will be addressed in a follow-up PR)

## QA

1. Open Vercel preview
2. Perform a smoke test to verify that product list page still renders correctly
3. Open [Govinor preview](https://upgrade-strapi-version.govinor.com/admin) of this branch
4. Navigate to settings and verify that the version is `4.3.0`
5. Change some data and verify that changes are reflected in the frontend (note that CDN caching might affect this step, so you might need a few refreshes to get fresh data on the frontend)

<hr/>

⚠️ ⚠️ ⚠️ After merging this, we need to re-deploy the production instance of Strapi as well

cc @sterlinghirsh

### CODE REVIEW

**Comment by sterlinghirsh** [comment]
CR :zap: deploy_block :zap: If we update Strapi without updating the frontend or if we update the frontend without updating Strapi, will that break prod? When we deploy this, it will auto deploy the frontend changes, and then we'll have to manually update Strapi. If we can test this with new frontend / old strapi and it works, then we're good to deploy. Otherwise we have to figure out a plan.

**Comment by dhmacs** [comment]
@sterlinghirsh all the changes have been made to the backend (the few frontend changes that you see are just due to code formatting). There are no breaking changes, so once this passes QA I think we're good 👍

**Comment by jordycosta** [comment]
QA 🟢 

Product list page is rendering correctly on [preview](https://react-commerce-prod-git-upgrade-strapi-version-ifixit.vercel.app/) ✔️ 
[Govinor preview](https://upgrade-strapi-version.govinor.com/admin) data changes are shown 👍 

---

### Testing Procedure:
1. Navigate to the [Vercel preview](https://react-commerce-prod-git-upgrade-strapi-version-ifixit.vercel.app/)
2. Ensure that the product list is rendered correctly
3. Navigate to the [Govinor preview](https://upgrade-strapi-version.govinor.com/admin)
4. Click on **Settings**
5. Ensure the Strapi version is v4.3.0
6. Make a data change in the [Content Manager](https://upgrade-strapi-version.govinor.com/admin/content-manager/)
7. Ensure that change is reflected on the frontend

**Comment by danielbeardsley** [comment]
CR :+1: 

Changes seems OK and I'm excited about typescript.

Are the changed files (all those in `backend`) generated? OR Do we have to hand-create and hand-convert them? i.e. Does strapi generate JS files and we have to hand-convert to typescript each time?

**Comment by danielbeardsley** [comment]
un_deploy_block :+1:  given what @dhmacs said.

**Pull request merged**
