### PR TITLE
Stars: Make reviews accessible

### PR DESCRIPTION
**Pull request by jarstelfox**
QA
---

* Ensure you screen reader now reads the rating

Connects: https://github.com/iFixit/ifixit/issues/51161

### CODE REVIEW

**Review by ianrohde — DISMISSED** [review]
CR 💯

**Comment by erinemay** [comment]
### Productlist:
@jarstelfox, I noticed on main that the number of reviews on a productlist page is read. On this branch it isn't. When I scroll through the items, I get the appropriate "Rated ${product.reviews.rating} out of 5 stars" read aloud to me, but it skips to the price instead of reading aloud the number of reviews. 

That number already wasn't clear because it was just a number read out, but now it's not read at all. 

image


### Product Page
Works. Tabbing through, I get the price, "Rated ${product.reviews.rating} out of 5 stars", and then "# reviews"

**Comment by jarstelfox** [comment]
Fixed

**Comment by erinemay** [comment]
> Fixed

Yep. QA 🍰 It's now reading me: "Rated ${product.rating} out of 5 stars with ${product.rating_count} reviews" on productlist pages.

Using a screen reader to interact with the star count on productlist and product pages is now much nicer. The screen reader reads the product rating and the review count clearly on both page types.

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Pull request merged**
