### PR TITLE
Collection filters improvements

### PR DESCRIPTION
**Pull request by dhmacs**
This PR adds many improvements to collection filters and collection subcategories.

The main improvements are:

- Makes the filters card sticky so that the user can scroll products while filters stay in place
- Makes filters options collapsible
- Virtualizes filters list to improve performances when a collection has many filters (you can read more about this technique [here](https://reactjs.org/docs/optimizing-performance.html#virtualize-long-lists))
- Changes subcategories UI/UX
- Adds a show more button to expand the collection description
- Makes pagination controls responsive
- Improves product list responsive styles
- Improves Algolia hooks internals to prevent some bugs

## Known issues

These are known issues that it's probably better to fix on a different PR

- Accordion animation on filters has still some issues (mainly due to problems that arises with list virtualization)
- #42 

## QA

1. Visit the Vercel PR preview
2. Visit any collection page that contains products
3. Test the improvements described above

### CODE REVIEW

**Comment by ardelato** [comment]
The following are good 👍 


- [x]  Filter bar should now be sticky
Filter is Sticky
- [x]  Filter options should be collapsible
- [x]  Filters list should have better performance
- [x]  Different UI/UX to subcategories
- [x]  Add `show more` button for expanding collection description
- [x]  Pagination controls should be more responsive
- [x]  Product lists responsiveness should be improved

---

dev_block ☁️  there are some logistic and UX issues. Feel free to mark any of these as something that won't be addressed in this pull. 

<details>
	<summary>1. I expected there to not be products list div if there are no products to list </summary>

While navigating the Parts, I saw that the products list div being rendered when there were no results for any corresponding products. This products list div takes up a majority of the page so if there are no results returned then I see no point in rendering the entire component.

This can be seen on the Root level as well as other collections like `/collections/powerbook`

Product Listing on Root level?


</details>

<details>
	<summary>2. There seems to be a weird bubbling up animation for the filters list </summary>

While on the `/collections/macbook` page, I selected the `Item Types` filter which expanded. I then collapsed the filter but noticed that some filters returned to their position immediately while other filters scrolled back into position?

I used the Animation Chrome Dev Tool to slow down and track the animations in the page.

https://user-images.githubusercontent.com/22064420/126719450-81302bbd-8bb3-479b-9709-ee292d5eb3ad.mp4



</details>

<details>
	<summary>3. Missing Product Images? </summary>

I guess this is more of a question, but is there supposed to be missing or broken product images?

Missing Images



</details>

<details>
	<summary>4. Associated Product Links? </summary>

Another question, but should the products list have corresponding links for purchase or reference? Will this be something added in later down the line?

</details>

<details>
	<summary>5. Displaying out of stock products? </summary>

Will inventory stock be taken into account for products displayed?
    - Example the `MacBook Pro 15" Retina (Mid 2018-2019) Right Speaker`  option 2 (Used) is in Akeneo at $14.99, but there does not seem to be any stock available for it. However, the products listings show that price since it is the lowest one for that product code?

</details>

<details>
	<summary>6. Images seem to be cropped instead of scaled down to fit the containers </summary>

 It seems that product images, including for the collection, are cropped to fit inside the container. 
Part Image Not Scaled


Images cropped instead of scaled down


</details>

<details>
	<summary>7. Some filter options do not accurately describe filter option</summary>

Meaning the filter or attribute title does not accurately represent what the attribute is mapped to for the associated product.

Example, when `Bluetooth Card` is selected the `Variant Text` lists the different types of bluetooth. While selecting a different item type, the `Variant Text` lists different options but nothing seems to be easily related to the term `Variant Text`.

Variant Text literal?

</details> 

<details>
	<summary>8. Some filters are not populated/associated correctly </summary>

Example is the Part Only items → MacBook 12" Retina (Early 2016-2017) Trackpad option 1 is marked as a Part Only but is not seen in the filters page.


https://user-images.githubusercontent.com/22064420/126720323-df1ddff9-132f-4a2b-8d8d-8a726156fb81.mp4


</details>

<details>
	<summary>9.  Discrepancy between filter options and products listed in terms of variants </summary>

On the surface, there is no knowledge that variants exist for the product listed and that the price list is associated to the lowest price of one of the variants. This can cause confusion as to what the user is actually looking at, searching for, or potentially willing to purchase.

Example: The filter counter counts the variants as well, but the variants are not displayed nor hinted that there are variants for the products listed. As such, the filter states there are **5** batteries but only displays **2** products. 

Filter counts variants but variants are not displayed or hinted at??

</details>

<details>
	<summary>10. Last container does not get populated in grid view </summary>

In grid view, the last row’s third column does not get populated even though there are more items in the list?

Grid View no last 3 column item

</details>

<details>
	<summary>11. Clearing search field is not user friendly </summary>

There is no clear button or option for the search field, only way to remove the search text is to select and delete the search text. I expected there to be a clear search button or something of the like.

No clear button for search field

https://user-images.githubusercontent.com/22064420/126720989-464361fd-4b4e-47a6-bcb4-18e54c4a598f.mp4


</details>

<details>
	<summary>12. Lots of layout shift with pagination </summary>

Due to the products list container not being a static height, it shifts when you paginate because the product titles and/or product descriptions are of varying length. Therefore, as you paginate, the new products listed make cause the product list container to resize to fit the new products. 


https://user-images.githubusercontent.com/22064420/126721177-0c5ffca2-525e-48c8-a425-dbe5336bd471.mp4


</details>

<details>
	<summary>13. Same with the filter options, there is associated layout shifts </summary>

This is more of shifting what is in view for the user. If you scroll half-way across the page and select one of the filters, you won’t be taken back into position to view the items in the list, you will need to scroll up. Essentially the products list is not staying within view when filters are applied.



https://user-images.githubusercontent.com/22064420/126721336-228ee845-d531-431f-8a74-ed173b123460.mp4




</details>

**Comment by dhmacs** [comment]
> 1. I expected there to not be products list div if there are no products to list

I think this should be solved when all collections will be populated.. A collection without products should probably not exist. I'm not sure how we want to handle this. Perhaps we should not render the section at all as you are suggesting, but we might also want to send an error via Sentry when we fetch collections that don't have products. 

I'm tracking this here #49 

I think we should address this on a separate PR.

> 2. There seems to be a weird bubbling up animation for the filters list

Yep, this is a known bug. It happens because elements that are further down the list are unmounted due to virtualization. When they are scrolled back into view they are just mounted in place without animation.

I'd like to figure this out on another PR, because potentially it requires a considerable amount of work to be fixed (we might need to implement our own custom virtualization library to get this done)

> 3. Missing Product Images?

Ideally we shouldn't have missing images on products, but since this might happen I'm planning to add a fallback image (on a separate PR)

#47 

> 4. Associated Product Links?

Yes, products link will be added eventually when we figure out the context in which this page will be deployed. 👍 

> 5. Displaying out of stock products?

I'm not sure what's the policy for out of stock products on collections. 
I've created an issue to discuss this #50

This is also a topic for a separated PR

> 6. Images seem to be cropped instead of scaled down to fit the containers

We discussed in the last meeting and we agreed to try to make some changes to the design to preserve 4:3 aspect ratio.

I'm tracking this here #51

We can also address this into another PR

> 7. Some filter options do not accurately describe filter option

I guess this is a data issue, so I'm going to tag @evannoronha and @sterlinghirsh. 

> 8. Some filters are not populated/associated correctly

I've checked the Algolia index and it returns the same result, so I think it's a sync issue between Akeneo and Algolia @evannoronha @sterlinghirsh 

> 9. Discrepancy between filter options and products listed in terms of variants

I forgot to mention this, but the numbers next to filter options are there only for debug purposes, they will be removed before the solution is deployed into production. I can also remove them right now if you'd like

> 10. Last container does not get populated in grid view

I've fixed this by fetching 24 items per page, so you can divide it both by 3 and 2 👍 

> 11. Clearing search field is not user friendly

Absolutely, we should list the search string as an applied filter, and clear it when we clear the filters 👍  
I'll track this #52

I'll open a different PR for this too.

> 12. Lots of layout shift with pagination

This is a known issue, I'm tracking it here #53

I'll address this on a separate PR

> 13. Same with the filter options, there is associated layout shifts

This is a known issue, I'm tracking it here #54

I'll address this on a separate PR

## Recap

Thanks for the great job in spotting all these issues 👏  

For the sake of merging this huge PR soon I want to push as much work as possible to other smaller PRs (this will help me also to go on with other features that require this PR).

**Comment by ardelato** [comment]
>> 2. There seems to be a weird bubbling up animation for the filters list

> Yep, this is a known bug. It happens because elements that are further down the list are unmounted due to virtualization. When they are scrolled back into view they are just mounted in place without animation.
> I'd like to figure this out on another PR, because potentially it requires a considerable amount of work to be fixed (we might need to implement our own custom virtualization library to get this done)

Rodger that, I created a separate issue to keep track of it -> #55

>> 9. Discrepancy between filter options and products listed in terms of variants

> I forgot to mention this, but the numbers next to filter options are there only for debug purposes, they will be removed before the solution is deployed into production. I can also remove them right now if you'd like

Oh rodger that, then its fine to keep it, it is useful for debugging 🙌 

---

un_dev_block 🌤️  thank you for creating the GitHub issues to keep track of the issues that were noted 🙌 

- [x] 1. I expected there to not be products list div if there are no products to list -> https://github.com/iFixit/react-commerce/issues/49
- [x] 2. There seems to be a weird bubbling up animation for the filters list -> #55 
- [x] 3. Missing Product Images? -> #47
- [x] 4. Associated Product Links? -> Will be added in later down the line
- [x] 5. Displaying out of stock products? -> #50
- [x] 6. Images seem to be cropped instead of scaled down to fit the containers -> #51


- [x] 9. Discrepancy between filter options and products listed in terms of variants -> debugging tool 
- [x] 10. Last container does not get populated in grid view -> fixed with bd3f705
- [x] 11. Clearing search field is not user friendly -> #52 
- [x] 12. Lots of layout shift with pagination -> #53
- [x] 13. Same with the filter options, there is associated layout shifts -> #54

---

QA 👍  on issue **10. Last container does not get populated in grid view**
Fixed Empty Slot

---

deploy_block ☁️  to get confirmation back from @evannoronha and/or @sterlinghirsh on the following issues:

- [ ] 7. Some filter options do not accurately describe filter option
- [ ] 8. Some filters are not populated/associated correctly

**Comment by cdcline** [comment]
CR 👍

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by kwiens** [comment]
un_deploy_block 👍  Let's fix these issues in a followup pull.

Great work everyone!

**Pull request merged**
