### PR TITLE
Add links to featured products section

### LINKED ISSUE #727: Product Page: Link reviews to review section
The reviews stars and text should be a link to the product reviews section.
image

We have this behavior on our php product pages.
Example: Stars and review # on https://www.ifixit.com/Store/iPhone/iPhone-11-Screen/IF426-000?o=2 links to https://www.ifixit.com/Store/iPhone/iPhone-11-Screen/IF426-000?o=2#productReviews

### LINKED ISSUE #767: Add links to product page featured products section
The current implementation of the featured products section is missing links to the products.

Screenshot 2022-10-04 at 12 11 20

### PR DESCRIPTION
**Pull request by dhmacs**
closes #767 

## QA

1. Visit a [product page](https://react-commerce-git-add-product-page-featured-prod-cbf560-ifixit.vercel.app/Products/pro-tech-toolkit) on the Vercel preview
2. Verify that the featured products at the bottom of the page link to product pages

### CODE REVIEW

**Review by masonmcelvain — DISMISSED** [review]
CR ✌🏻

**Comment by erinemay** [comment]
QA 👍 Works on desktop and mobile without errors.

**Comment by dhmacs** [comment]
Amazing I didn't catch this while developing 🤔 Should be fixed now 👍 

cc @erinemay 

un_dev_block 🟢

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by jordycosta** [comment]
QA 🟢 

Featured products at the bottom of the page link to product pages ✔️ 
Not seeing any application or console errors 👍 

**Demo**

firefox_f7vYXDhBCh

**Pull request merged**
