### PR TITLE
Add carousel to product page

### LINKED ISSUE #669: Make product section responsive

### LINKED ISSUE #674: Add mobile-friendly carousel functionality to gallery in product page

### PR DESCRIPTION
**Pull request by federicobadini**
closes #674 
closes #669 

This PR introduces a new product gallery component to display product images.
The product page contains two product galleries: one for desktop, one for mobile.
The two galleries are kept in sync so that the same image is shown even if the screen dimensions changes (eg rotating a mobile device).
The whole productSection inside the product page (so gallery + product variant selectors) is now responsive

## QA

1. Visit the Vercel preview
2. Check that the gallery is working properly
3. Check that mobile and desktop galleries are kept in sync
4. Check that the product section is responsive

### CODE REVIEW

**Comment by deltuh-vee** [comment]
dev_block ✊ 
Are you supposed to be able to click on these in order to change the picture?
CleanShot 2022-09-07 at 14 51 58
It seems to work when I'm on the second picture and switching to the first picture, but not the other way around.

**Comment by federicobadini** [comment]
> dev_block ✊ Are you supposed to be able to click on these in order to change the picture? CleanShot 2022-09-07 at 14 51 58 It seems to work when I'm on the second picture and switching to the first picture, but not the other way around.

Do you have a repro for that? 
It would be very useful to know if you followed a specific set of operations or if you worked on a specific product.
I'm asking because I do not see issues on either brave/chromium or safari:

https://user-images.githubusercontent.com/7805759/188992842-25f071d5-71cd-401b-8c17-44cb1edb534f.mov

**Comment by deltuh-vee** [comment]
@federicobadini 
Try toggling to the Silver color on this item: https://react-commerce-git-add-carousel-to-product-page-ifixit.vercel.app/Products/macbook-air-13-late-2020-trackpad

**Comment by federicobadini** [comment]
> @federicobadini Try toggling to the Silver color on this item: https://react-commerce-git-add-carousel-to-product-page-ifixit.vercel.app/Products/macbook-air-13-late-2020-trackpad

Was due to some handlers not being unsubscribed. I've updated the PR

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 un_dev_block 👍🏻

**Comment by jordycosta** [comment]
QA 🟢 

The gallery is working properly on desktop/mobile 👍 
Mobile and desktop galleries are kept in sync ☑️ 
The product section is responsive ❔ (see deploy_block)

---

deploy_block 🟨 

Changing the condition of the product removes the carousel + gallery pictures, and also displays no image for a product at times

firefox_e8Gj46yAB0

no-image

**Comment by federicobadini** [comment]
> Changing the condition of the product removes the carousel + gallery pictures, and also displays no image for a product at times

Images shown in the cart are a subsection of the product images. 
So the set of selected images may change according to the selected variant. 

To be more precise, images has the `sku` value of their corresponding associated variant encoded as altText. 
When a variant is selected only images with the associated sku or images not associated to any sku are considered valid for that variant.

That is why it may happen that the number of images associated with a variant changes. 
If there is only one image (or zero) we are not even showing a carousel - we fall back to a simple image

**Pull request merged**
