### PR TITLE
Add structured data on product page

### LINKED ISSUE #853: Add structured data on Product Page
Add jsonld

This doc lists "Required" properties, as well as some other properties that it'd be great to implement later: https://docs.google.com/document/d/1gprBDfp7ZQ7nG57DE45JOMG4YNr8F7uqr2lCQTBiMyA/edit#

### PR DESCRIPTION
**Pull request by federicobadini**
closes #853 

According to the choices in #972 we inserted the aggregate rating data but not the single reviews.
Brand has been tied to the `vendor` shopify product field. 

cc @ifixitmaxb 

### QA

1. Visit Vercel preview
2. Verify that both `breadcrumbs` and `product` snippets are present on page
3. Verify that they match correctly the InStock/OutOfStock and the New/Refurbished/Used state of the product

### CODE REVIEW

**Comment by deltuh-vee** [comment]
QA 🎬 
* Both `breadcrumbs` and `product` jsonld snippets are present on page.
* The Product snippets match the stocking status and the New/Refurbished/Used state of the product

**Review by masonmcelvain — CHANGES_REQUESTED** [review]
CR ✌🏻 but we need to regenerate pnpm-lock

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Comment by k0rvusk0r4x** [comment]
- [Structured Data Testing Tool](https://validator.schema.org/) shows this is continuing to work as [here](https://github.com/iFixit/react-commerce/pull/1082#issuecomment-1332647743).
- No warnings or errors showed.

QA 😺

**Pull request merged**
