### PR TITLE
Refactor header components

### LINKED ISSUE #245: Making header component reusable

### PR DESCRIPTION
**Pull request by dhmacs**
fixes #245 

## Changelog

- Export user model as an `auth-sdk` package (this could be later expanded with other auth related stuff)
- Export header components from `ui` package
- Create a `helpers` package to share reusable helpers
- Refactored layout and header components to use components from `ui` package

## QA

1. Visit the Vercel PR preview (replace vercel.app with cominor.com)
2. Visit all parts product list
3. Verify that everything works the same way as for the main branch

### CODE REVIEW

**Comment by erinemay** [comment]
dev_block 🦕  I'm seeing a new console error and one of the user menu buttons is no longer functional:

**New error** that shows up when a user is logged out on /Store/Parts, or any other collection (like /Store/Parts/Kindle_Tablet). I'm not seeing this error on the main branch (https://react-commerce.vercel.app/Store/Parts).
image

`Orders` button is no longer linking to /User/Orders on this branch

https://user-images.githubusercontent.com/72166715/163015811-fe54a640-e4e9-4b11-8ad8-d5b4679cc98b.mp4

**Comment by dhmacs** [comment]
@erinemay everything should be fixed now 👍

**Comment by erinemay** [comment]
Yay! un_dev_block 🥳

**Comment by erinemay** [comment]
QA 🔥 Both issues are fixed. The header looks and behaves the same as on the main branch. All links are appropriate and expected based on main branch behavior.

**Comment by lithobraking** [comment]
CR ✨

**Comment by sterlinghirsh** [comment]
CR :zap:

**Pull request merged**
