### PR TITLE
Hotfix: Handle undefined user teams from api

### PR DESCRIPTION
**Pull request by masonmcelvain**
Fixes this:

image

### CODE REVIEW

**Comment by danielcliu-ifixit** [comment]
CR :v:

**Review by danielcliu-ifixit — DISMISSED** [review]

**Comment by masonmcelvain** [comment]
deploy_block ✋🏻 this seems like a local storage caching problem actually

**Comment by masonmcelvain** [comment]
un_deploy_block ✌🏻

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Pull request merged**
