### PR TITLE
Proposal active image always first

### LINKED ISSUE #861: Add scroll buttons to image thumbnail list
Without scroll indicators, it's unclear that there are more thumbnail images available to click on.

This product has more images than can fit in the row of thumbnails.
https://react-commerce.vercel.app/products/Precision-Tweezers-Set

image

### PR DESCRIPTION
**Pull request by federicobadini**
closes #861 

As proposed in [comment](https://github.com/ifixit/react-commerce/issues/861#issuecomment-1289278944) this PR helps the user in understanding that there are more thumbnails available.

### QA

1. Visit [Vercel preview](https://react-commerce-git-improvements-on-product-galler-0c72c4-ifixit.vercel.app/products/fix-the-world-t-shirt)
2. Verify that the currently active image is always positioned as the leftmost visible in the thumbnails carousel
3. Only exception is when the carousel cannot scroll anymore to the right

### CODE REVIEW

**Review by sterlinghirsh — APPROVED** [review]
CR :zap: This is an improvement for sure. I might want to come back later and use a transparent gradient to indicate when there are more images, or start scrolling the container when the active image is in the middle, but I'm okay with this for now.

**Comment by deltuh-vee** [comment]
dev_block ✊ 
This seems to obscure that there's images to the left even more than before. Looking at the Precision Tweezers Set, 
image
you can't tell there's images to the left unless you notice the dot indicators.

**Comment by sterlinghirsh** [comment]
Good catch @deltuh-vee. I didn't notice that we weren't starting with the first image. I think the behavior of keeping the selected image's thumbnail on the left is fine, but we'd like to start on the first image, even if it's a product-level instead of variant-level image. Starting in the middle of the list is too confusing.

**Comment by federicobadini** [comment]
Thumbnails are now rendered with a gradient overlay on the sides where more images could be revealed by scrolling.
The currently selected image is always kept on the left but outside of the gradient overlay.
So it is initially positioned on the very left and then is it kept as second leftmost image.

**Comment by deltuh-vee** [comment]
QA 🎬 
un_dev_block 👍 
* Selected images start at the left most image
* Gradients have been added to suggest there are more images

**Comment by federicobadini** [comment]
I've noticed a slight regression and I've modified the code in order to continue keeping mobile and the desktop carousel in sync.

**Comment by jordycosta** [comment]
Screenshot 2022-11-04 090546

I noticed after scrolling all the way to the right, the last image still appears that there are more images beyond that since the gradient is still present

last

Same goes for scrolling back to the first image in the carousel

first

**Comment by federicobadini** [comment]
> I noticed after scrolling all the way to the right, the last image still appears that there are more images beyond that since the gradient is still present

Is this a drag without a select or an arrow click here right?

**Comment by deltuh-vee** [comment]
> Is this a drag without a select or an arrow click here right?

Yes. Clicking in the middle will also result in double gradients after dragging.

**Comment by deltuh-vee** [comment]
dev_block ✊ on resolving merge conflicts.

**Comment by jordycosta** [comment]
QA 🟢 

Active images start at the left 👍 
The scroll gradient issue in https://github.com/iFixit/react-commerce/pull/879#issuecomment-1303815963 is fixed ✔️ 

firefox_9BblC3nPBC

**Comment by federicobadini** [comment]
Do you see other details to refine here or we are ready to ship? 🙂

**Pull request merged**
