### PR TITLE
Optimize images

### LINKED ISSUE #51: Improve images by preserving 4:3 aspect ratio

### PR DESCRIPTION
**Pull request by dhmacs**
This PR closes #51 and #47 and fixes a few minor issues.

## QA

1. Visit the Vercel PR preview
2. Visit `/collections/macbook`
3. Verify that products without image render a placeholder image
4. Verify that images are rendered in a 4:3 ratio so that they are displayed correctly (some images though don't have a 4:3 ratio therefore they will be cropped)

### CODE REVIEW

**Comment by ardelato** [comment]
- [x] Missing images are good now 👍 
Missing image comparison

- [x] Collection images are no longer cropped 👍  
Collection Image ratio


--- 

@dhmacs is the `AspectRatio` component the thing applying the `object-fit: cover` property? Reason being, is images are still being cropped, but if you use `object-fit: contain` the aspect ratio is maintained and the images will be scaled down to fit within the container.

That said, is there a specific reason for using `object-fit: cover`?

| Object-fit: Cover	| Object-fit: Contain	|
|:---:|:---:|
|Product image still cropped	|	Object-fit contain|

**Comment by dhmacs** [comment]
> That said, is there a specific reason for using `object-fit: cover`?

@ardelato No, it was applied by default by `AspectRatio` component and I didn't realize it. Thank you for pointing this out! I've already pushed the fix 👍

**Comment by ardelato** [comment]
QA 👍 

un_dev_block 👍 

- [x] Product images are no longer cropped to fit the container
Non-cropped images

## Steps Taken:
1. Look at Vercel preview and confirmed the images noted in https://github.com/iFixit/react-commerce/pull/59#issuecomment-889503741 were no longer cropped

**Comment by cdcline** [comment]
CR 👍

**Comment by sterlinghirsh** [comment]
CR :zap:

**Pull request merged**
