### PR TITLE
Add lifetime guarantee banner

### PR DESCRIPTION
**Pull request by dhmacs**
This PR adds the collection page lifetime guarantee banner.

## QA

1. Visit the Vercel PR preview
2. Visit any collection page (other than `/parts` and `/tools`)
3. Verify that the lifetime guarantee banner is displayed and looks like the mockup (see below for reference):

    Screen Shot 2021-05-28 at 17 59 08

4. Verify that the banner is responsive

### CODE REVIEW

**Comment by deltuh-vee** [comment]
QA 🎬

The lifetime guarantee banner appears and is reponsive to window size

## Steps Taken

1. Visited [https://react-commerce-git-add-lifetime-guarantee-banner-ifixit.vercel.app/collections/mac](https://react-commerce-git-add-lifetime-guarantee-banner-ifixit.vercel.app/collections/mac)
2. Adjusted the window size
3. Verified that the banner resizes accordingly ✅
4. Clicked the Learn more button on the banner
5. Verified I get linked to the warranty info ✅
6. Also checked the banner loads and is resizable(if applicable)
    - [x]  Safari on iPhone 12 mini
    - [x]  Galaxy S9 on Chrome
    - [x]  Edge on Windows 10
    - [x]  Firefox on macOS
    - [x]  Safari on macOS

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by masonmcelvain** [comment]
CR 👍🏻

**Comment by masonmcelvain** [comment]
(Looks like Ian's CR didn't get detected by pulldasher, but this is ready to merge)

**Pull request merged**
