### PR TITLE
Bit table section frontend

### PR DESCRIPTION
**Pull request by federicobadini**
Closes https://github.com/iFixit/ifixit/issues/49327

Figma: https://www.figma.com/file/BolmFORO6ZfHXePOSyEGSS/iFixit---Page-sections?type=design&node-id=1766-10708&mode=design&t=z7yor1h57OAQfLpy-0

This PR introduce the frontend components for the BitTable section.

### QA

1. Visit Vercel preview [here](https://react-commerce-git-bit-table-section-frontend-ifixit.vercel.app/products/repair-business-toolkit)
2. Verify that the frontend is aligned with the Figma mockup

### CODE REVIEW

**Comment by federicobadini** [comment]
deploy block 🔴 on #2075

**Comment by deltuh-vee** [comment]
QA 🎬 
Bit table section matches the figma mockup.

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by deltuh-vee** [comment]
un_deploy_block 👍

**Pull request merged**
