### PR TITLE
Header: Restore previous iFixit logo

### PR DESCRIPTION
**Pull request by ianrohde**
## Issue

We're restoring the standard iFixit logo on the header.

## CR/QA

Straight-forward change, but let's make sure there are no regressions.

`Wordmark` component contains the standard iFixit logo SVG.

Linked to https://github.com/iFixit/ifixit/issues/51066

### CODE REVIEW

**Comment by ianrohde** [comment]
deploy_block 🔴 to sync with matching php app changes

**Comment by deltuh-vee** [comment]
QA 🎬 
Old header logo has been restored.

**Review by aburke07 — DISMISSED** [review]
CR :alien:

Edit: whoops, I thought this was the PHP side change.

**Review by hcutrone — DISMISSED** [review]
CR 🌯 Nice!

**Comment by ianrohde** [comment]
One of the modified files was deleted in https://github.com/iFixit/react-commerce/pull/2191/

**Comment by ianrohde** [comment]
Closing this in favor of a new clean PR. It's faster at this point 😒

**Pull request closed without merging**
