### PR TITLE
Part or Kit: make more accessible

### PR DESCRIPTION
**Pull request by jarstelfox**
We now will read out these are selected or not as well as state 'select <variant>'

Connects: https://github.com/iFixit/ifixit/issues/51161

### CODE REVIEW

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Comment by deltuh-vee** [comment]
QA 🎬 
Part or Kit is now labeled and can tell which one is selected.

**Comment by erinemay** [comment]
When I use a screen reader on a mobile product page, like https://www.ifixit.com/products/macbook-air-13-late-2010-2017-replacement-battery, it says neither are selected and I can't select either. Can someone confirm that this isn't happening to them? 

I get: not checked for both when I try to select either. 
I took long pauses between clicks in the video since my audio isn't quite synced with the video. 

https://github.com/iFixit/react-commerce/assets/72166715/9175310f-c504-4d49-b115-86892c38f0da

**Comment by jarstelfox** [comment]
@erinemay https://github.com/iFixit/react-commerce/pull/2161

**Pull request merged**
