### PR TITLE
Fix navigation issues

### LINKED ISSUE #216: Fix navigation menu issues
There are a couple of regressions on the main navigation menu.

- Hovering on the menu doesn't show it
  Screenshot 2022-03-18 at 17 28 04

- The slightly changes core primitives breakpoints makes the menu cut off at the `lg` breakpoint (1000px)
  Screenshot 2022-03-18 at 17 18 35

### PR DESCRIPTION
**Pull request by dhmacs**
fixes #216  

## QA

1. Visit the Vercel PR preview (replace `vercel.app` with `cominor.com`)
2. Visit parts product list page
3. Verify that the issues mentioned in #216 are fixed

### CODE REVIEW

**Comment by danielbeardsley** [comment]
CR :+1: 

I've changed `govinor.com` in your description with `cominor.com` (assuming it was just a mistake?)

**Comment by dhmacs** [comment]
> I've changed `govinor.com` in your description with `cominor.com` (assuming it was just a mistake?)

My bad! 🤦‍♂️  Thanks for fixing it 👍

**Comment by deltuh-vee** [comment]
QA 🎬 
* Hovering over header menu options shows the options
* Menu options are no longer cutoff

**Comment by sctice-ifixit** [comment]
CR :rose:

**Pull request merged**
