### PR TITLE
Add a flag to control the show all default value of product list children on large screen (frontend changes)

### LINKED ISSUE #682: Collections: Display 4 rows "devices" on /Tools parent collection
Just for /Tools parent collection, display 4 rows instead of the default 3. We want all the current child collections to show and not be hidden by "Show more".

### LINKED ISSUE #741: Collections: Display 4 rows "devices" on /Parts/Electronics parent collection
On [/Parts/Electronics parent collection](https://www.ifixit.com/Parts/Electronics), display 4 rows instead of the default 3. We want all the current child collections to show and not be hidden by "Show more".

Similar to https://github.com/iFixit/react-commerce/issues/682

### PR DESCRIPTION
**Pull request by federicobadini**
closes #682 
closes #741 

completes #974 

A new product list flag is now giving the possibility to show all product list children on large screen.
If enabled the list is not showing the `Show more` / `Show less` button on `> lg` screen sizes.
On smaller screen sized nothing should change.

Here is a preview of the `/Tools` page with the flag enabled:

Screenshot 2022-11-03 at 08 51 52

The same page on mobile is showing the `Show more` / `Show less` button as before:

Screenshot 2022-11-03 at 09 03 54

### QA

1. Visit Vercel preview
2. Verify that the implementation is coherent with the spec described above

### CODE REVIEW

**Comment by jordycosta** [comment]
dev_block 🟥 

When visiting the Vercel preview (with the feature flag)
> https://react-commerce-git-display-4-rows-devices-on-sele-6f124a-ifixit.vercel.app/Tools

I found that the Show more/less for the page description is showing on both desktop & mobile (should only be on mobile)

desktop-desc
mobile-desc

**Comment by jordycosta** [comment]
QA 🟢 

https://react-commerce-git-display-4-rows-devices-on-sele-6f124a-ifixit.vercel.app/Tools

When visiting the **Vercel** preview (flag-enabled):

1. All product list children are shown, on larger view-ports
2. On mobile, the Show more/less is shown _(not all product list children)_

---

### Screen Captures:

desktop

mobile

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 QA ✌🏻 as long as tests pass

**Pull request merged**
