### PR TITLE
Lets Fix the Hardcoded Proposition Text

### PR DESCRIPTION
**Pull request by danielcliu-ifixit**
## Overview
Jeff has some new text to implement for the propositions [here](https://docs.google.com/spreadsheets/d/1ghuenb5j9kyDK3-RJtSLeBctrXxOseOHJr3gHk5G65k/edit#gid=0). Let's update our propositions to match these desired texts.

## QA

Is the text right now? Does everything else look the same?

Closes: #910

### CODE REVIEW

**Review by danielbeardsley — APPROVED** [review]
CR :+1: 

Noice!

**Comment by jordycosta** [comment]
QA 🟢 

Looks good!

icons

header

---

deploy_block 🟨 on a question

The first two icons in the propositions shown appear to be not the same as in the spreadsheet

Screenshot 2022-10-26 140255

**Comment by jeffsnyder** [comment]
Don't worry about the icons in the document. That was just for reference as I was sharing the document around. @jordycosta @danielcliu-ifixit

**Comment by danielcliu-ifixit** [comment]
un_deploy_block :v:

**Pull request merged**
