### PR TITLE
Upgrade to Next.js 12

### PR DESCRIPTION
**Pull request by federicobadini**
The project has been updated to Next.js 12 and is now using the [SWC compiler](https://nextjs.org/docs/advanced-features/compiler).
Jest tests however are still run via `babel-jest` / `next/babel`.

This is due to the fact that SWC strictly adhere to the ESModules specification so, according to how a module is declared, we may have difficulties in mocking up functions.   Here is an example:

Screenshot 2022-08-11 at 00 33 09

 Function 1 is exported via named export, but since it is imported with a namespace notation, it ends up being not modifiable. So any mocking will fail.

This is tracked in several issues: 
https://github.com/swc-project/swc/issues/5205
https://github.com/swc-project/swc/issues/3843#issuecomment-1061382158
https://github.com/facebook/jest/issues/9430

There seems to be a [plugin](https://github.com/swc-project/swc/discussions/5151) specifically designed to solve this issue but currently overriding .swcrc in Next [is not admitted](https://github.com/vercel/next.js/discussions/30413#discussioncomment-1543513)

For those reasons I decided to - at least temporarily - continue using Babel for the Jest transform

cc @ardelato 

## QA
1. Visit the Vercel preview
2. Verify that there are no inconsistencies between the old Next.js 11 version and this version

### CODE REVIEW

**Comment by danielbeardsley** [comment]
Wow. I'm surprised how little had to change in our code... almost nothing; mostly config changes.

CR :+1: 

Thanks @federicobadini

**Comment by erinemay** [comment]
Compared [this preview](https://react-commerce-git-nextjs-12-ifixit.vercel.app/Parts) and the [main branch](https://react-commerce.vercel.app/Parts) and confirmed the following are identical:
- Header links and link previews
- Breadcrumb links, link previews, appearance
- Appearance of each entire page is identical by going down the page space by space - spot checked `/Parts` and `/Tools` homepages and a few Parts children pages
- Search facets: Behavior, appearance, content
- Images
- Search
- Pagination
- Tab titles
- List/box view
- Log in/out states and user profile links when logged in
- Mini cart and checkout from mini cart
- Footer appearance and links
- Item type collection pages

General:
- No new console errors on this preview
- Spot checked the prod preview and confirmed parity with live collection pages

Browsers:
- Windows 11 Chrome + FF
- MacOS + Safari
- iOS + Safari
- Android + Chrome

Everything looks good and behaves identical to the main branch EXCEPT, the mobile hamburger menu isn't opening on this branch. 

dev_block 🧷 It's not working on Safari or Chrome on mobile and tablet screen sizes. 

There aren't any errors in the console when clicking on the menu button, it just doesn't open. 

On iOS (image from iOS/Safari 15 on iPhone 13), after clicking on and failing to open the hamburger menu, the iFixit logo gets rendered like this:
image

<details><summary>Screen recordings</summary>

Android + Chrome

https://user-images.githubusercontent.com/72166715/184213449-8a932e3d-0014-4773-bfd1-a1d8f0eda209.mp4

iOS + Safari

https://user-images.githubusercontent.com/72166715/184213596-5f0eb8e9-f0e1-42ca-bd99-8e48c9cb361b.mp4

</details>

**Comment by federicobadini** [comment]
Fixed the drawer issue

**Comment by danielbeardsley** [comment]
CR :+1: 

Conflicts though.

**Comment by federicobadini** [comment]
> CR 👍
> 
> Conflicts though.

Solved

**Comment by erinemay** [comment]
un_dev_block 🛩️

**Comment by k0rvusk0r4x** [comment]
- The hamburger menu hand logo are now fixed.
- Otherwise, continues to look as [here](https://github.com/iFixit/react-commerce/pull/606#issuecomment-1212354999).

QA 😺

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Pull request merged**
