### PR TITLE
Mitigate #385 for iPhone devices

### LINKED ISSUE #385: Wrong vertical scrollbar in mobile filter list
<details>
<summary> Toggle View </summary> <br>

scroll
</details>

It appears that the filter list may at times use a different vertical scroll bar than what is intended, which can be shown in the above `.gif` file.

### PR DESCRIPTION
**Pull request by federicobadini**
closes #385

As agreed in the weekly meeting, we are going to mitigate the issue experienced by iOS users hiding the underlying body on small devices as soon as the drawer is shown. 

cc @sterlinghirsh 

## QA

1. Open [Vercel Preview](https://react-commerce-git-vertical-scrollbar-in-mobile-filter-ifixit.cominor.com/Parts) on a iOS mobile device
2. Verify that even in Safari - portrait mode - when the browser UI is not fully visible (i.e. the address bar is retracted, and the toolbar bar fully collapsed), the issue described in #385 is not present anymore

### CODE REVIEW

**Comment by jordycosta** [comment]
dev_block 🔴 

The issue seems to be fixed, however, there seems to be a new bug introduced.

> On a page load, the first two times I open the facet list, it will close on any vertical scroll.

> https://user-images.githubusercontent.com/95656772/180027190-6b02c6f2-a5b1-4ce9-b97c-38caa2287830.mov

**Comment by federicobadini** [comment]
Hi @jordycosta 

After digging a bit through this I think that the bug you are experiencing is not related with this PR.

I've noticed that if you access the preview from the `.cominor.com` url there is something strange going on with the api calls toward iFixit. Take a look at the url in the screenshot:

Screenshot 2022-07-21 at 12 04 42

Then i noticed that if you open the preview through the `vercel.app` [url](https://react-commerce-git-vertical-scrollbar-in-mobile-filter-ifixit.vercel.app/Parts), the api calls point at the right endpoints.

I suspect this strange behaviour may be tracked down to [this commit](https://github.com/iFixit/react-commerce/commit/7154743a201b85cb517a3ea2684ae8f1765287de):
The focus of the commit seems to be removing the `IFIXIT_ORIGIN` prefix in cases in which the website origin is on the same base domain of the api url. This however seems not to take into account subdomains.
The preview accessed via `cominor.com` and the api are on the same base domain, so many api calls fail because they end up pointing to non-existent relative urls.
Those several failing api calls seems then to trigger a few re-render of the page, giving you the illusion that the drawer disappears as a result of a scroll. 

Can you please verify this PR via the `vercel.app` url?

**Comment by jordycosta** [comment]
un_dev_block 🟩 

---

QA 🟢 

Verified that the vertical scroll behavior shown in https://github.com/iFixit/react-commerce/issues/385 is no longer present 👍 


### Testing Procedure:
1. Visited the [Vercel preview ](https://react-commerce-prod-git-vertical-scrollbar-in-mob-9015b2-ifixit.vercel.app/Parts)
2. Changed to mobile view, _both using a personal device and browser view_
3. Press on `Filters`
4. Ensure that the correct vertical scroll bar is being used

**Comment by sterlinghirsh** [comment]
CR :zap:

**Review by sterlinghirsh — APPROVED** [review]

**Pull request merged**
