### PR TITLE
Problems List: Finalize UI styles

### PR DESCRIPTION
**Pull request by ianrohde**
## Issue

We found a few UI issues when reviewing the Problems List page yesterday during a Vulcan meeting. This is a second pass at the styles to shore it up.

## CR/QA

[Figma link](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=1-122&mode=design&t=ayzLTnsYXY4NW2PN-0)

https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Google_Phone

**Fixed:**

- On mobile: Device images in question cards are variable size. [(ref link)](https://ifixit.slack.com/archives/CDFNZ4N4A/p1706051332728989)
- On mobile: Missing margin on the bottom of the question count. [(ref link)](https://ifixit.slack.com/archives/CDFNZ4N4A/p1706051332728989)
- Double-check desktop/mobile spacing variances
- Refactor the AnswerCard layout to vertically center the text
- Adjust Answers heading text (I reached out to Max about this earlier today. He's going to get back to me with any tweaks)

Connects https://github.com/iFixit/ifixit/issues/51698

### CODE REVIEW

**Review by aburke07 — DISMISSED** [review]
CR :alien:

**Comment by deltuh-vee** [comment]
@ianrohde 
Did you mean to swap the text in the Answers Cards?

CleanShot 2024-01-25 at 10 19 22
CleanShot 2024-01-25 at 10 19 32

**Comment by ianrohde** [comment]
> Did you mean to swap the text in the Answers Cards?

Definitely not - thanks!

dev_block 🔴

**Comment by ianrohde** [comment]
https://github.com/iFixit/react-commerce/pull/2220/commits/229d98150d4e8eca7d5e16fef8f4c46cfb1b09f8 fixes the order.

https://github.com/iFixit/react-commerce/pull/2220/commits/55e095d50c80cf23675f830c33d4e4da250f0c9f corrects the fontSize to 14px (I missed this previously)

<details>
<summary>fontSize Details</summary>

Screenshot 2024-01-25 at 10 50 47 AM

Screenshot 2024-01-25 at 10 51 00 AM

</details>

un_dev_block 🟢

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by erinemay** [comment]
Looks great! QA 👍 deploy_block 🌵 Feel free to address anything in follow up as I'm not sure what was introduced here and it's still hidden. The issues you've [noted above](https://github.com/iFixit/react-commerce/pull/2220#issue-2099281463) appear to be addressed. 

Style issues
<details><summary>1. Question cards overflow into the footer on Safari</summary>

This seems to be a Mac/Safari thing. I'm not seeing the same thing on Android+Chrome or Windwos+Chrome. 
When I look at the same desktop page on Sonoma + Chrome, the issue is resolved, but when I look at the same page on the iPhone 15 Pro Max with Chrome, it is present. 

### Mobile
https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Samsung_Television
iPhone 15 Pro Max on Browserstack with Safari

image


Subtler: iPhone 15 on Browserstack with Safari 17
image


### Tablet

iPad Pro 12.9 2021 with Safari 
https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Nintendo_Switch
image

### Desktop 
Sonoma with Safari 17
https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Nintendo_Switch
image


</details>

Non-Style issues
<details><summary>2. Image next to device is troubleshooting wiki image</summary>

The image next to the device in problem card is the same as the troubleshooting wiki image. Should this be the device image?
https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Steam_Deck
image

</details>

**Comment by sctice-ifixit** [comment]
> The image next to the device in problem card is the same as the troubleshooting wiki image. Should this be the device image?

Yes, it should be the device image. But I think we should get rid of the device "row" entirely when we start splitting problems into sections by device, per [the mock-up](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?type=design&node-id=1417-51724&mode=design&t=JqGALAiUqNsFbGG4-4).

**Comment by ianrohde** [comment]
Safari issue fixed with https://github.com/iFixit/react-commerce/pull/2220/commits/9fcdc6f0d16eb77c3e15a9489a5720e202a62de8

<details>
<summary>Details</summary>

Screenshot 2024-01-25 at 3 05 21 PM

</details>

**Comment by erinemay** [comment]
QA 🌵 Safari issue is fixed. The pages look good (like the mockup) on iOS+Safari mobile and tablet, MacOS+Safari, Android+Chrome, Windows+Chrome.

Issues noted in the description are fixed.

Pages checked:
https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Samsung_Television
https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Nintendo_Switch
https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Dryer
https://react-commerce-prod-git-problems-list-finalize-ui-styles-ifixit.vercel.app/Troubleshooting/Christmas_Lights

**Comment by ianrohde** [comment]
Thanks for catching that issue @erinemay 🙌

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Pull request merged**
