### PR TITLE
Add Sharp to Dependencies for Production.

### PR DESCRIPTION
**Pull request by danielcliu-ifixit**
## Overview

When running `next start` we were getting the warning that the optional sharp dependency should be added when running a production deployment. This should solve that error by adding `sharp` as a dependency to the project.

## CR
Super simple.

## QA
Easy to test.
1.) run `pnpm install:all`
2.) run `pnpm build`
3.) run `pnpm start`
4.) go to `localhost:3000/Parts`
5.) click on "Android Parts"
6.) a warning should show up in your terminal for using `sharp` if it isn't installed here (ie on main), and shouldn't if it is installed (ie on this branch).

Closes: #397

### CODE REVIEW

**Comment by danielcliu-ifixit** [comment]
deploy_block :v: on making sure this is still an issue

**Comment by sterlinghirsh** [comment]
Should this be on the frontend/package.json? Seems like if it's needed by next.js it should go there instead of the root package.json.
CR :zap: dev_block :zap:

**Comment by danielcliu-ifixit** [comment]
I haven't had lock files in a repo before, are these amount of changes expected for it?

**Review by danielbeardsley — APPROVED** [review]
CR :+1: 

Annoyingly, sharp is still not at version 1.0

Yet it's the recommended tool for production next.js deployments and has millions of downloads.

image

**Comment by k0rvusk0r4x** [comment]
1. Ran ` pnpm install:all`.
2. Got the message that `pnpm` is no a command.
3. Ran `curl -fsSL https://get.pnpm.io/install.sh | sh -` to install `pnpm`.
4. Ran ` pnpm install:all` again.
5. Got the message that the command failed.
6. Checked out this branch.
7. Ran ` pnpm install:all` again.
8. Still got the message that the command failed.

What is the setup to get `pnpm` to function here?

**Comment by danielcliu-ifixit** [comment]
@k0rvusk0r4x The QA commands were if you had setup `react-commerce` successfully (locally i think is ideal). There are instructions in the repo's README on how to install the required libraries for this project for ubuntu-based systems.

**Comment by batbattur** [comment]
dev_block 🚒 on resolving merge conflicts

**Comment by danielcliu-ifixit** [comment]
un_dev_block :v:

**Comment by deltuh-vee** [comment]
QA 🎬 
No longer getting warnings about `sharp` not being installed.

**Review by batbattur — APPROVED** [review]
CR 🚛

**Pull request merged**
