### PR TITLE
Vulcan: Show author and update information

### PR DESCRIPTION
**Pull request by andyg0808**
I've done all this in one pull because it's all part of the same `div` on the page, so breaking it up would generally involve shipping pulls which build on each other (to avoid deleting code from the mockup export which we'd then just re-add).

## QA Notes
Please check that the behavior and choices seem reasonable and match the mockup.

Closes https://github.com/iFixit/ifixit/issues/46828
Closes https://github.com/iFixit/ifixit/issues/46831
Closes https://github.com/iFixit/ifixit/issues/46845

### CODE REVIEW

**Comment by deltuh-vee** [comment]
dev_block ✊ 
We'll want the "and" to be blue and also use "contributor"(when there's only one).
image

**Comment by andyg0808** [comment]
@deltuh-vee Point well-taken on plurals (and nice catch!). On the blue bit, the mockup doesn't show it that way:
image
https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=9319-156393&t=66jjKuk54XjfedBf-0

**Comment by andyg0808** [comment]
un_dev_block :+1: 
Fixed contributor plural.

**Comment by deltuh-vee** [comment]
Is this the correct mockup? https://www.figma.com/file/TOg0KMcfXCCa2K7pkyXM6D/iFixit---Vulcan?node-id=59%3A1692&t=R33H7iNwpjM0xxti-0
Here's what I see:

**Comment by andyg0808** [comment]
@deltuh-vee Yes, I think that's no longer the current mockup. I'm pretty sure the current mockup is the one linked in the #vulcan channel header on Slack, which I believe is the one I linked above.

**Review by jyee27 — APPROVED** [review]
CR ☕ through 55aba14492a34c48296f44f0f8e1fc935726c223

**Comment by deltuh-vee** [comment]
QA 🎬 
Author and update info now match the mockup.

**Pull request merged**
