### PR TITLE
Integrate Piwik Pro

### PR DESCRIPTION
**Pull request by danielcliu-ifixit**
## Overview

We want to try out Piwik Pro, so lets load it onto every page. Piwik Pro by default saves stuff into `window._paq`, but our code for matomo already handles this being instantiated so it should work fine.

## QA

Make sure that all pages have Piwik Pro and are sending events fine. Make sure that your `NEXT_PUBLIC_PIWIK_ENV` is set to your desired environment (dev for development, prod for production, anything else for none);

Closes: #1990

### CODE REVIEW

**Review by jarstelfox — DISMISSED** [review]
CR 🌵

**Review by jarstelfox — DISMISSED** [review]
CR 🌵 I noticed this, but I don't think it matters too much across the repos. The variable is local to a page load. Fair enough to keep the same just in case

**Comment by erinemay** [comment]
>Make sure that all pages have Piwik Pro and are sending events fine. 

Where are events sent? Is there a UI we can check? 

>Make sure that your NEXT_PUBLIC_PIWIK_ID is set correctly (the pull should set it correctly though).

Is this a vercel setting?

<details><summary>In my console, I see</summary>

In head, I see: 

```
<script type="text/javascript" async="" defer="" src="https://ifixit.containers.piwik.pro/ppms.js"></script>
<script async="" src="https://ifixit.containers.piwik.pro/6bf6bc54-82ca-4321-8620-b12d5c9b57b6.js?data_layer_name=pproDataLayer"></script>
<script id="ppas_container_configuration" data-appid="6bf6bc54-82ca-4321-8620-b12d5c9b57b6" data-host="ifixit.piwik.pro"></script>
<script type="text/javascript" async="" src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/732989102/?random=1695931606440&amp;cv=11&amp;fst=1695931606440&amp;bg=ffffff&amp;guid=ON&amp;async=1&amp;gtm=45He39r0&amp;u_w=1920&amp;u_h=1080&amp;url=https%3A%2F%2Freact-commerce-git-integrate-piwik-pro-ifixit.vercel.app%2FTroubleshooting%2FiPhone_X%2FWon't%2BTurn%2BOn%2F405163&amp;hn=www.googleadservices.com&amp;frm=0&amp;tiba=iPhone%20X%20Won't%20Turn%20On%20-%20iFixit%20Troubleshooting&amp;auid=1926970084.1695931606&amp;fledge=1&amp;uaa=x86&amp;uab=64&amp;uafvl=Google%2520Chrome%3B117.0.5938.92%7CNot%253BA%253DBrand%3B8.0.0.0%7CChromium%3B117.0.5938.92&amp;uamb=0&amp;uap=Windows&amp;uapv=10.0.0&amp;uaw=0&amp;rfmt=3&amp;fmt=4"></script>

```

And in the body, I see:

```
<script id="piwik-pro" data-nscript="afterInteractive">
         (function(window, document, dataLayerName, id) {
            window[dataLayerName] = window[dataLayerName] || [];
            window[dataLayerName].push({
                  start: (new Date).getTime(),
                  event: "stg.start"
            });

            var scripts = document.getElementsByTagName('script')[0],
                  tags = document.createElement('script');

            function stgCreateCookie(a, b, c) {
                  var d = "";
                  if (c) {
                     var e = new Date;
                     e.setTime(e.getTime() + 24 * c * 60 * 60 * 1e3);
                     d = "; expires=" + e.toUTCString();
                     f = "; SameSite=Strict";
                  }
                  document.cookie = a + "=" + b + d + f + "; path=/";
            }

            var isStgDebug = (window.location.href.match("stg_debug") || document.cookie.match("stg_debug")) && !window.location.href.match("stg_disable_debug");
            stgCreateCookie("stg_debug", isStgDebug ? 1 : "", isStgDebug ? 14 : -1);

            var qP = [];
            dataLayerName !== "dataLayer" && qP.push("data_layer_name=" + dataLayerName);
            isStgDebug && qP.push("stg_debug");

            var qPString = qP.length > 0 ? ("?" + qP.join("&")) : "";

            tags.async = !0;
            tags.src = "https://ifixit.containers.piwik.pro/" + id + ".js" + qPString;
            scripts.parentNode.insertBefore(tags, scripts);

            !function(a, n, i) {
                  a[n] = a[n] || {};
                  for (var c = 0; c < i.length; c++) 
                     !function(i) {
                        a[n][i] = a[n][i] || {};
                        a[n][i].api = a[n][i].api || function() {
                              var a = [].slice.call(arguments, 0);
                              "string" == typeof a[0] && window[dataLayerName].push({
                                 event: n + "." + i + ":" + a[0],
                                 parameters: [].slice.call(arguments, 1)
                              });
                        };
                     }(i[c]);
            }(window, "ppms", ["tm", "cm"]);
         })(window, document, 'pproDataLayer', '6bf6bc54-82ca-4321-8620-b12d5c9b57b6');
      </script>
```

```
<script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(['setTrackingSource', 'jstc_tm']);
    _paq.push(['enableLinkTracking']);
    _paq.push(['setIpTracking', true]);
    _paq.push(['setDomains', ['www.ifixit.com/', 'store.ifixit.de/', 'store.ifixit.fr/', 'store.ifixit.co.uk/', 'store.ifixit.eu/', 'store.ifixit.com/', 'help.ifixit.com/', 'about.ifixit.com/', 'meta.ifixit.com/', 'edu.ifixit.com/', 'ifixit.com/', 'australia.ifixit.com/', 'canada.ifixit.com/', 'de.ifixit.com/', 'en.ifixit.com/', 'es.ifixit.com/', 'fr.ifixit.com/', 'it.ifixit.com/', 'nl.ifixit.com/', 'pt.ifixit.com/', 'ru.ifixit.com/', 'tr.ifixit.com/', 'zh.ifixit.com/', 'jp.ifixit.com/', 'ko.ifixit.com/']]);
    _paq.push(['setCookieDomain', '*.ifixit.com']);
    _paq.push(['enableHeartBeatTimer']);
    _paq.push(['trackPageView']);
    _paq.push(['trackVisibleContentImpressions']);
    _paq.push(['enableCrossDomainLinking']);
    _paq.push(['enableJSErrorTracking']);
    (function(p,i,w,ik) {
        var g=ik.createElement('script'),s=ik.getElementsByTagName('script')[0];
        _paq.push(['setTrackerUrl', p]);
        _paq.push(['setSiteId', w]);
        g.type='text/javascript';g.async=true;g.defer=true;g.src=i;s.parentNode.insertBefore(g,s);
    })('https://ifixit.piwik.pro/ppms.php','https://ifixit.containers.piwik.pro/ppms.js','6bf6bc54\u002D82ca\u002D4321\u002D8620\u002Db12d5c9b57b6',document)
</script>

```


</details>


<details><summary>I also see several post requests that look like this</summary>

image
image

</details>


Do these elements and requests look correct?

**Comment by erinemay** [comment]
Talked to @jarstelfox and what we want to confirm here is: Is Piwik on the page, and is it trying to send info to Piwik.

QA 👍

**Review by jarstelfox — APPROVED** [review]
CR 🌵 FYI the failing tests are due to an outage at docker: https://www.dockerstatus.com/

**Comment by danielcliu-ifixit** [comment]
QA :v: made sure that "none" "dev" and "prod" all work as expected as `NEXT_PUBLIC_PIWIK_ENV` values.

**Review by jarstelfox — APPROVED** [review]

**Pull request merged**
