### PR TITLE
Vulcan: Add action menu and history link

### PR DESCRIPTION
**Pull request by andyg0808**
This adds a dropdown menu to the Vulcan navbar and populates it with a link to the wiki history for the current wiki.

Blocked on #1378 going out.

## QA Notes
Please check that the history link does what we'd want, and that the dropdown looks like the [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=9319%3A156393).

Closes iFixit/ifixit#46560

### CODE REVIEW

**Comment by andyg0808** [comment]
deploy_block :+1: on https://github.com/iFixit/react-commerce/pull/1378 going out.

**Comment by andyg0808** [comment]
un_deploy_block :+1:
#1378 went out.

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I think we want the dropdown to turn blue when active? From the mockup:
image

Also disable the underlining and just have the shading to denote hover over selection.
image

**Comment by andyg0808** [comment]
un_dev_blocked :+1: 
Should be fixed in [01219de](https://github.com/iFixit/react-commerce/pull/1379/commits/01219de8c47f8668eef24ada5bc23ab5cfd71d2c) and [30fec21](https://github.com/iFixit/react-commerce/pull/1379/commits/30fec218666710cda7b7e32d3342cdbf6c79f8a2).

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by deltuh-vee** [comment]
QA 🎬
* History links works and the dropdown/link matches the mockup.

**Comment by deltuh-vee** [comment]
Carry Over QA 🎬

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Pull request merged**
