### PR TITLE
Add OEM badge

### LINKED ISSUE #797: Add OEM badge on Product page
https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=4849%3A48376

### PR DESCRIPTION
**Pull request by federicobadini**
connects #797 

Screenshot 2022-10-27 at 16 33 11

### QA

1. Visit Vercel preview
2. Try modifying the OEM Partnership JSON metafield value associated with the product to verify that the banner is working as expected in all scenarios

### CODE REVIEW

**Comment by davidrans** [comment]
deploy_block :hand: on checking that we have permission to display all these logos

**Comment by danielbeardsley** [comment]
Probably know this... but we already have these logos on our home page:
image

**Comment by shead2** [comment]
I think we can add the logo for everybody except Google. They are the only one who asked us to not do it until they get internal approval to do it. Logitech doesn’t have any OEM products yet

**Comment by danielbeardsley** [comment]
I'll update it.

**Comment by danielbeardsley** [comment]
un_dev_block :+1:

**Comment by danielbeardsley** [comment]
un_deploy_block :+1: 

Hid the Google logo.

**Comment by sterlinghirsh** [comment]
dev_block :zap: doesn't look good with a missing image. 
image
https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/google-pixel-3a-xl-replacement-battery-genuine

Also I don't see it at all on a genuine samsung part but it might be a data issue. https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/samsung-galaxy-s20-plus-usa-back-glass-genuine

**Comment by federicobadini** [comment]
I've completely hidden the banner since the alternative discussed yesterday was removing the metafield for brands that were not yet ready to show their associated logo.
If something has changed and you wanna keep the text-only banner please let me know

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Comment by sterlinghirsh** [comment]
Yeah let's get a design that works with a text-only banner. This can be in a second pull. un_dev_block :zap:

**Comment by sterlinghirsh** [comment]
Also tests are failing

**Comment by danielbeardsley** [comment]
> Also tests are failing

Did you re-run one of them? Looks like it's passing here:
image

**Comment by davidrans** [comment]
Yeah, I re-ran tests and they passed

**Comment by erinemay** [comment]
Basically qa, but got some questions. OEM partnerships logic works and the boxes looks good:
- When the oem_partnerships json metafield is populated appropriately, the OEM badge appears on the product page except for Google. (I spoofed the data for Logitech because it looks like we don't have that info yet. Without the json field, before I spoofed it, the box didn't appear). So, effectively, this merge will make OEM badges live for all of the above but Logitech and Google. 
- Looks good on desktop and mobile
- Did a cross browser/device check (Windows + Chrome, Windows + FF, MacOS + Safari, iOS + Safari, Android + Chrome) and confirmed all the colors/appearance come out the same. 

<details><summary>Design question/nitpick 1️⃣: Is there any way around the visible excess space in the box when we wrap text, or the text is short?</summary>
Suuuper minor, but when the text is short or wraps, there's a bunch of excess space in the container. 

Looks like the box was accidentally made too far left aligned:
image

IMO a nice looking one where the text fits well in the box.
image

</details>

<details><summary>Design question/nitpick 2️⃣: Could we unify border radius values in and around the buy box?</summary>

The OOS box vs the OEM badge on [this page](https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/motorola-moto-x-2nd-gen-replacement-battery) ⬇️ 
image

The Pro only box vs the OEM badge on [this page](https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/surface-display-debonding-tool-m1214770-001) ⬇️ 
image

The add to cart button vs the OEM badge on [this page](https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/samsung-galaxy-s20-ultra-usa-usb-c-charge-port-genuine) ⬇️ 
image


</details>

<details><summary>Quick double check 3️⃣: I'm 95% positive this is just a data issue, but could you confirm?</summary>

We're missing many footer and header elements as well as collections on /Parts. 
I see the [individual menu items](https://add-oem-badge-on-product-page.govinor.com/admin/content-manager/collectionType/api::menu.menu?page=1&pageSize=10&sort=title:ASC&plugins[i18n][locale]=en) aren't populated like on main, but I can't account for the lack of product lists on /Parts

image
image

</details>

deploy_block 🦕 on a stakeholder checking these out and giving 👍 or 👎... @shead2, do you wanna take a quick look at these links ⬇️ and just confirm this is looking how you would expect? 

⚠️ There are a few things on this page that have already been fixed, like the off-centered low stock count and the old value prop favicons. These are just here because the branch is out of date. 

<details><summary>Sample links for every partnership</summary>
🚫 = OEM partnership box is absent on product pages. Google because we don't want it until the logo is ok'd. Logitech because we don't have that info, or aren't selling genuine parts yet.

- 🚫 Google Pixel: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/google-pixel-3a-xl-replacement-battery-genuine
- HTC Vive: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/htc-vive-tracker-dongle-3-0
- Lenovo: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/lenovo-chromebook-n23-palmrest-keyboard
- 🚫 Logitech: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/logitech-ue-boom-replacement-battery
- Microsoft Surface: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/microsoft-surface-rt-1st-gen-kickstand
- Microsoft Surface Tool: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/surface-display-debonding-tool-m1214770-001
- Motorola: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/motorola-moto-x-2nd-gen-replacement-battery
- Samsung Galaxy: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/samsung-galaxy-s20-ultra-usa-usb-c-charge-port-genuine
- Steam Deck: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/steam-deck-right-trigger-button-assembly
- Teenage Engineering: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/op-z-rubber-feet
- Valve: https://react-commerce-git-add-oem-badge-on-product-page-ifixit.vercel.app/products/valve-index-right-controller-strap-adjustment-and-elastic-band

</details>


double deploy_block :ANOTHER:  to remember to re-save products if we haven't since https://github.com/iFixit/ifixit/pull/45289 was merged.

**Comment by erinemay** [comment]
Some notes from @kwiens and @shead2. 

It looks like products have already been saved to the prod Shopify store since we [added this metafield](https://github.com/iFixit/ifixit/pull/45208), so deploy_block 🛑 the whole thing until we get the data right and re-save. 

I believe all this lives in Akeneo. cc: @jeffsnyder 

## Big picture
Can't turn on the following:
- Google (already off) ✔️ 
- Logitech (not programmatically off, but we don't even have these products yet) ✔️ 

## Details
1. Change capitalization and add a period to all the copy. Only the product name should be capitalized.
Example: "This is a Genuine HTC Vive Part" should be "This is a genuine HTC Vive part."

2. Unify Steam Deck and Valve. They should both use the Valve image and have the same copy. Drop the "index" in the Valve text, so both Valve and Steam Deck badges read: "This is a genuine Valve part."

3. It looks like only some of these have links associated with them. It sounds like there's already been conversation around adding links if we don't have a landing page. cc: @jeffsnyder

**Comment by danielbeardsley** [comment]
1. I'm fixing this in JS, because the values are from Akeneo and are used in several other places where changing the capitalization might look worse.

2. Unification of Steam/Valve. Does this apply across the board wherever we mention this partnership? i.e. should we just combine the values in akeneo which has them separated. Or should this unification *only* apply to this one UI component.
image

3. Links. We had a previous issue. @jeffsnyder gave us a spreadsheet and we put those links into code. See: https://github.com/iFixit/ifixit/pull/45289

@kwiens, @ifixitmaxb, or @shead2 clarity on number 2 is needed.

**Comment by danielbeardsley** [comment]
Regarding the text-wrapping, it appears we render the text and the link in separate lines (text is in a `<p>`) We could put them together and then force `Lean more` to not break on it's space... but I think we'd get nearly the same result.

I've also fixed the border radius inconsistency. Good catch!

**Comment by ifixitmaxb** [comment]
I'm sorry but I don't understand the implications to traffic/SEO here so I'm not sure what to offer. Danny asked for clarity and I don't know how to help. Would merging eliminate the number of product pages? Would URLs change? What would change that would impact SEO? @danielbeardsley

**Comment by danielbeardsley** [comment]
> . Would merging eliminate the number of product pages? Would URLs change? What would change that would impact SEO

Sorry, none of that. I think I was mentally saying "Chris Parkhurst" but I typed your handle. I'll ping him.

**Comment by danielbeardsley** [comment]
I think we should merge this as it gets the badge there. Unifying Steam/Valve partnerships will likely happen in a different code base and no changes would be needed here.

Thoughts @erinemay ?

**Comment by erinemay** [comment]
> Regarding the text-wrapping, it appears we render the text and the link in separate lines (text is in a `<p>`) We could put them together and then force `Lean more` to not break on it's space... but I think we'd get nearly the same result.

I don't think we should un-wrap the learn more link. It was a stretch nitpick, and I was looking for other input or a brilliant design solution that I didn't know about. I think it's fine to ship without any change there.

Border radii look good now ✔️ 
Sentences look good ✔️ 
image

QA 👍 that all these are fixed. They look good now.

deploy_block ❔ tbh, I didn't get a good idea if the valve/steam deck was a blocker for @kwiens.
(The Steam Deck image looks like an image placeholder, and I think Valve unification would be a big improvement.)

also test failures?

**Comment by danielbeardsley** [comment]
CR :+1:

**Comment by kwiens** [comment]
un_deploy_block 👍  Perfectly fine as is, slightly better if Valve and Steam are unified.

**Comment by erinemay** [comment]
un_dev_block 👍

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Comment by danielbeardsley** [comment]
> slightly better if Valve and Steam are unified.

I'm guess this would apply everywhere we call out these partnerships. If that's the case, does it make sense to just represent them that way in Akeneo? (setting `oem_partnership` to `valve` for both sets of products) Or is that attribute used for more than just display? @shead2 

FYI, if they should be combined, then this is jut a data-task in Akeneo.

**Pull request merged**
