### PR TITLE
Bump strapi to `4.4.7`

### LINKED ISSUE #1013: Strapi: Try out new version
We found [a bug in the existing version of strapi](https://github.com/strapi/strapi/issues/13731#issuecomment-1304319866) that caused us downtime. The devs have recommended we try updating to the newest version

Do This
###

* Open a pull to upgrade strapi
* Try out the migration process in dev
   * Talk to Danny about booting another dev strapi and snapshotting the RDS beforehand

### PR DESCRIPTION
**Pull request by masonmcelvain**
In an effort to patch a bug: https://github.com/strapi/strapi/issues/13731#issuecomment-1304322026

### [Migration guides](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html)

- [v4.3.6 to v4.3.8 migration guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.3.6-to-4.3.8.html) (unnecessary, our app already had the change)
- [v4.4.3 to v4.4.5 migration guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.3-to-4.4.5.html)

CC @danielbeardsley 

Closes #1013

### CODE REVIEW

**Comment by masonmcelvain** [comment]
Strapi builds and runs fine locally. I'll sync up with @danielbeardsley to figure out why https://bump-strapi.govinor.com/ is down

**Comment by masonmcelvain** [comment]
dev_block ✌🏻

**Comment by federicobadini** [comment]
Do you have any updates to share here? 
I'm asking because #1157 and #1158 are in draft in order to understand if the newer versions of Strapi solve the `required: true` issue that caused #989.

If not, those two PR will add the boolean without the `required: true`.

**Comment by masonmcelvain** [comment]
I don't have anything new to share, we put that PR on ice in favor of some more pressing issues. I apologize if this blocks your work or complicates it, I will reprioritize it on our sprint.

**Comment by masonmcelvain** [comment]
un_dev_block ✌🏻

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Comment by masonmcelvain** [comment]
QA ✌🏻 

The admin dashboard loads, and collection and product pages work.

**Comment by danielbeardsley** [comment]
Woo hoo!

This took Mason and I a few hours of chasing our tails to get to the bottom of; To save others time I'll explain the problem we had.

When doing `yarn install` inside `/backend`, it was utilizing the `.npmrc` file from the project root. This resulted in it replacing npm urls with `npm.fontawesome.com` for all `@fortawesome` packages (even though strapi only uses the free icon set). We didn't notice the change to the `resolved` property on the fontawesome dependency in the yarn.lock file (among the other thousand lines of changes). This resulted in not being able to build the docker image without the fontawesome auth token in the environment.

**Comment by masonmcelvain** [comment]
deploy_block ✌🏻 on qaing the deploy

**Comment by masonmcelvain** [comment]
un_deploy_block ✌🏻

**Comment by masonmcelvain** [comment]
@danielbeardsley and I successfully rotated in a new strapi machine, we officially on 4.4.7!

**Comment by federicobadini** [comment]
Great! Have you already tested out if this new version handles better the default values?
If not I'll do a couple of tests tomorrow

**Comment by masonmcelvain** [comment]
We didn't test that yet. If you have time to do so, that would be great!

**Pull request merged**
