### PR TITLE
Readd menu3 to strapi

### PR DESCRIPTION
**Pull request by aburke07**
I'm not sure how this was removed in the last few days, but we still need this for #1342 to pass CI.

After this deploys, I think we need to redeploy strapi again.

Qa_req 0

### CODE REVIEW

**Review by hcutrone — COMMENTED** [review]
CR :burrito: but deploy_block :burrito: - should we figure out why this was removed? Will it happen again?

**Comment by aburke07** [comment]
> should we figure out why this was removed? Will it happen again?

@danielbeardsley Found it here: https://github.com/iFixit/react-commerce/pull/1448#discussion_r1131383164

It was just accidentally removed.

Un_deploy_block :alien:

**Comment by masonmcelvain** [comment]
Doesn't this cause a diff every time you run a dev server? deploy_block ✌🏻

**Comment by aburke07** [comment]
> Doesn't this cause a diff every time you run a dev server? deploy_block ✌🏻

The diff I'm getting is adding back this menu3 type. Wouldn't adding this to main remove the diff? I'm not sure why this is adding a diff in the first place either.

**Comment by aburke07** [comment]
> I added to #1342 where we query for it, so lets see if that passes CI. If so, we can close this pull.

Vercel deployed successfully there, so adding menu3 on that pull seems like the way to go.

**Comment by danielbeardsley** [comment]
> The diff I'm getting is adding back this menu3 type. 

The SDK is built off whatever is in your strapi DB, is it not? Strapi itself will I think adjust it's database (does it remove columns too??) to whatever is defined in the schema files in the backend each time it's booted.

**Comment by masonmcelvain** [comment]
> Hmm, I thought the strapi type needed to be updated before we query for it?

Ah, I meant that we needed to add the field to strapi in `backend/`, which you did in #1444 in `backend/src/components/store/footer.json`. The types in `frontend/lib/strapi-sdk/generated/sdk.ts` get autogenerated based on what we're querying for in `frontend/lib/strapi-sdk/operations` I think. So, when we start querying for `menu3` in `findStore.graphql`, that's when we'd expect the type of `menu3` to be added to the generated type schema.

**Comment by masonmcelvain** [comment]
This [file](https://github.com/iFixit/react-commerce/blob/main/frontend/codegen.yml) controls the schema generation, for reference

**Pull request closed without merging**
