### PR TITLE
Troubleshooting: Fix text encoding on `RelatedProblems` card

### PR DESCRIPTION
**Pull request by jyee27**
Use `Prerendered` to properly render HTML encoded text such as `&quot;`.

QA
--
Check that text renders properly for the device card:

<details>
<summary>Image</summary>

image

</details>

Example troubleshooting page: https://me.cominor.com/Troubleshooting/iPhone_11/Will+Not+Turn+On/478192

Closes: https://github.com/iFixit/ifixit/issues/50287

### CODE REVIEW

**Review by ianrohde — DISMISSED** [review]
CR ⚪

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by aburke07** [comment]
Do we also need to wrap the device title?

**Comment by kthaler** [comment]
QA 🔷  -  Used the string `& < > " '` and confirmed that text renders properly for the device card.

deploy_block 🦖  - Looks like the summary text was shifted down in this branch. Example:
Screenshot 2023-10-18 at 5 31 16 PM

Reference: 
Screenshot 2023-10-18 at 5 31 50 PM

**Comment by jyee27** [comment]
> deploy_block 🦖 - Looks like the summary text was shifted down in this branch. 

What browser/OS are you on? This is what it looks like for me on Windows:

<details>
<summary>Master</summary>


image


</details>

<details>
<summary>Branch</summary>

image


</details>

**Comment by ianrohde** [comment]
@jyee27 I have a pull open to address the `prerendered` margins here https://github.com/iFixit/react-commerce/pull/2037.

**Comment by jyee27** [comment]
deploy_block ☕ on https://github.com/iFixit/react-commerce/pull/2037, which will affect `prerendered` margins

**Comment by jyee27** [comment]
un_deploy_block ☕

**Review by ianrohde — DISMISSED** [review]
CR ⚪

**Comment by jordycosta** [comment]
QA 🟢 

The text encoding issue is resolved on the **RelatedProblems** card 👍 

firefox_o2Ektx6BX4

**Comment by ianrohde** [comment]
Head's up on https://github.com/iFixit/react-commerce/pull/2042/files#diff-6ee89f2292a5e40be6686c92372cc0dbe1f2b29af769f28390b2a61061fe1008R975-R980

**Comment by sctice-ifixit** [comment]
> Used the string `& < > " '` and confirmed that text renders properly for the device card.

@kthaler When testing special characters like this, please make sure you _also_ test that they're properly encoded. That is, they shouldn't literally be `& < >` in the markup; they should be encoded as something like `&amp; &lt; &gt;`.

**Comment by jyee27** [comment]
deploy_block ☕ on https://github.com/iFixit/react-commerce/pull/2042

**Comment by erinemay** [comment]
>When testing special characters like this, please make sure you _also_ test that they're properly encoded. That is, they shouldn't literally be `& < >` in the markup; they should be encoded as something like `&amp; &lt; &gt;`.

image

Is this what you mean?

**Comment by sctice-ifixit** [comment]
> Is this what you mean?

The dev tools are going to show you the text as it would render, not the raw HTML. If you right-click on that node and select "Edit as HTML", you should be able to see the actual HTML. Here's an example of the difference between the two:

| Rendered                                                                                                | HTML                                                                                                    |
| ------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
| image | image |

**Comment by erinemay** [comment]
> The dev tools are going to show you the text as it would render, not the raw HTML. If you right-click on that node and select "Edit as HTML", you should be able to see the actual HTML. Here's an example of the difference between the two:

Thank you!! TIL

image

`<>&` are all still encoded. The double quote (straight or curly) isn't, though.

**Comment by jyee27** [comment]
un_deploy_block ☕ 

It looks like there's an issue with the `display={{ base: 'none', xl: '-webkit-box' }}` property not hiding the description when the card moves below `xl`, but this is also present on `main`.

<details>
<summary>Image</summary>

image


</details>

**Comment by ianrohde** [comment]
> It looks like there's an issue with the display={{ base: 'none', xl: '-webkit-box' }} property not hiding the description when the card moves below xl, but this is also present on main.

I'll patch this in another PR.

**Review by ianrohde — DISMISSED** [review]
CR ⚪

**Comment by kthaler** [comment]
deploy_block 🦖  - on @erinemay 's comment https://github.com/iFixit/react-commerce/pull/2039#issuecomment-1773197301

**Comment by ianrohde** [comment]
> `<>&` are all still encoded. The double quote (straight or curly) isn't, though.

@erinemay were you using `&quot;` to test double quotes?

https://developer.mozilla.org/en-US/docs/Glossary/Entity

**Comment by sctice-ifixit** [comment]
> deploy_block 🦖 - on @erinemay 's comment [#2039 (comment)](https://github.com/iFixit/react-commerce/pull/2039#issuecomment-1773197301)

un_deploy_block :flags: This struck me as strange, as I'm pretty sure we would encode a double quote (not a single quote). Checking on a device page, where I can look directly at the source, we _do_ encode double quotes, but Chrome's "Edit as HTML" still shows it as `"`. Bummer. The only way I can think of to check is to edit the source to log the string in the prerendered component that we pass to `dangerouslySetInnerHTML()`. In any case, given that the other characters are encoding as expected, I think this is okay.

**Comment by deltuh-vee** [comment]
dev_block ✊ on merge conflicts

**Comment by ianrohde** [comment]
un_dev_block 🟢 fixed in [`24e6ed0`](https://github.com/iFixit/react-commerce/pull/2039/commits/24e6ed03bcf81b4845fa434e1a63f78a511dd215)

**Review by ianrohde — DISMISSED** [review]
CR ⚪

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by jordycosta** [comment]
QA 🟢 Keeping in mind https://github.com/iFixit/react-commerce/pull/2039#issuecomment-1773476796

The encoding issue appears to be resolved on the **RelatedProblems** card

**Pull request merged**
