### PR TITLE
Add Strapi product list redirect fields

### PR DESCRIPTION
**Pull request by masonmcelvain**
Connects https://github.com/iFixit/react-commerce/issues/2067

The intent is to grab `redirectTo` at request time (cached with Redis) and issue a redirect if appropriate.

`redirectFrom` isn't necessary for the Next.js app, but offers a convenient way for Strapi admin users to create redirects from a source to a target from the source product list page. (e.g. If I am on product list A and want to cause product list B to redirect to product list A, I can do so without visiting product list B in Strapi admin).

https://docs.strapi.io/dev-docs/backend-customization/models#relations

qa_req 0

### CODE REVIEW

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by danielbeardsley** [comment]
> e.g. If I am on product list A and want to cause product list B to redirect to product list A, I can do so without visiting product list B in Strapi admin

I feel like this is complexity that isn't really needed. We have to add another query to the graphQL query and it allows there to be two places where the same data is stored and thus there can be conflicts:

    X.redirectFrom = Y 
    Y.redirectTo = Z

Where do we go when visiting Y?

**Comment by masonmcelvain** [comment]
> I feel like this is complexity that isn't really needed

You're right, it's not necessary, but it could be nice to see which product lists redirect to the one you're looking at. It is also a visual cue to help Strapi admin users prevent redirect chains.

> there can be conflicts

I don't think Strapi allows there to be conflicts. When you add a `redirectFrom` via the UI, the `redirectTo` is automatically set on the other product list, even if `redirectTo` is already set to something. Try it yourself: https://main.govinor.com/admin/content-manager/collectionType/api::product-list.product-list?page=1&pageSize=100&sort=title:ASC&plugins[i18n][locale]=en

We do not have to query for `redirectFrom` in Next.js, and I do not in the implementation here https://github.com/iFixit/react-commerce/pull/2166.

**Comment by danielbeardsley** [comment]
> I don't think Strapi allows there to be conflicts.

Oh! I didn't understand the `"inversedBy": "redirectFrom"` before. I assumed this was two separate relationships, but instead it's more like giving a name to the other side of the relationship for easier reference / visibility. Nice!

Thanks for explaining!

**Pull request merged**
