### PR TITLE
Align product list sections with product/pages section conventions

### PR DESCRIPTION
**Pull request by dhmacs**
closes https://github.com/iFixit/ifixit/issues/48437

## Changelog

- Refactor graphql queries, mostly to align naming conventions and reuse fragments
- Refactor of product list model to adapt to other models conventions about sections
- There are currently 2 lifetime warranty banner implementations. With this PR I'm converging their model schema. We might merge them into a single reusable component, but I've left this for another PR
- Moved around some product list enums to avoid increasing bundle size (this actually ended up decreasing the bundle size)

## QA

This is a refactor of the product list model that is mostly affecting product list sections. Let's do a quick smoke test to verify that product list pages still work as intended.

### CODE REVIEW

**Comment by deltuh-vee** [comment]
dev_block ✊ on merge conflicts.

**Comment by dhmacs** [comment]
un_dev_block 🟢 

cc @deltuh-vee

**Comment by deltuh-vee** [comment]
QA 🎬 
Product list pages still look good.

**Comment by dhmacs** [comment]
@deltuh-vee I've merged the conflicts again

**Comment by deltuh-vee** [comment]
Carry Over QA 🎬

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 Everything seemed reasonable to me. Thanks for cleaning this up!

**Pull request merged**
