### PR TITLE
Strapi: Deploy with actions

### PR DESCRIPTION
**Pull request by mlahargou**
We previously used cimpler to deploy strapi. We are trying to remove all
instances of cimpler, and this is the last one. This creates a copy of the
strapi-deploy script that cimpler uses. It's slightly modified because some
of the checks it did can be more easily expressed in the workflow file.

CR:
--
I think we eventually will want to transform the bash script into actual
workflow steps, but for now a copy of the existing/working bash script
should be enough.

QA:
--
Idk how we want to test this. Might have to just test this on deploy.

On Deploy:
--
Deactivate the webhook that sends the push event to ubreakit. Deploy
and verify that all went well.

Closes: https://github.com/iFixit/react-commerce/issues/2175

qa_req 0
QA on deployment

### CODE REVIEW

**Comment by mlahargou** [comment]
deploy_block 📱 on the runner being created.

**Comment by jordycosta** [comment]
I will mark this as qa_req 0 for now, feel free to remove that if it needs to be tested before deployment

**Comment by mlahargou** [comment]
Runner is created. Keeping deploy_blocked b/c I need to be careful when deploying this.

**Review by batbattur — APPROVED** [review]
CR 🚛 

Since the deploy logs will be public, is there anything we should check?

Looks like this was the latest strapi deploy: [logs](https://www.ubreakit.com/Misc/cimpler-logs/strapi-deploy/main--5d7c686e03eaa54daff017929ae1ac553e77e04d--1704307511490.log). I don't see anything sensitive but just wanted to make sure.

**Comment by ardelato** [comment]
Heads up, I just found this line of related code in `server-templates` that we should drop once this goes out.
https://github.com/iFixit/server-templates/blob/master/terraform/iam/github/actions_assume_role.tf#L7

**Review by danielbeardsley — APPROVED** [review]
Looks good!

After this goes out, we can drop the IAM permissions stuff from server-templates.

CR :+1:

**Pull request merged**
