### PR TITLE
Next: Upgrade to v14

### PR DESCRIPTION
**Pull request by jarstelfox**
NextJS 14 does not have any breaking changes. It should be safe to upgrade!

See:

https://nextjs.org/docs/pages/building-your-application/upgrading/version-14

https://dev.to/mongodb/nextjs-14-no-new-apis-breaking-changes-3nh3

QA
---

* Run `nvm use`
	* It may instruct you to run `nvm install`
	* Then run `nvm use` to ensure you are on node 18.17.0
* Run `npm install -g pnpm@8`
* Run `npm install -g yarn`
* Run `pnpm dev`
* Smoke test site.

Note: I expect no issues as the claim is nothing is breaking, but I'd like to check before merging.

Connects: https://github.com/iFixit/ifixit/issues/50776

### CODE REVIEW

**Comment by jarstelfox** [comment]
dev_block 🌵 I think we should tackle the terser issue another way if we believe the issue still affects us

**Review by andyg0808 — APPROVED** [review]
CR :+1: 

Looks reasonable to me, and if the SWC build passes tests and basic manual QA, I have very little fear of it.

**Comment by kthaler** [comment]
dev_block 🦖 - I've encountered a couple errors:

I'm getting this error when attempting to view [this Troubleshooting page](http://localhost:3000/Troubleshooting/Whirlpool_Refrigerator/Door+Not+Closing/509237):

Screenshot 2023-11-27 at 3 40 24 PM

<details>
<summary>The error in the terminal</summary>
<br>

```
> [dev:frontend] [Next] - wait compiling /_error (client and server)...
> [dev:frontend] [Next] - error ../packages/feature_flags/index.ts:4:0
> [dev:frontend] [Next] Module not found: Can't resolve '@ifixit/local-storage'
> [dev:frontend] [Next]   2 | import type { FlagList as FormalFlagList } from './flag_schema';
> [dev:frontend] [Next]   3 | 
> [dev:frontend] [Next] > 4 | import { useSafeLocalStorage } from '@ifixit/local-storage';
> [dev:frontend] [Next]   5 | 
> [dev:frontend] [Next]   6 | export const flags: FormalFlagList = raw_flags;
> [dev:frontend] [Next]   7 | export type FlagKey = keyof typeof raw_flags;
> [dev:frontend] [Next] 
> [dev:frontend] [Next] https://nextjs.org/docs/messages/module-not-found
> [dev:frontend] [Next] 
> [dev:frontend] [Next] Import trace for requested module:
> [dev:frontend] [Next] ../packages/react-feature-flags/index.ts
> [dev:frontend] [Next] ./templates/troubleshooting/index.tsx
> [dev:frontend] [Next] ./pages/Troubleshooting/[device]/[problem]/[wikiid].tsx
```

</details>

I'm getting this error when trying to view [the Playstation 4 page](http://localhost:3000/Parts/PlayStation_4):

Screenshot 2023-11-27 at 3 44 37 PM

<details>
<summary>The entire error</summary>
<br>
[dev:frontend] [Next] - wait compiling /_error (client and server)...
[dev:frontend] [Next] - error ../node_modules/.pnpm/next@13.4.12_@babel+core@7.17.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/image-loader.js (41:26) @ defaultLoader
[dev:frontend] [Next] - error Error: Invalid src prop (https://main.govinor.com/uploads/small_shuttle_3_a282509a77.jpg) on `next/image`, hostname "main.govinor.com" is not configured under images in your `next.config.js`
[dev:frontend] [Next] See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host
[dev:frontend] [Next]     at defaultLoader (webpack-internal:///../node_modules/.pnpm/next@13.4.12_@babel+core@7.17.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/image-loader.js:40:27)
[dev:frontend] [Next]     at /Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/next@13.4.12_@babel+core@7.17.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/get-img-props.js:101:36
[dev:frontend] [Next]     at Array.map (<anonymous>)
[dev:frontend] [Next]     at generateImgAttrs (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/next@13.4.12_@babel+core@7.17.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/get-img-props.js:101:24)
[dev:frontend] [Next]     at getImgProps (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/next@13.4.12_@babel+core@7.17.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/get-img-props.js:387:27)
[dev:frontend] [Next]     at eval (webpack-internal:///../node_modules/.pnpm/next@13.4.12_@babel+core@7.17.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/image-component.js:272:82)
[dev:frontend] [Next]     at renderWithHooks (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
[dev:frontend] [Next]     at renderForwardRef (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5842:18)
[dev:frontend] [Next]     at renderElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
[dev:frontend] [Next]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderIndeterminateComponent (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
[dev:frontend] [Next]     at renderElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
[dev:frontend] [Next]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderNode (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
[dev:frontend] [Next]     at renderHostElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
[dev:frontend] [Next]     at renderElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
[dev:frontend] [Next]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderNode (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
[dev:frontend] [Next]     at renderChildrenArray (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
[dev:frontend] [Next]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
[dev:frontend] [Next]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderIndeterminateComponent (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
[dev:frontend] [Next]     at renderElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
[dev:frontend] [Next]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderForwardRef (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
[dev:frontend] [Next]     at renderElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
[dev:frontend] [Next]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderNode (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
[dev:frontend] [Next]     at renderChildrenArray (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
[dev:frontend]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderNode (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
[dev:frontend] [Next]     at renderHostElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
[dev:frontend] [Next]     at renderElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
[dev:frontend] [Next]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderNode (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
[dev:frontend] [Next]     at renderChildrenArray (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
[dev:frontend] [Next]     at renderNodeDestructive (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
[dev:frontend] [Next]     at renderElement (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
[dev:frontend] [Next]     at renderNodeDestructiveImpl (/Users/karlthaler/Stuff/react-commerce/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11) {
[dev:frontend] [Next]   digest: undefined
[dev:frontend] [Next] }
[dev:frontend] [Next] null

</details>

**Review by andyg0808 — APPROVED** [review]
CR :+1:

**Comment by kthaler** [comment]
> I was not able to repro the troubleshooting error. I suspect some node module cache was out of date

I reran the startup script in this branch and am now able to see the Troubleshooting pages.

I reviewed these pages:

- /Parts
- /product/[product]
- /Store
- /Tools
- /Troubleshooting

I verified that they are all operating correctly without any errors.

QA 💎

**Comment by dhmacs** [comment]
I was doing the same work on this PR, and I remember that one of the issues was the 404 page.

I'm going to deploy_block 🛑 and verify on this branch if it's still relevant

**Comment by jarstelfox** [comment]
I ran this down to: https://github.com/vercel/next.js/issues/58945

As far as I can tell, the Pages router error page works if we drop the App router.

The App router error page works with no issue.

We could either upgrade all routes to the App router or wait for them to patch the 404 bug

**Comment by dhmacs** [comment]
@jarstelfox 

> We could either upgrade all routes to the App router

I was thinking about doing this first and then upgrade 👍

**Pull request closed without merging**
