### PR TITLE
Troubleshooting: Show Related Problems appropriately

### PR DESCRIPTION
**Pull request by andyg0808**
When we have the `extended-related-problems` flag enabled, we have extra
problems potentially included in the `Related Problems` list
(confusingly, these come from the `relatedProblems` key and are added to
the existing `linkedProblems` list). This ensures that we update the
`hasRelatedPages` boolean to accurately reflect the state of the
`Related Problems` section.

## QA Notes
Check that adding `#enable-extended-related-problems` to a troubleshooting page URL results in the extended related-problems section showing up.

### CODE REVIEW

**Comment by andyg0808** [comment]
QA :+1:

**Comment by andyg0808** [comment]
QA :+1:

**Review by hcutrone — APPROVED** [review]
CR 🌯

**Review by danielcliu-ifixit — APPROVED** [review]
CR :v:

**Pull request merged**
