### PR TITLE
Strapi Uploads: persist in s3

### PR DESCRIPTION
**Pull request by danielbeardsley**
Make the S3 bucket configurable via an env variable.

Closes #309

### CODE REVIEW

**Comment by danielbeardsley** [comment]
dev_block :+1: on conditionalizing it for local development

**Comment by danielbeardsley** [comment]
un_dev_block :+1:

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 22f2a8e

**Comment by danielbeardsley** [comment]
It was tricky to get into a position to test this, but it works!

I uploaded a bunny!
image

image

QA :+1:

**Pull request merged**
