### PR TITLE
Add jest tests workflow to github actions 

### PR DESCRIPTION
**Pull request by batbattur**
## Summary

In https://github.com/iFixit/react-commerce/pull/438, we will add jest tests. This pull adds a new workflow to run jest tests using github actions.

## QA Notes
Please re-run the jest action and make sure it passes.

## Merge instructions
Merge after https://github.com/iFixit/react-commerce/pull/438 is deployed.

### CODE REVIEW

**Comment by batbattur** [comment]
deploy_block 👍 Merge after https://github.com/iFixit/react-commerce/pull/438 is deployed.

**Review by mlahargou — APPROVED** [review]
CR 📱 Do we want this to run on all push requests instead of just pull requests?

**Comment by batbattur** [comment]
> Do we want this to run on all push requests instead of just pull requests?

I think it's okay to run on push events because it's free. Also, we don't have to wait for tests to start until the pull request is created. This way, when we create the pull request, the tests will be already running or possibly finished running.

**Comment by jordycosta** [comment]
♻️ Re-running Jest tests / jest

**Comment by jordycosta** [comment]
QA 🟢 

Screenshot 2022-07-15 110351

**Comment by batbattur** [comment]
un_deploy_block 👍 https://github.com/iFixit/react-commerce/pull/438 is merged.

**Pull request merged**
