### PR TITLE
Add featured collection section

### LINKED ISSUE #29: Add "Popular Fix kits" section into parts collection page
Add a section to the Parts collection page that contains popular fix kits as shown below:

Screen Shot 2021-06-23 at 16 18 38

## Todos

- [x] Add graphql codegen config for Shopify storefront
- [x] Add "FeaturedCollection" section component to Strapi collection
- [x] Add storefront credentials to strapi Store model (different regions use different Shopify stores, hence they have different credentials)
- [x] Fetch data from Algolia
- [x] Create featured collection section react component

### PR DESCRIPTION
**Pull request by dhmacs**
This PR closes #29  

## QA

1. Visit the Vercel PR preview
2. Visit the parts collection page
3. Verify that the featured collection section is rendered with content from Strapi

### CODE REVIEW

**Comment by ardelato** [comment]
QA 👍 

## Steps Taken:
1. Went to `strapi.cominor.com`
2. I then went to the `Collections` section and clicked on `Parts` titled collection
3. I then scrolled to the bottom to the `FeaturedCollection` section
FeaturedColleciton
4. I then checked out the Vercel preview and scrolled down to the bottom in the `Parts` page
5. I confirmed a featured section was now rendered and included the item and relevant products for the item
Featured Collection
6. I then switched the `FeaturedCollection` item to `iPhone X` and clicked save
7. I refreshed the Vercel page and confirmed the changes were pushed
Strapi Featured Collection Update

**Comment by ardelato** [comment]
QA 👍 

## Steps Taken:
1. Repeated steps from https://github.com/iFixit/react-commerce/pull/87#issuecomment-925060161
2. Also confirmed with 40e5553 the `Parts` and `Tools` links now had the reference links as part of the anchor tag
Href added

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by masonmcelvain** [comment]
CR ✌🏻

**Pull request merged**
