### PR TITLE
Troubleshooting: Wrap page in standard middleware

### PR DESCRIPTION
**Pull request by andyg0808**
Does what it says on the tin.

qa_req 0
I looked at the page and it still shows up. I'll let the tests confirm everything else.

Closes https://github.com/iFixit/ifixit/issues/48098

### CODE REVIEW

**Comment by sterlinghirsh** [comment]
Fyi middlware has a specific definition in nextjs that might be confusing here.

**Comment by sctice-ifixit** [comment]
> Fyi middlware has a specific definition in nextjs that might be confusing here.

This is borrowing from an [existing pattern](https://github.com/iFixit/react-commerce/blob/f5aaa43d5399631a0802451d763ac752f75cb4e1/frontend/templates/product/server.tsx#L17-L21) [suggested by @danielbeardsley ](https://ifixit.slack.com/archives/CDFNZ4N4A/p1684866915036909?thread_ts=1684799970.160549&cid=CDFNZ4N4A). If we'd like to settle on a less overloaded term, sooner rather than later would probably be a good idea. `withDecorators`?

**Review by danielbeardsley — DISMISSED** [review]
CR :+1:

**Comment by ianrohde** [comment]
Sorry to clutter up history @andyg0808, I tried.

**Comment by ianrohde** [comment]
I'm going to close this and open a new pull with the proposed changes. My bad

**Pull request closed without merging**
