### PR TITLE
packages/ui: Add missing peer dependencies

### PR DESCRIPTION
**Pull request by andyg0808**
We appear to be missing a bunch of required peer dependencies in `@ifixit/ui`. This adds them.

## QA Notes
Would be worth checking that the site still loads after this.

### CODE REVIEW

**Comment by andyg0808** [comment]
I'm not sure what's breaking here; I hadn't anticipated the changes I made to be a problem (especially because they're installing), but I'm wondering if it might be React version incompatibilities.

**Comment by masonmcelvain** [comment]
Just noticed this PR - I'm doing something similar in https://github.com/iFixit/react-commerce/pull/604 but I think we're not overlapping here.

**Comment by masonmcelvain** [comment]
Here's what I see on Vercel, if it's helpful. Looks like the `TypeError` might be the culprit, but it's hard to tell what's causing it.

```
[GET] /Parts
22:00:41:50
Function Status:None
Edge Status:500
Duration:4845.45 ms
Init Duration: N/A
Memory Used:167 MB
ID:sfo1::tf4wn-1660366846444-58d30bc3240c
User Agent:Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0

Cache miss for 'storeList': 35msCache miss for 'globalSettings': 429msstrapi:getProductList: 565msalgolia:create key: 2msCache miss for 'store-us': 624ms2022-08-13T05:00:44.689Z	9c5d9c78-d2e8-40f1-a3f8-09a401287534	ERROR	fetch() HTTP error: 502 Internal Error {  _resource: 'https://www.cominor.com/api/2.0/wikis/topic_images?size=thumbnail&t%5B%5D=Android&t%5B%5D=Kindle+Paperwhite&t%5B%5D=Android+Phone&t%5B%5D=Chromebook&t%5B%5D=Electronics&t%5B%5D=Game+Console&t%5B%5D=GoPro+Camera&t%5B%5D=GoPro&t%5B%5D=iPad&t%5B%5D=iPhone&t%5B%5D=iPod&t%5B%5D=iPod+Touch+5th+Generation+16+GB+2014&t%5B%5D=iPod+Touch+5th+Generation+16+GB&t%5B%5D=Kindle+Tablet&t%5B%5D=Mac&t%5B%5D=PC+Desktop&t%5B%5D=PC+Laptop&t%5B%5D=PowerBook+G3&t%5B%5D=Smartwatch',  headers: undefined,  method: 'GET',  body: undefined}iFixit API GET:wikis/topic_images?size=thumbnail&t%5B%5D=Android&t%5B%5D=Kindle+Pa...: 256msPromise.all: 845msgetServerState: 682msgetServerSideProps: 1528ms2022-08-13T05:00:46.384Z	9c5d9c78-d2e8-40f1-a3f8-09a401287534	ERROR	TypeError: Cannot read properties of undefined (reading 'onToggle')    at useMenuButton (/var/task/frontend/.next/server/chunks/793.js:9166:23)    at Object.render (/var/task/frontend/.next/server/chunks/793.js:9623:21)    at a.b.render (/var/task/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:194)    at a.b.read (/var/task/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)    at Object.exports.renderToString (/var/task/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)    at Object.renderPage (/var/task/node_modules/.pnpm/next@11.1.3_d2d3f5d29d8bc921bbe8ef8bb649cedb/node_modules/next/dist/server/render.js:596:45)    at Function.getInitialProps (/var/task/frontend/.next/server/chunks/75.js:603:19)    at Object.loadGetInitialProps (/var/task/node_modules/.pnpm/next@11.1.3_d2d3f5d29d8bc921bbe8ef8bb649cedb/node_modules/next/dist/shared/lib/utils.js:69:29)    at renderDocument (/var/task/node_modules/.pnpm/next@11.1.3_d2d3f5d29d8bc921bbe8ef8bb649cedb/node_modules/next/dist/server/render.js:609:48)    at Object.renderToHTML (/var/task/node_modules/.pnpm/next@11.1.3_d2d3f5d29d8bc921bbe8ef8bb649cedb/node_modules/next/dist/server/render.js:647:34) {  page: '/Parts'}RequestId: 9c5d9c78-d2e8-40f1-a3f8-09a401287534 Error: Runtime exited without providing a reasonRuntime.ExitError
```

image

**Comment by masonmcelvain** [comment]
Related: https://github.com/iFixit/ifixit/pull/44261

**Comment by andyg0808** [comment]
This doesn't seem needed any more.

**Pull request closed without merging**
