### PR TITLE
Troubleshooting ToC: Finalize headings

### PR DESCRIPTION
**Pull request by andyg0808**
This configures the table of contents per the description in https://github.com/iFixit/ifixit/issues/51115.

## QA Notes
Please confirm that the table of contents matches the specified behaviors.

Closes https://github.com/iFixit/ifixit/issues/51115

### CODE REVIEW

**Comment by ianrohde** [comment]
I hid all but the first desktop TOC headings, [here](https://github.com/iFixit/react-commerce/pull/2159/files#diff-1d449ad5feaeea815ccf696a69d45380b874a41e1452884ef06bf960e15ef40aR260-R264). If you remove that block, we should be good to go.

It was a temp resolution for https://github.com/iFixit/react-commerce/pull/2151. Apologies for not adding more context to the description.

**Comment by andyg0808** [comment]
@ianrohde You'd mentioned that and I forgot to deal with it; thanks. Done now in [7516b06](https://github.com/iFixit/react-commerce/pull/2159/commits/7516b068468f1a1a56fce56da412454510274010).

**Review by ianrohde — APPROVED** [review]
CR ⚪ 

Looks great on:
`/Troubleshooting/Refrigerator/Ice+Maker+Not+Making+Ice/481782`
`/Troubleshooting/Garbage_Disposal/Hums/491105`
`/Troubleshooting/Google_Phone/Google+Pixel+Overheating/479437`

**Comment by kthaler** [comment]
Using the these platforms:
Macbook M1 + Google Chrome
Windows 11 + Firefox
iPhone 12 + Safari
Google Pixel 7 + Chrome

I've confirmed the following:

- [x] Related Problems are never shown in desktop and mobile TOC
- [x] All level-2 headings (excluding Related Problems) from the conclusion section are displayed in the desktop/mobile TOC
- [x] If there are 1+ conclusion headings (excluding Related Problems), they are separated from the causes list with a Conclusion heading in the desktop/mobile TOC
- [x] All level-2 headings (including Related Problems) from the conclusion section are displayed in the mobile outline
- [x] If there are 1+ conclusion headings, they are separated from the causes list with a Conclusion heading in the mobile outline

QA 💎 - The toubleshooting TOC headings all match the specified behaviors

**Pull request merged**
