### PR TITLE
Simplify warranty banner component and adjust according to mockup

### LINKED ISSUE #1806: Uniform lifetime warranty banners
Currently we have 2 types of lifetime warranty sections in react-commerce, one banner style and one full width:
  
Screenshot 2023-07-06 at 08 49 38

Screenshot 2023-07-06 at 09 20 16

Currently these 2 are implemented with 2 different components. Since we're trying to make section reusable, let's merge this 2 into a single configurable component

### PR DESCRIPTION
**Pull request by dhmacs**
closes #1806 

## QA

1. Open a product list page that has the lifetime warranty section (e.g. [/Parts](https://react-commerce-git-refactor-product-list-warranty-banner-ifixit.vercel.app/Parts))
2. Verify that the banner renders correctly and according to [mockup](https://www.figma.com/file/BolmFORO6ZfHXePOSyEGSS/iFixit---Page-sections?type=design&node-id=383-9494&mode=dev)

Screenshot 2023-07-06 at 17 10 16

### CODE REVIEW

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 Thanks for doing this!

The bundle analysis diff seems reasonable, given that this pull moves some JS around and adds a Wrapper to a number of components.

**Comment by dhmacs** [comment]
@masonmcelvain yes I've investigate a bit around that and it seems to be due 2 more code sharing between product and product list templates.

One interesting finding is that the bundle analyzer script that we're using differs from the Next.js build output stats. I'm trying to understand what's wrong with that, but it's unrelated to this PR

**Comment by k0rvusk0r4x** [comment]
Overall, the banner matches the mockup and is responsive.

QA 😺 

The text of the banner is different. Is this something done in ops or on our side? If it is on our side, can we get a link or screen shot where we decided on the change?

deploy_block 😿

**Comment by masonmcelvain** [comment]
@k0rvusk0r4x I think the text is controlled in Strapi

https://refactor-product-list-warranty-banner.govinor.com/admin/content-manager/collectionType/api::product-list.product-list/1?plugins[i18n][locale]=en

This is the Strapi page for `/Parts`. If you scroll down, you'll see the text and call to action match the preview. You can experiment with changing Strapi, and seeing the changes reflected in the preview.

**Comment by dhmacs** [comment]
@k0rvusk0r4x as @masonmcelvain is suggesting, the copy is driven by Strapi, so it'll be whatever is being set in production Strapi 👍 

un_deploy_block 🏎️

**Pull request merged**
