### PR TITLE
Stop using middleware

### LINKED ISSUE #820: No-indexing Middleware: Put it back in code
### Facts

* Currently our tiny no-index middleware is being run as an `Edge Function` in vercel. This means that code is run in a different physical location from the main app
   - https://github.com/iFixit/react-commerce/blob/c7692458348abb34f589faaf59e4abb565ee66ed/frontend/middleware.ts#L5-L11
   - This code also runs on every cache hit, slowing them down
* Right when this change was deployed, the number of requests to our app jumped up 5x
  - Don't know why here
* Right when this change was deployed several errors about getting 503 from Strapi became 20x more frequent

### Hypothesis
????

### Do This

Implement the above functionality without using middleware because it [doesn't appear](https://github.com/vercel/next.js/discussions/38989) you can have vercel run your middleware in your normal app.

CC @sterlinghirsh @masonmcelvain

### PR DESCRIPTION
**Pull request by masonmcelvain**
Middleware is run in a different location than our app. It runs on every cache hit, which is slow. We also noticed that the number of requests to our app spiked 5x and Strapi 503s increased by 20x

We're not sure why these things are happening, but for now let's do this in code instead.

## QA

Make sure the previews have the header `X-Robots-Tag: noindex, nofollow`

## On deploy

Make sure www.ifixit.com/Parts doesn't have that header, but https://react-commerce-prod.vercel.app does.

CC @danielbeardsley

Closes #820

### CODE REVIEW

**Comment by masonmcelvain** [comment]
QA ✌🏻 the previews have the header

**Review by danielbeardsley — APPROVED** [review]
CR :+1: 

:boom:

**Comment by danielbeardsley** [comment]
> Did you experience slow response times due to middleware? 

I think he means comparatively slow. Vercel is saying invocations average in around 5ms. This is fast enough to not care from a users perspective. But the extra server process running, the more limited environment your code is running in, and the fact that the middleware runs on cache hits too is just extra complexity that we don't need. This code is equivalent in functionality, but involves way less infrastructure and special knowledge.

While this is the right task (set a header) for the idea of middleware, the fact that they run all middleware on a separate server process, on a different JS runtime, on a different continent is just way more complexity than is needed to run several lines of code.

**Comment by dhmacs** [comment]
@danielbeardsley I agree, not necessary for this 👍 I was just trying to understand what issues we might have if for some reason we need to use them in the future

**Comment by danielbeardsley** [comment]
FYI, using middleware *definitely* changed something. After disabling it (this pull), server invocations dropped back down 5x:

image

It sure seems like the middleware caused #818 which would explain the increase in number of requests.

**Comment by danielbeardsley** [comment]
Turns out, it's a bug in next.js. Well, at least it's been reported:
https://github.com/vercel/next.js/issues/38845

**Pull request merged**
