### PR TITLE
Add product page quote section

### LINKED ISSUE #1535: Add product page quote section
Implement product page quote section according to [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=4600-47732&t=FjYHNWsi2enlEylc-4)

Screenshot 2023-04-05 at 18 39 49

### PR DESCRIPTION
**Pull request by dhmacs**
closes #1535 

## QA

1. Open a [featured product page preview](https://react-commerce-git-add-product-page-quote-section-ifixit.vercel.app/products/repair-business-toolkit)
2. Verify that the quote section si implemented as specified in #1535 
3. Verify that the section is responsive
4. Verify that you can edit the section content from [Strapi](https://add-product-page-quote-section.govinor.com/admin/content-manager/collectionType/api::product.product/1)

### CODE REVIEW

**Comment by jordycosta** [comment]
QA 🟢 

The [quote section](https://react-commerce-git-add-product-page-quote-section-ifixit.vercel.app/products/repair-business-toolkit) is responsive on various view-ports ✅ 
I am able to edit the content shown [via Strapi](https://add-product-page-quote-section.govinor.com/admin/content-manager/collectionType/api::product.product/1) ✅ 

quote

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by masonmcelvain** [comment]
deploy_block ✌🏻 the leftmost `"` is top-aligned in the mockup, but not in @jordycosta's screenshot

**Comment by jordycosta** [comment]
@masonmcelvain oop 😅 

That's my bad, nice catch!

**Comment by dhmacs** [comment]
@masonmcelvain I reviewed this with @mmarcon91 and he told me that this is ok.. If needed we can tweak it when we have some real world examples, but this should be ok for now

@jordycosta the look of the image largely depends on what we upload into Strapi, so that's something that can be changed from Strapi

un_deploy_block 👍

**Pull request merged**
