### PR TITLE
Fix screen reader experience

### LINKED ISSUE #446: Screen reader experience sub par with each model button image name as the image alt text
The model button image alt text is the image name and is read allowed while navigating the page with a screen reader.
image
The above 3 buttons get read allowed as:
imc-resized.png + Mac Parts - "imc resized dot png iphone parts"
iphone_x.png + iPhone Parts - iphone underscore x dot png iphone parts
pixel16.jpg + Android Phone Parts - pixel16 dot jpg android phone parts

Is the image alt text here necessary? If so, can we clean it up? The screen reader experience is very sub par as is.

### PR DESCRIPTION
**Pull request by sumukhipandey**
We didn't have the best screen reader experience for the product button images. This PR fixes this.

Closes #446 

CC: @erinemay

### CODE REVIEW

**Comment by erinemay** [comment]
QA 🦕 
- The screen reader experience is much smoother without the image alt text getting read for every product list button
- Works on /Parts, /Tools, and children collection links
- Product list image alt text is unaffected

Sample image attributes:
```html
<img alt="" src="https://ifixit-strapi-uploads.s3.amazonaws.com/imac_resized_3e5aa95221.png" decoding="async" data-nimg="fill" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%; object-fit: cover;">
```

deploy_block ❓ on a quick question
@sumukhipandey, are both of these files just affecting the product list ("Choose a model") buttons? Just want to make sure I'm testing everywhere that's affected. 

        ProductListChildrenSection.tsx
        ProductListSetSection.tsx

**Comment by sumukhipandey** [comment]
> QA 🦕
> 
> * The screen reader experience is much smoother without the image alt text getting read for every product list button
> * Works on /Parts, /Tools, and children collection links
> * Product list image alt text is unaffected
> 
> Sample image attributes:
> 
> ```
> 
> ```
> 
> deploy_block ❓ on a quick question @sumukhipandey, are both of these files just affecting the product list ("Choose a model") buttons? Just want to make sure I'm testing everywhere that's affected.
> 
> ```
>     ProductListChildrenSection.tsx
>     ProductListSetSection.tsx
> ```

@erinemay Sorry I should have made that clear. Yes these 2 files are for this section 
Screenshot 2022-08-25 092051

I will wait for CR to un deploy block this. Thank you!

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :dog: through 0ecfe26

**Review by andyg0808 — APPROVED** [review]
CR :dog: through 0ecfe267c5aa946710a9ced418023fd6eecbd382

**Comment by sumukhipandey** [comment]
un_deploy_block 🦋

**Pull request merged**
