### PR TITLE
Actions: Auto-commit formatting diff

### LINKED ISSUE #616: Linting: Add a GitHub Action
## Problem

We have a linter that runs as a post-commit hook or as an npm script `pnpm run format`. Sometimes, code sneaks into `main` that hasn't been formatted, and it causes unrelated code changes on feature branches if developers commit the formatting changes.

## Do this

Add a GitHub action that runs our linter. It could fail when there is a linting diff (forcing the dev to format and commit). Alternatively, it could apply the formatting changes in an automated commit, like we do for psalm baseline fixes in iFixit/ifixit.

### PR DESCRIPTION
**Pull request by masonmcelvain**
Much like we do for updating the psalm baseline, this automatically commits formatting changes produced by prettier every time a dev pushes to their branch.

The intent is to prevent formatting diffs sneaking through to `main`, which causes diffs on unrelated feature branches.

## QA

- Make a commit to this branch that would cause a diff if you ran `pnpm format`.
- Push the commit to this branch.
- The action should push a new commit that applies the diff.

Closes #616

### CODE REVIEW

**Comment by masonmcelvain** [comment]
dev_block ✌🏻 for testing

**Comment by masonmcelvain** [comment]
un_dev_block ✌🏻

**Review by andyg0808 — DISMISSED** [review]

**Comment by andyg0808** [comment]
CR :dog: through 682c2bf30fe0ee590fe4cd412a452944c8a423e0

**Comment by masonmcelvain** [comment]
QA ✌🏻 The bot does the thing!

I think I'll leave https://github.com/iFixit/react-commerce/pull/665/commits/f6cd5e9b183d21061c45fa0972ba209d900d0968 and https://github.com/iFixit/react-commerce/pull/665/commits/a20b6b57d1c091b162d2c5df5d27a0f769bd88db in the history as a demonstration of what the action does.

**Comment by masonmcelvain** [comment]
Hmm... it doesn't seem like the workflows re-run after the push? dev_block ✌🏻

**Comment by masonmcelvain** [comment]
QA ✌🏻 With the personal access token, all checks are re-run after the bot commit.

un_dev_block ✌🏻

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :dog: through 3026220f8a475167bbaebddba4a7b30c5c75086a

**Pull request merged**
