### PR TITLE
Fix lifetime guarantee wording

### LINKED ISSUE #1292: Featured Product Badge: Lifetime Warranty --> Lifetime Guarantee
Our `Lifetime Warranty` badge should read `Lifetime Guarantee`. We relabelled the Akeneo code from `Lifetime Garantee` to `Lifetime Warranty` some time ago and we want the text change to apply everywhere.

Badges on Featured Products don't match text in the banner. This juxtaposition makes the needed change very clear: 

image

Similarly, ProductList product cards need an update: 

image

@sterlinghirsh anything I'm missing here or is this just a text change needed somewhere?

### PR DESCRIPTION
**Pull request by dhmacs**
closes #1292 

## QA

1. Open Vercel preview
2. Go to product list pages and product pages
3. Verify that lifetime warranty badges now read "lifetime guarantee" as requested in #1292

### CODE REVIEW

**Comment by dhmacs** [comment]
The failing test are not related to this change it seems. There are many tests that fail for various reasons. 
@ardelato do you know why so many tests are failing? This PR seems pretty trivial 🤔 The thing that puzzles me is that there's seems to be many different reasons for which tests are failing, not just one

**Comment by batbattur** [comment]
Clicked `Update branch` to check if tests pass.

**Comment by deltuh-vee** [comment]
QA 🎬 
Lifetime Guarantee is now used instead of Lifetime Warranty.

**Review by batbattur — APPROVED** [review]
CR 🚛

**Pull request merged**
