### PR TITLE
Prevent Algolia hooks in product list empty state from unmounting

### LINKED ISSUE #398: Product search: Results and query / filters get out of sync very easily
### Description
Fixing a typo can result in no appropriate search results showing (URL is still at https://d3lnoy3aplwg2k.cloudfront.net/Parts/iPhone)
image

### Repro steps
1. Go to https://d3lnoy3aplwg2k.cloudfront.net/Parts/iPhone
2. Type "iphone 21 screen" into the search bar
3. Fix the typo 
       a. Add a 1 before the 2 to get: "iphone 121 screen"
       b. Delete the 1 after the 2 to get "iphone 12 screen"
4. After deleting the final 1 and getting expected search terms, the page is set to https://d3lnoy3aplwg2k.cloudfront.net/Parts/iPhone
5. Pressing enter doesn't add the url params. 

### Additional Notes
Was found during Hallway testing - I watched a test user make this exact mistake and fix it in this exact way.

### PR DESCRIPTION
**Pull request by dhmacs**
fixes #398 

This subtle bug is due to Algolia library behaviour. Whenever an Algolia hook or widget gets unmounted, the state is reset. I think this is not a wise API design choice because it makes it really easy to introduce subtle bugs, like in this case.
Here the problem is that the product list empty state makes use of `useSearchBox`. To fix the issue we're keeping the component mounted, but hidden via CSS when it's not needed.

## Changelog

- Fix the bug
- Remove unused dependencies
- Formatting adjustments: these are due to the fact that @federicobadini has fixed a discrepancy between prettier versions in the project, so many files are still not correctly formatted, and are being formatted when you change them.

## QA

1. Open the vercel preview
2. Verify that #398 is fixed

### CODE REVIEW

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by batbattur** [comment]
dev_block 🚒 on resolving conflicts for `pnpm-lock.yaml`

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 carry forward

**Comment by masonmcelvain** [comment]
un_dev_block ✌🏻

**Comment by deltuh-vee** [comment]
QA 🎬 
Results can still be returned after encountering an empty product list.

**Pull request merged**
