### PR TITLE
Product Page: Add compatibility disclosure

### PR DESCRIPTION
**Pull request by masonmcelvain**
Collapses the product page compatibility component when there are more than 10 model number lines.

## CR

The diff is easier to view with whitespace ignored.

It also seems like the Jest test that was changed was broken before. The product being tested only has 3 variants on the compatible device, so the previous test implementation should have produced `other model...`, however the test was asserting for `other models...`.

## QA
- Find a product with a compatible device that has >10 model numbers.
- Make sure the implementation matches the disclosure [mockup](https://www.figma.com/file/BolmFORO6ZfHXePOSyEGSS/iFixit---Page-sections?node-id=159-5560) (disregard the search bar for this PR).
- Make sure _both_ compatibility components otherwise match their `main` counterparts.

Closes https://github.com/iFixit/react-commerce/issues/1436

### CODE REVIEW

**Comment by deltuh-vee** [comment]
Is showing 1 extra model for compatible models intentional?
image
image

**Comment by masonmcelvain** [comment]
Ah man, I continue to misunderstand the meaning of the `maxModelLines` prop. To me, it means "how many model lines should be shown", but to previous implementors it meant something different. Fix incoming.

**Comment by masonmcelvain** [comment]
Should be fixed when that commit finishes deploying

**Comment by deltuh-vee** [comment]
QA 🎬 
* Implementation matches the mockup
* Both compatibility components match their counterparts on main

**Comment by danielcliu-ifixit** [comment]
> Ah man, I continue to misunderstand the meaning of the maxModelLines prop. To me, it means "how many model lines should be shown", but to previous implementors it meant something different. Fix incoming.

Yeah i remember having this discussion about it originally. If its a headache for developers we can just change it so its more universally intuitive.

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Pull request merged**
