### PR TITLE
Add IntlDate component

### LINKED ISSUE #1904: Fix troubleshooting template date hydration error
When you visit a troubleshooting page (e.g. `/Troubleshooting/Acer_Chromebook/Not+Charging/514224?revisionid=HEAD`) during development, you see the following error:

Screenshot 2023-08-10 at 09 36 25

This happens because there's an hydration mismatch between the server date locale format, and the browser date locale format.

### PR DESCRIPTION
**Pull request by dhmacs**
closes #1904 

## QA

1. Open a [troubleshooting preview page](https://react-commerce-git-fix-troubleshooting-date-ssr-bug-ifixit.vercel.app/Troubleshooting/Acer_Chromebook/Not+Charging/514224?revisionid=HEAD)
2. Verify that the last updated at date still renders

### CODE REVIEW

**Comment by dhmacs** [comment]
> There is a brief flash of the day of the week being shown and then going away. There also seems to be a date difference

@jordycosta Unfortunately this is expected. If this bothers us we could just hide the date until the client is hydrated. Would you prefer that?

**Comment by erinemay** [comment]
> > There is a brief flash of the day of the week being shown and then going away. There also seems to be a date difference
> 
> @jordycosta Unfortunately this is expected. If this bothers us we could just hide the date until the client is hydrated. Would you prefer that?

Would that appear like the recording, but not show the initial date flash? And show the final rendered date around the same time it updates in that recording?

**Comment by dhmacs** [comment]
@erinemay 
> Would that appear like the recording, but not show the initial date flash? And show the final rendered date around the same time it updates in that recording?

Yes, I can do it and if you don't like it we revert back to this if you want

**Review by sterlinghirsh — DISMISSED** [review]
CR :zap: I was curious about trying an approach like this. Not a huge fan of the visual change on page load but it's a tradeoff. We could probably get away with just using the US date format or matching the date format to the view language. But for now I'm down to try it and if we decide the flash is too annoying we can revert it. There's a similar concern for localizing currency display.

**Comment by sterlinghirsh** [comment]
I want to make sure the date difference is expected before we unblock this.

**Comment by dhmacs** [comment]
> I want to make sure the date difference is expected before we unblock this.

Yes, it's due to timezone differences. I've implemented a version that avoids FOUC. Let me know if you prefer this

un_ deploy_block 🏎️ 

cc @sterlinghirsh @erinemay @jordycosta

**Comment by jordycosta** [comment]
QA 🟢 

I think this is much better 👍 

firefox_VhSRtHxjnD

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Pull request merged**
