### PR TITLE
Add manage links to user menu

### LINKED ISSUE #152: Add manage link to user menu (Admins only)
Current react-commerce user menu:
image

Current iFixit main user menu:
image

The main differences here are the "My Team" and "Manage" links.

For "My Team", if the user api responds with a non-empty teams array, add the My Team link to `/Team`. This will redirect to the correct team and doesn't require generating a custom link. 
image

For "Manage", if the user api responds with a field "links" that contains a key "manage", include a link to `/Manage`. That target url is the value of user.links.manage.
 
image

For the moment, we won't try to handle anything else in the "links" object.

### PR DESCRIPTION
**Pull request by federicobadini**
closes #152 

### QA

1. Visit Vercel preview
2. Verify that - according to the user's permissions - links to `/Manage` and `/Team` are shown

### CODE REVIEW

**Comment by jordycosta** [comment]
dev_block 🟥 

If a non-administrator has a team / is in a team, the **My Team** link is not present

**Comment by federicobadini** [comment]
> If a non-administrator has a team / is in a team, the **My Team** link is not present

So the Team link should be available also for non admin users? 
Because the issue title was currently `Add manage link to user menu (Admins only)` so I tied both links to the admin role

**Comment by jordycosta** [comment]
@federicobadini The **My Teams** dropdown menu item shows for non-admins if they are in/have a team

The team page isn't really admin related, it just links to the user's team page - [example](https://me.cominor.com/Team/46451/Team+1234)

@sterlinghirsh thoughts on this?

**Comment by sterlinghirsh** [comment]
Sorry for the confusion. The Manage link is for admins only (i.e. if they have a manage link in their user api response). The Team link is for anyone with a team in their user api response. The title confusion was because there were two very similar issues and I think I closed one but didn't clarify the title on the remaining one.

**Comment by sterlinghirsh** [comment]
To be clear, we shouldn't have to check isAdmin. Anyone with the manage link in the api is allowed to see it.

**Comment by federicobadini** [comment]
un_dev_block 👍

**Comment by deltuh-vee** [comment]
QA 🎬 
* Users on a team get a "My Team" link in the user menu
* Admins get a "Manage" link in the user menu

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Pull request merged**
