### PR TITLE
Pages: Add `/Shop/[handle]` page

### LINKED ISSUE #473: Marketing collections on /Shop
/Shop/{handle} should support marketing collections.

### PR DESCRIPTION
**Pull request by masonmcelvain**
## QA

Visit /Shops/anything. Make sure the page 404s for anything except marketing collections, and that the page works properly for marketing collections.

CC @sterlinghirsh 

Closes #473

### CODE REVIEW

**Review by sterlinghirsh — APPROVED** [review]

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by sumukhipandey** [comment]
CR 🦋

**Comment by jordycosta** [comment]
What would be an example of a marketing collections handle?

So far anything I put as /Shops/<handle> 404's

**Comment by masonmcelvain** [comment]
@jordycosta Any product list whose type is `marketing`. The data lives in Strapi, so you could go to the strapi admin to find some collections. I actually don't know where the strapi backend is hosted for these previews, but the main branch uses main.govinor.com/admin

**Comment by erinemay** [comment]
There are only a few marketing product lists in production, but I tried with the active one and it worked. QA ™️ 
Product list checked: Genuine_Google_Pixel_Parts.

The following links 404:
/Genuine_Google_Pixel_Parts
/Parts/Genuine_Google_Pixel_Parts
/Shop/any-other-legit-collection-handle

BUT with /Shop/, the page loads as expected: 
https://react-commerce-prod-r1as46gxm-ifixit.vercel.app/Shop/Genuine_Google_Pixel_Parts
image


deploy_block 🦺

> Visit /Shops/anything. Make sure the page 404s for anything except marketing collections, and that the page works properly for marketing collections.

 @masonmcelvain is it /Shop/ or /Shops/? Right now, Shop (singular) is working.

**Pull request merged**
