### PR TITLE
Troubleshooting: Add solutions TOC

### PR DESCRIPTION
**Pull request by jyee27**
Add the "Causes" TOC section. This only includes solutions (solution cards). Clicking on a TOC link takes you to the corresponding solution card. The section doesn't show if there are no solutions.

Closes: https://github.com/ifixit/ifixit/issues/47188

### CODE REVIEW

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by aburke07** [comment]
CR :alien:

**Comment by k0rvusk0r4x** [comment]
I haven't been able to get the preview to work here. Not sure what's up/why it's not working.

**Comment by jyee27** [comment]
The regular preview is working for me, but the prod preview is 500ing.
https://react-commerce-git-vulcan-add-solutions-toc-ifixit.vercel.app/Vulcan/troubleshooting-test
https://react-commerce-prod-git-vulcan-add-solutions-toc-ifixit.vercel.app/Vulcan/troubleshooting-test

**Comment by k0rvusk0r4x** [comment]
- The "Causes" section is there.
- Clicking the links causes the page to scroll to the correct section. (has `#<section_name>` appended to url)

QA 😺

**Pull request merged**
