### PR TITLE
Update product cross sell

### LINKED ISSUE #1910: Update "Frequently Bought Together" widget on ProductDetail Page
We've seen a huge drop in "Frequently Bought Together" engagement since the new ProductDetail Page was launched. A very reasonable theory suggests that the feature is now too far down the page. 
 
image

@mmarcon91 worked up a [design](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?type=design&node-id=8831-143909&mode=design) that integrates the Frequently Bought Together offer with the main BuyBox. Let's implement it! 

image

Implementation notes: 

1) The checkboxes pictured should be unchecked by default
2) Make sure the GA Events are copied over to the new cross-sell widget implementation

CC @sterlinghirsh @dhmacs @c00perdanny @ifixitmaxb

### PR DESCRIPTION
**Pull request by dhmacs**
close #1910 

## Note for CR

From #1910:
> Make sure the GA Events are copied over to the new cross-sell widget implementation

It seems to me that the tracking is entirely done with `useAddToCart('Frequently Bought Together')`. I haven't found any other custom tracking, but I'd appreciate a double check.

## QA

1. Open a [product page preview](https://react-commerce-git-update-product-cross-sell-ifixit.vercel.app/products/pro-tech-toolkit)
2. Verify that the frequently bought together box is rendered right after the add to cart button
3. Verify that you can successfully add "frequently bought together" items to cart

### CODE REVIEW

**Comment by jordycosta** [comment]
QA 🟢 

I am able to add items from the **Frequently bought together** section to my cart 👍 

https://github.com/iFixit/react-commerce/assets/95656772/7cbc897e-9726-42a2-b20a-24005f549585

**Review by masonmcelvain — APPROVED** [review]
CR 👏🏻  Looks great!

Two concerns I have:

- The cross sell item image/text is not horizontally aligned with it's button. I see this in @jordycosta's QA too. (I'm using firefox)

image

- We no longer link to the cross sell item's product page from the text/image. While not explicitly part of the spec, I think this is a regression that would surprise stakeholders.

deploy_block ✌🏻

**Comment by dhmacs** [comment]
> The cross sell item image/text is not horizontally aligned with it's button. I see this in @jordycosta's QA too. (I'm using firefox)

This is validated with @mmarcon91, and it is so that products with longer names can use more space

> We no longer link to the cross sell item's product page from the text/image. While not explicitly part of the spec, I think this is a regression that would surprise stakeholders.

Good point, I'll add the link functionality as well 👍  

dev_block 🛑

**Comment by dhmacs** [comment]
un_dev_block 🏎️  un_deploy_block 🟢

**Review by masonmcelvain — APPROVED** [review]
CR 👏🏻  Thanks for the change!

**Comment by jordycosta** [comment]
QA 🟢 

No functionality has been lost since https://github.com/iFixit/react-commerce/pull/1929#issuecomment-1688261720 👍 

There is now a link to the relative product page in the cross-sell section ✔️ 

Untitled

**Pull request merged**
