### PR TITLE
Troubleshooting: Bypass varnish always

### PR DESCRIPTION
**Pull request by jarstelfox**
This commit adds a header which we will use to bypass varnish

As an added measure I added a nice bit of logging.

QA
---

* Make an edit to a vulcan page
* Visit the page without `?revisionid=HEAD`
* Ensure the latest changes show up

Connects: https://github.com/iFixit/ifixit/issues/48965

### CODE REVIEW

**Comment by jarstelfox** [comment]
deploy_block 🌵 on https://github.com/iFixit/ifixit/pull/49142

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I'm still seeing outdated cached versions of Troubleshooting pages for a bit after making a change.

This was the page I was using:
https://react-commerce-git-dsc-api-passthrough-ifixit.vercel.app/Troubleshooting/Whirlpool_Washing_Machine/Whirlpool+Washer+Not+Spinning/506149

**Comment by jarstelfox** [comment]
huh, It looks like the [API for ifixit is updated](https://jstelfox.cominor.com/api/2.0/Troubleshooting/wikiid/506149), the page is not cached: 
image


I am also *not* seeing the most recent data. I will dig here...

**Comment by deltuh-vee** [comment]
QA 🎬 
Edits to Vulcan pages are shown immediately without `?revisionid=HEAD`.

**Comment by deltuh-vee** [comment]
un_dev_block 👍

**Pull request merged**
