### PR TITLE
Vulcan: Fix breadcrumbs and tabs collapsing sensibly

### PR DESCRIPTION
**Pull request by ianrohde**
## Summary
The breadcrumbs are built to dynanmically collapse, so it doesn't make sense to also collapse the tabs.

<details>
  <summary>Updated Post-fix Video</summary>

https://github.com/iFixit/react-commerce/assets/1634505/0c8f9d2d-a64d-4a63-a5ac-73746591bbe1

</details>

## Modified
1. [zero flexShrink on navTabs parent](https://github.com/iFixit/react-commerce/commit/fbf54a98b046f2ea8eee636ec96896c99b45c69a)

## CR/QA Notes
http://localhost:3000/Vulcan/Dryer_Not_Spinning
- disallow flex shrinking to force min width
- refactor properties

Closes: https://github.com/iFixit/ifixit/issues/47235

### CODE REVIEW

**Comment by erinemay** [comment]
The breadcrumbs are collapsing really nicely when I change my viewport width!

dev_block 🧷 The vertical spacing on the second header row that appears on mobile devices seems to be squished now. These two screenshots are from the iPhone 14 with Safari on Browserstack.
https://react-commerce-git-vulcan-collapse-breadcrumbs-sensibly-ifixit.vercel.app/Vulcan/nested_troubleshooting_test
image

On main (https://react-commerce.vercel.app/Vulcan/nested_troubleshooting_test):
image

It actually looks like the mockup has the breadcrumbs on mobile outside of the header bar. Not sure if you want to change all that here. I can make a new issue if needed.
image

**Comment by ianrohde** [comment]
Jarred and I were just talking about the differences between the design and the Vulcan implementation. I'm going to make another pass at it and get them closer since the heights aren't quite right anyway.

**Comment by erinemay** [comment]
👍 
Also, it looks like as many breadcrumbs as can fit are showing up on mobile instead of just the last one.
https://react-commerce-git-vulcan-collapse-breadcrumbs-sensibly-ifixit.vercel.app/Vulcan/Dryer_Not_Spinning
image

**Comment by ianrohde** [comment]
I'm reviewing effort on porting over everything until we figure out what the preferred way is to share components between repos.

**Comment by jarstelfox** [comment]
Minor: The approach I took on the guide page was this: https://ifixit.slack.com/archives/C089J162J/p1676926181287159

In short, the tabs still collapse, but only after the breadcrumbs fully collapse.

We need the collapse behavior for tabs far more with translations since the tab text could be much longer in another lang, thus running out of real-estate before we hit the mobile breakpoint.

It might be worth adding similar CSS which will solve possible issues down the road

**Comment by ianrohde** [comment]
I am going to take a different approach. If we are bringing in react-commerce, it doesn't make sense to port over components now. I'm going to address via styling now, and open an issue to carry the component over once we merge repos.

**Comment by ianrohde** [comment]
@erinemay https://github.com/iFixit/react-commerce/pull/1635/commits/0607f6766e6528cb31aa014f15232673b8ebe550 contains changes to get this closer to the design you referenced.

<details>
  <summary>Video</summary>

https://github.com/iFixit/react-commerce/assets/1634505/0c8f9d2d-a64d-4a63-a5ac-73746591bbe1

</details>

**Comment by deltuh-vee** [comment]
QA 🎬 
Breadcrumbs are now collapsing before shortening the tabs component.

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Pull request merged**
