### PR TITLE
No Results Search: Add link to main search

### LINKED ISSUE #401: No-results search page: add link to main search
## Problem
When a user searches on a product list and gets no results, it's not always clear that their search is restricted to the current product list.

## Do This
Make the no-results component say something like `No matching products found in [page title]` instead of just "no results". Add a link that says "Search all of iFixit for [search term]". That should take the user to `https://www.ifixit.com/Search?query=[search term]`.

For example, `No matching products found in iPhone 7 Parts` `Search all of iFixit for "potato head"` => `https://www.ifixit.com/Search?query=potato%20head`

The link can be relative in production, but probably needs to be absolute in for it to work from vercel previews.

### PR DESCRIPTION
**Pull request by sterlinghirsh**
When a user searches but does't find any results, this changes the no-results page to clarify that they're only searching within their given page. There's now a link to the main iFixit search with their query pre-filled, too.

I also added a couple changes in the project setup to fix some issues I encountered while setting this up on windows.

Closes #401

### CODE REVIEW

**Review by dhmacs — APPROVED** [review]
I like how it turned out 👍 

CR ⚡

**Comment by erinemay** [comment]
deploy_block 🦖 on a thought... 
Do we want the ifixit search to be `?doctype=product`

**Comment by erinemay** [comment]
> deploy_block 🦖 on a thought... Do we want the ifixit search to be `?doctype=product`

Products are below the fold on some important mobile devices when the doctype isn't product:

<details><summary>iPhone 13</summary>

image

</details>

<details><summary>Samsung Galaxy S22</summary>

image

</details>

**Comment by sterlinghirsh** [comment]
un_deploy_block :zap: I left it as a global search on purpose. The idea is that if someone searches for something that's not a product, we want to give them a quick way to do a global search.

**Pull request merged**
