### PR TITLE
Update Jest Configuration for React Component Testing

### PR DESCRIPTION
**Pull request by ardelato**
## Description

This pull request updates the configuration of `Jest` to improve the testing of React components. The changes include adding support for NextJS, modifying the transformation rules, and adding a mock React context for accurate component rendering in tests.

## CR Notes:

I tried my best to explain the reasoning for each change in the commit messages. I will highlight the following:
- We needed to override the default behavior of not transforming `/node_modules` paths because `Jest` does not natively support `ESM Modules`. As a result, we were having issues where we are importing packages that are `ESM modules`.

	unexpected export token

- We needed to add a separate transformer to handle some imports of our `css` modules.  https://github.com/facebook/jest/issues/3094#issuecomment-514308251
	CSS Transformation error

- Lastly, some of our React Components require some type of `React Context` in order to render which is why I created a utility function to wrap the `AppContext` component around any components you pass. 
	App Contenxt missing

## QA Notes:
These changes should not have affected any of the actual `Frontend` components. We will just need to confirm that CI still passes.

Closes: #1071

### CODE REVIEW

**Comment by jordycosta** [comment]
QA 🟢 

CI is passing ✅ 
[View Summary](https://github.com/iFixit/react-commerce/actions/runs/3624655207)

**Review by batbattur — DISMISSED** [review]
CR 🚛 The new changes look good
@ardelato Thanks for updating it!

**Comment by ardelato** [comment]
QA 🐷 just a master merge and CI is still passing

**Review by batbattur — APPROVED** [review]
CR 🚛

**Pull request merged**
