### PR TITLE
Vulcan: Fix `youtube-lite` on mobile

### PR DESCRIPTION
**Pull request by ianrohde**
## Issue

The inline width/height styles on the `youtube-lite` element were forcing the element past the mobile viewport. This pr adds styles that override the width/height when necessary to keep things contained.

While working on this, I found the styles for our prerendered.tsx component were getting a bit unruly. I split them out as part of this pull to keep things tidy and more manageable as we move forward.

I also found a small visual bug with `imageBox` that I patched with https://github.com/iFixit/react-commerce/commit/bf1079f33cb52eabf87f01b4c5ff1357aa09918b

## CR/QA

<details>
<summary>Before Screenshot</summary>

Screenshot 2023-08-25 at 9 11 58 AM

</details>

<details>
<summary>After Screenshot</summary>

Screenshot 2023-08-25 at 9 13 57 AM

</details>

I tested with QA's awesome list of Vulcan case-specific examples: https://docs.google.com/spreadsheets/d/1HjHwsbd4MC1gkvKTK9vUnf3r-dzKawJLgkobmdeo7Iw/edit#gid=642460031

Closes https://github.com/iFixit/react-commerce/issues/1937

### CODE REVIEW

**Comment by andyg0808** [comment]
CR question: The purpose of the `Prerendered` component is almost completely these styles. I think splitting them out doesn't really buy us anything, because it adds a file hop for devs to find them and only extracts ~25 lines of actual `Prerendered` code. I agree that they're a bit messy, but it's not obvious to me how to make that better.

**Comment by ianrohde** [comment]
@andyg0808 are you asking that I move the styles back to `prerendered.tsx`?

I thought that moving them out would be helpful since they are the focus. Basically, instead of modifying `prerendered.tsx`, we now modify `styles/prerenderedStyles.ts`. I don't really care either way, I was just trying to improve the situation.

**Comment by andyg0808** [comment]
> I was just trying to improve the situation.
Totally, and thank you!

> are you asking that I move the styles back to prerendered.tsx?
Yes, but feel free to argue; I'm open to debate!

> I thought that moving them out would be helpful since they are the focus. Basically, instead of modifying prerendered.tsx, we now modify styles/prerenderedStyles.ts
True enough, but I'm inclined to think that the distraction level of the 25 lines of component code is low, whereas the "where do these styles get used" question is brought up by splitting them out.

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by aburke07** [comment]
I personally like having the styles separated, but I don't feel strongly either way.

**Comment by deltuh-vee** [comment]
QA 🎬 
Youtube videos no longer overflow on mobile.

**Pull request merged**
