### PR TITLE
Re-refactor Footer: Move back into /frontend

### PR DESCRIPTION
**Pull request by hcutrone**
Since we are making separate footers for cart and guide pages, let's move the cart footer back into /frontend and fix some type regression.

## CR
I did not delete the components I changed for the GuideFooter. They are not being used anywhere, but they are nicely broken up and restyled to fit the new footer design, so I decided to keep them for future reference. 

## QA
Please just make sure the footer on /Parts and /Tools has not been affected :) 

Closes: #695 
Connects: https://github.com/ifixit/ifixit/issues/43967

### CODE REVIEW

**Comment by jordycosta** [comment]
QA 🟢 

Not seeing any regressions on the footer for /Parts or /Tools

footer

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by hcutrone** [comment]
I'm gonna deploy_block :burrito: on a review from @dhmacs, just to make sure this clears up the regression issue he brought up :)

**Review by dhmacs — APPROVED** [review]
Looks great! Thanks for fixing it 👍 

CR ⚡

**Comment by hcutrone** [comment]
Thanks @dhmacs ! un_deploy_block :burrito:

**Pull request merged**
