### PR TITLE
Vulcan Products: Load via the API

### PR DESCRIPTION
**Pull request by jarstelfox**
QA
---

* Ensure products on Vulcan pages look the same

Connects: https://github.com/iFixit/ifixit/issues/48101

### CODE REVIEW

**Comment by jarstelfox** [comment]
deploy_block 🌵 on #48641

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by erinemay** [comment]
un_deploy_block 👍 https://github.com/iFixit/ifixit/pull/48641 is out

**Comment by erinemay** [comment]
QA 👍 product cards appear identical to main

https://react-commerce-git-use-products-added-to-troubles-f41f90-ifixit.vercel.app/Vulcan/Nintendo%20Switch%20Blue%20Screen%20of%20Death

**Pull request merged**
