### PR TITLE
Refactor: Move Footer into `packages/ui` and split up components

### PR DESCRIPTION
**Pull request by hcutrone**
We want to use the new footer across the whole site, which includes php-land and pages with no store info. To prepare for this, let's do 2 things:
1. Move the footer into `packages/ui` so it can be accessed in the monorepo
2. Split components up for clarity ~~and to make it easier to cherry-pick components (if we want to build separate footers that don't rely on store information).~~

In a new pull, I will create a footer that can be used in non-store based pages.

## CR
Commit-by-commit. I broke things down into small commits to hopefully make it easier to see the changes.

## QA
Please make sure this does not affect the footers in /Parts and /Tools.

### CODE REVIEW

**Comment by jordycosta** [comment]
QA 🟢 

Not seeing any footer regressions in /Parts and /Tools

---

### Testing Procedure:
1. Navigate to [`react-commerce-prod`](https://react-commerce-prod-git-refactor-footer-ifixit.vercel.app/) (/Parts & /Tools)
2. Compare the footer to https://ifixit.com (/Parts and /Tools)
3. Ensure that nothing has changed in the footer

---

### Screen Capture:

footer

**Comment by dhmacs** [comment]
@hcutrone 

> 1. Move the footer into `packages/ui` so it can be accessed in the monorepo
> 2. Split components up for clarity and to make it easier to cherry-pick components (if we want to build separate footers that don't rely on store information).

It seems like what you're describing is already done. Reusable footer components are already exported by the`ui` package. What is on the commerce frontend layout is an example of how to compose them to create a footer.
Is the purpose of this reusing more complex components, like the newsletter form?

deploy_block 🔢

**Comment by hcutrone** [comment]
> Is the purpose of this reusing more complex components, like the newsletter form?

@dhmacs Yes! Eventually, we would like to use one unified footer in react-commerce and iFixit/ifixit. So while I didn't _need_ to move `LayoutFooter` yet, it sets us up to use it in iFixit/ifixit later. 

That second bullet is slightly incorrect, as we have decided not to cherry-pick components to create a new footer, but rather to use the same footer and have default values to use when there is no currentStore ([see this Slack thread](https://ifixit.slack.com/archives/C01GVQAAGDU/p1660930396485619?thread_ts=1660868317.728449&cid=C01GVQAAGDU), thank you @sctice-ifixit for documenting). For now, so that we don't mess up the current Collection's footer, we are going to copy `LayoutFooter` and make our changes, then merge the two later. But that's another PR...

**Comment by andyg0808** [comment]
CR :dog: through 65d63f1
Looks reasonable to me.

**Review by andyg0808 — DISMISSED** [review]

**Comment by hcutrone** [comment]
dev_block :burrito: on deciding what layout we want for the footer. We may actually end up wanting different footer files for Store and Guide pages, in which case we would not need `LayoutFooter` to be in `packages/ui`

**Comment by hcutrone** [comment]
un_dev_block :burrito: un_deploy_block :burrito: 
We decided on a footer layout! See [this Slack thread](https://ifixit.slack.com/archives/C01K32B4FPX/p1661443067599519). And the Guide and Store versions are very similar, thus I think it makes sense to have one main footer component for both types of pages.

**Comment by hcutrone** [comment]
This merge with master was a little wonky, so I would appreciate another quick QA if possible :heart:

**Comment by jordycosta** [comment]
QA 🟢 
deploy_block 🟨 

I'm seeing a very minor page shift between [Parts](https://react-commerce-prod-git-refactor-footer-ifixit.vercel.app/Parts) and [Tools](https://react-commerce-prod-git-refactor-footer-ifixit.vercel.app/Tools), also a minor shift for some elements on when comparing [Parts](https://react-commerce-prod-git-refactor-footer-ifixit.vercel.app/Parts) to https://ifixit.com/Parts 

1. Open both links
2. Scroll down to the end of the page on both
3. Switch tabs between the two

> There is a very minor shift in height for some elements on the page (i.e. banner positioning, payment methods, some other text on the live site)

---

Nothing seems to be missing from the footer, but I want to ensure that this minor shift is expected/will be okay when merged

**Review by andyg0808 — APPROVED** [review]
CR :dog: through bd02c90231073012389a22069063b8c823eec6ed

**Comment by hcutrone** [comment]
I'm gonna make the executive decision to say the difference is not significant enough to be concerning. All I see is a _very_ small shift in the Payment icons on the footer, and digging into the CSS everything looks identical. I will take the blame if this breaks things :sweat_smile: 
un_deploy_block :burrito:

**Pull request merged**
