### PR TITLE
README: update with instructions to use vercel cli

### LINKED ISSUE #1617: Vercel Development Environment: support vercel cli
Vercel has a great cli for pulling down a .env file from the configured "development" deployment but we aren't using it.

### Do This
* Set the needed env variables for the "development" deployment in the vercel project (which one?) to values that support local development.
* Update README to be advise using vercel cli to get the repo set up

### PR DESCRIPTION
**Pull request by danielbeardsley**
You can pull down all the appropriate env vars with `vercel env pull`, so let's update the instructions with two ways of getting an env file.

If you don't have a vercel account, I've left (and reformatted) the previous instructions.

Closes #1617

### CODE REVIEW

**Review by ianrohde — DISMISSED** [review]
Cool, thanks!

CR ⚪

**Comment by ianrohde** [comment]
@danielbeardsley I ran this and it creates a `.env` file in the root, and a few strapi-sdk files. We should add them to `.gitignore`?

Screenshot 2023-05-04 at 4 10 22 PM

**Comment by danielbeardsley** [comment]
> it creates a .env file in the root, and a few strapi-sdk files. We should add them to .gitignore?

Hopefully the env file had more in it than that? It had a bunch of secrets for me 

I think the strapi-sdk files must be from some install scripts outside this pull, but I went ahead and added the env file to gitignore.

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by deltuh-vee** [comment]
Which scope should I use?
image

**Review by deltuh-vee — CHANGES_REQUESTED** [review]

**Comment by deltuh-vee** [comment]
dev_block ✊

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Review by deltuh-vee — DISMISSED** [review]

**Comment by jordycosta** [comment]
dev_block 🟥 (testing purposes, deleting after)

**Comment by danielbeardsley** [comment]
un_dev_block :+1:

**Comment by erinemay** [comment]
Also curious which scope I should use
image

**Comment by danielbeardsley** [comment]
> Also curious which scope I should use

iFixit. I'll add that to the README.

**Review by ianrohde — APPROVED** [review]
CR ⚪ 

Thoughts on setting the scope automatically with a cli command? https://vercel.com/docs/cli/global-options#scope

**Comment by danielbeardsley** [comment]
> Thoughts on setting the scope automatically with a cli command

Nice. The rest of this is not automatic (copy-pasting from the readme), so I'm OK with another instruction.

**Comment by erinemay** [comment]
QA 👍 
Following the steps worked.

deploy_block 🧷 How important is it that we each use our own api keys? My new .env file also had a bunch of secrets, including one of Massimo's algolia api keys. I already had my own, so I replaced it again after following these steps.

**Pull request merged**
