### PR TITLE
Matomo: Remove code

### PR DESCRIPTION
**Pull request by ianrohde**
## Purpose

Remove all code references to Matomo in https://github.com/iFixit/react-commerce

## CR/QA

According to related issue, we've already used configuration to stop sending data.

Removal step 2 of 3 in https://github.com/iFixit/ifixit/issues/50502

### CODE REVIEW

**Comment by ianrohde** [comment]
deploy_block 🔴 on syncing with remainder of https://github.com/iFixit/ifixit/issues/50502

**Comment by jarstelfox** [comment]
There are few more references:

https://github.com/iFixit/shopify-v2/blob/4883bb98b19a0735542694717abb4774744c1da6/src/scripts/analytics/piwik/cart.ts#L149

https://github.com/iFixit/shopify-v2/blob/4883bb98b19a0735542694717abb4774744c1da6/src/snippets/analytics-switch.liquid#L3-L5

https://github.com/iFixit/shopify-v2/blob/4883bb98b19a0735542694717abb4774744c1da6/src/snippets/theme-js-vars.liquid#L28

**Comment by ianrohde** [comment]
Not sure how I missed those, but fixed in https://github.com/iFixit/react-commerce/pull/2078/commits/3417bca40945d73d316d2ced9428b45c06b12fc1. Thanks!

**Comment by erinemay** [comment]
QA 🍰 

- Previewing this theme with [Piwik](https://overlord.ifixit.com/Wiki/SQA_Piwik_Pro_Testing#Section_React_commerce) and [GA4](https://overlord.ifixit.com/Wiki/SQA_GA4_Testing#Section_React_commerce) debug mode turned on via vercel environment variables, I'm still seeing all the same events and event details show up in the respective debug viewers.
- Events I tested include: product-collection search, product page view, cart add, and clicking checkout.
- The only Matomo related traffic I saw in my network tab was due to the name of this branch.

**Review by masonmcelvain — APPROVED** [review]
CR 👏🏻

**Comment by ianrohde** [comment]
un_deploy_block 🟢

**Pull request merged**
