### PR TITLE
Youtube: use lite embed

### PR DESCRIPTION
**Pull request by danielbeardsley**
Youtube iframes slow down a page a suprising amount, many requests, 1MB
of resources, slow JS, ...

A way to combat this is to show the thumbnail and the play button and
only create the iframe when the play button or thumbnail is clicked.

This is the most depended upon package that does this. It's only 3KB
minified+gzipped.

See individual commits for more context

Connect #1015 

Consumes the metafield added here: https://github.com/iFixit/ifixit/pull/45611

### CODE REVIEW

**Review by masonmcelvain — DISMISSED** [review]
CR ✌🏻 Great work!

> Typescript couldn't find the index.d.ts file anymore cause I wasn't importing the main pacakge, but a particular file

I wonder if adding the file to the `include` array of `tsconfig.json` would work. Though you mentioned that you already played with the tsconfig, so you might have tried this already.

**Comment by danielbeardsley** [comment]
>  Though you mentioned that you already played with the tsconfig, so you might have tried this already.

Puzzactly. Though the type definitions aren't *global* in those files, so I don't know how it would have associated it with the later `import` of a specific file in a specific package.

**Comment by erinemay** [comment]
@danielbeardsley should this speed up page load as is or is there a follow up to this? For qa: validate page load is faster, validate the video loads when clicked on, no errors or usability issues...

**Comment by deltuh-vee** [comment]
Is this blocked on https://github.com/iFixit/ifixit/pull/45611 merging first?

**Comment by danielbeardsley** [comment]
> Is this blocked on 45611 merging first?

I don't think so, if the metafield is empty it's just ignored, though it'd be much easier to validate when that pull is merged cause there will be values in it.

**Comment by danielbeardsley** [comment]
> should this speed up page load as is or is there a follow up to this?

This will only affect page load speed on products that have videos by replacing the video with a lite version once the other pull is merged and the products are re-synced.

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Comment by deltuh-vee** [comment]
QA 🎬 
Youtube iframe is only loaded and created after clicking play on the video.

**Pull request merged**
