### PR TITLE
fix(user menu): Fix user menu bugs

### LINKED ISSUE #202: Brief flash of two placeholder avatars on page refresh
### Description
On page reload, there is a brief flash of two different placeholder avatars before the correct one is loaded.

### Screen captures
<details><summary>Video showing avatar load behavior</summary>

https://user-images.githubusercontent.com/72166715/157349796-0fd2f046-871a-460e-abe9-0586aa7459d9.mp4

</details>

Progression of avatars shown on page load:

image

image

image

### LINKED ISSUE #206: Mobile Chrome/FF user menu cut off
On mobile Chrome and FF browsers, the user menu is cut off. Closing it then results in an empty header until page reload.

https://user-images.githubusercontent.com/72166715/157721443-e726089c-950c-4964-9e85-f80e437629ad.mp4

Unable to reproduce this behavior in iOS, but might be due to different macOS/iOS behavior (https://github.com/iFixit/react-commerce/issues/205).

Confirmed in:
Google Pixel 6 - Chrome
Galaxy S21 - Chrome
Galaxy S22 - FF

### PR DESCRIPTION
**Pull request by dhmacs**
fixes #206 
fixes #202 

As discussed on this Slack [thread](https://inkofpixel.slack.com/archives/C01K32B4FPX/p1647276389936719) we're also improving the navigation menu so that it gets easier to show content that goes over the header bar (e.g. user menu).

## QA

1. Visit the Vercel PR preview
2. Visit parts product list page
3. Verify that all of the above bugs are fixed

### CODE REVIEW

**Comment by cdcline** [comment]
CR 👍

**Comment by dshehbaj** [comment]
CR 💯

**Comment by deltuh-vee** [comment]
dev_block ✊ 
My user avatar is no longer loading while logged in.
CleanShot 2022-03-15 at 14 29 29
and the user dropdown menu isn't showing due to https://github.com/iFixit/react-commerce/issues/205 so I'll need to test this once that's fixed.

**Comment by erinemay** [comment]
> dev_block ✊ My user avatar is no longer loading while logged in. and the user dropdown menu isn't showing due to #205 so I'll need to test this once that's fixed.

What device/browsers did you test on?

**Comment by deltuh-vee** [comment]
> What device/browsers did you test on?

I tested this on Chrome(mobile/desktop)

**Comment by dhmacs** [comment]
@danielbeardsley I think you wanted to close this one 👉  https://github.com/iFixit/react-commerce/issues/205

**Comment by dhmacs** [comment]
@deltuh-vee can you test this with plain simple Chrome? (I'm using the latest version and it should work). 
This PR is not trying to solve #205, so if we can successfully test it with the latest version of Chrome I think we can merge it

**Comment by erinemay** [comment]
un_dev_block 🧷 
QA 👍 

- User menu looks good on mobile (desktop unaffected). ✔️ 
- No longer seeing the brief flash of the intermediate user avatar placeholder. ✔️ 

<details><summary>Mobile menu now</summary>

image

</details>

Checked:
- Samsung Galaxy S22 Chrome/FF
- Desktop Chrome (Windows) with narrowed window

**Comment by danielbeardsley** [comment]
> think you wanted to close this one

So sorry!

**Pull request merged**
