### PR TITLE
Log More Info About Unhandled Rejections

### PR DESCRIPTION
**Pull request by danielcliu-ifixit**
## Overview

We are having a ton of unhandledrejections filling up our sentry logs and the info they have for debugging isn't helpful enough to debug what is going wrong. This should add some more errors to our logs, but will at least we should have better/more specific error data.

## QA

Check if unhandled rejections are being sentry logged now. You can trigger an unhandled rejection easily by inserting the following code into the file `_app.js` in `myApp()`

```tsx
   new Promise((resolve, reject) => {
      reject(new Error("This is a custom error"));
    });      
``` 

Connects: #1913

### CODE REVIEW

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Comment by erinemay** [comment]
QA 👍 I'm seeing an extra Sentry event when applying that diff on this branch. 

On main, I'm getting [this one](https://ifixit.sentry.io/issues/4475818684/?environment=dev&environment=development&environment=test&environment=testing&environment=vercel-%22development%22&environment=vercel-development&environment=vercel-preview&project=6475315&query=&referrer=issue-stream&statsPeriod=14d&stream_index=0)


On this branch, I'm getting these two: [Sentry link 1](https://ifixit.sentry.io/issues/4475819187/?environment=dev&environment=development&environment=test&environment=testing&environment=vercel-%22development%22&environment=vercel-development&environment=vercel-preview&query=&referrer=issue-stream&statsPeriod=14d&stream_index=0), [Sentry link 2](https://ifixit.sentry.io/issues/4475818972/?environment=dev&environment=development&environment=test&environment=testing&environment=vercel-%22development%22&environment=vercel-development&environment=vercel-preview&query=&referrer=issue-stream&statsPeriod=14d&stream_index=1)

@danielcliu-ifixit deploy_block 🌵 un block if these look like the info you want

**Comment by danielcliu-ifixit** [comment]
un_deploy_block :v:

**Comment by danielcliu-ifixit** [comment]
Likely related errors now being logged
https://ifixit.sentry.io/issues/4240611515/?project=6469069&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=3

possibly related

https://ifixit.sentry.io/issues/4240611515/?project=6469069&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=3
https://ifixit.sentry.io/issues/4477070431/?project=6469069&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=2
https://ifixit.sentry.io/issues/4357907729/?project=6469069&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=17
https://ifixit.sentry.io/issues/4477955114/?project=6469069&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=8

Etc. It is difficult to pinpoint what is going wrong

**Pull request merged**
