### PR TITLE
iFixit Api: use new minimal device api

### PR DESCRIPTION
**Pull request by danielbeardsley**
Uses the API from https://github.com/iFixit/ifixit/pull/43908

Connect #379

### CODE REVIEW

**Comment by davidrans** [comment]
dev_block :hand:

**Comment by sterlinghirsh** [comment]
I wonder if there's an issue with whitelisting this api on cominor.

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :dog: through 6693ae2
Looks reasonable, although I certainly don't know if it'll still provide all the data we need.

**Comment by sterlinghirsh** [comment]
Closing in favor of https://github.com/iFixit/react-commerce/pull/491

**Pull request closed without merging**
