### PR TITLE
Extended Related Problems: Switch feature flag to true

### PR DESCRIPTION
**Pull request by andyg0808**
Does what it says on the tin.

## QA Notes
This should now include problems from the parent device, along with any ancestor devices which have inheritance enabled. Please see the issue for the precise spec; if you find anything wonky, please let me know!

Connects https://github.com/iFixit/ifixit/issues/50604

### CODE REVIEW

**Review by ianrohde — APPROVED** [review]
CR ⚪ 

Should we remove the old version function?

**Comment by andyg0808** [comment]
@ianrohde Yes, but I was thinking of doing that in a future PR, so this could be as little change as possible.

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by deltuh-vee** [comment]
The issue mentions
> Target N "Related Problems" on the problem page.

Is there a specific number for this?

**Comment by deltuh-vee** [comment]
dev_block ✊ 
This troubleshooting page I created has a circular reference back to itself:
CleanShot 2023-12-22 at 13 14 07
Troubleshooting page: https://react-commerce-git-extended-related-problems-release-ifixit.vercel.app/Troubleshooting/Test_Device_2/test+troubleshooting/536566
Device page: https://www.cominor.com/Device/Test_Device_2

**Comment by andyg0808** [comment]
@deltuh-vee Interesting. That definitely seems like a blocker. I'll work on keeping these cleaner in the new year.

**Comment by andyg0808** [comment]
Okay, @deltuh-vee I think that's fixed. un_dev_block :+1:

**Comment by deltuh-vee** [comment]
QA 🎬
- Related pages pulls from direct links to /Troubleshooting in the page text first, followed by directly linked Related Problems.
- If there are fewer than 6 problems to pull from, Related Pages pulls from problems related to the same device. If inheritance is enabled, problems are pulled from ancestor devices.
- Problems from each device are sorted by view count descending.
- When pulling from indirectly linked problems, a maximum of 6 problems total will be shown.
- When there are more than 6 problems that are directly linked, all of the directly linked problems are shown.

**Pull request merged**
