### PR TITLE
Troubleshooting: Add "Related Problems" section

### PR DESCRIPTION
**Pull request by andyg0808**
This pull adds a "Related Problems" section to the bottom of each troubleshooting page. It contains all the problems which have been linked from the current page.

### CODE REVIEW

**Review by ianrohde — APPROVED** [review]
CR ⚪ _(only slightly biased 😁)_

**Comment by deltuh-vee** [comment]
QA 🎬 
Related problems section is present.
❓ I think the font looks a little off.
image

**Comment by ianrohde** [comment]
> ❓ I think the font looks a little off. Will that be fixed here or elsewhere?

@deltuh-vee what browser and OS was this on?

**Comment by ianrohde** [comment]
@deltuh-vee https://github.com/iFixit/react-commerce/pull/1730/commits/dcef46a9d055ee3018984954191b7c59cc45f418 fixes the issue

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by deltuh-vee** [comment]
QA 🎬
Font looks fixed now.

**Pull request merged**
