### PR TITLE
Add Zod product schema

### PR DESCRIPTION
**Pull request by dhmacs**
Related to #1156 

This adds a Zod validation schema to the product model. This schema later will be used to validate cached products to make sure the cache entry is valid.

## QA

Perform a smoke test of the product page

### CODE REVIEW

**Review by masonmcelvain — DISMISSED** [review]
CR ✌🏻 Nice!

**Comment by erinemay** [comment]
dev_block 🧷 Everything looks and works the same except for discount/sale prices. 

https://react-commerce-git-add-product-zod-schema-ifixit.vercel.app/products/Fix-the-World-Sticker ⬇️ 

image


https://react-commerce.vercel.app/products/Fix-the-World-Sticker ⬇️ 
image


Steps/notes:
- Checked most products in our list of [sample/edge case product list](https://docs.google.com/spreadsheets/d/1Jx0HSfwEeu3VGc8Ylv61LTlAmWoKHyhDF0NTc3sva8M/edit#gid=1996972818)
- Compared visually - pages looked identical
- Compared functionally - clicked on all the checkboxes and dropdowns
- Checked on desktop mac and windows and mobile. 
- Checked as a regular user and pro user (pro discounts are showing up just fine)

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by dhmacs** [comment]
un_dev_block 🟢 Thanks @erinemay, should be fixed now 👍

**Comment by k0rvusk0r4x** [comment]
- Issue noted [here](https://github.com/iFixit/react-commerce/pull/1277#issuecomment-1400854196) is gone.
- Otherwise, continues to look good.

QA 😺

**Pull request merged**
