### PR TITLE
Configure more specific name for backend

### PR DESCRIPTION
**Pull request by andyg0808**
## Description
This restores the package name for the backend package from before the refactor.

qa_req 0

### CODE REVIEW

**Review by dhmacs — APPROVED** [review]
CR 👍

**Comment by jarstelfox** [comment]
CR 🌵

**Comment by erinemay** [comment]
Hey, @andyg0808, are there any expected behavioral changes to the [collection pages](https://react-commerce-git-backend-restore-name-ifixit.vercel.app/) from this change?

**Comment by andyg0808** [comment]
@erinemay Nope!

**Pull request merged**
