### PR TITLE
Add store home page hero section

### LINKED ISSUE #813: Add store home page hero section
See [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=1923%3A8386) for details

Screenshot 2022-10-11 at 16 13 02

### PR DESCRIPTION
**Pull request by dhmacs**
closes #813 

## QA

1. Open Vercel preview
2. Visit [`/Store2`](https://react-commerce-git-add-store-home-page-hero-section-ifixit.vercel.app/Store2)
3. Verify that hero section is implemented as specified in #813 

## Post merge

This PR adds a new content type and a fix to gracefully handle missing content types on the remote server when seeding, so after having merged this we need to migrate the Strapi live server

cc @sterlinghirsh

### CODE REVIEW

**Comment by deltuh-vee** [comment]
QA 🎬 
Hero section is implemented according to the [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=1923%3A8342).

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by dhmacs** [comment]
carry over QA 🐎

**Comment by dhmacs** [comment]
cc @sterlinghirsh now that this is merged let's migrate the Strapi production server too

**Pull request merged**
