### PR TITLE
Add Strapi components for header

### PR DESCRIPTION
**Pull request by dhmacs**
## Changelog

- Adds submenu menu component
- Adds header slot in store content type
- Adds seed data for header
- Minor frontend adaptations to account for content type changes

## QA

> 👀   This PR contains changes to Strapi config. Since the new Strapi staging server is not ready yet, we need to test this locally. The current Strapi server will be manually updated when this PR merged

1. Clone this repo
2. Make sure you are running on node v14 (if you are using nvm run `nvm use` in the project working directory)
3. Install dependencies `npm install`
4. Rename `backend/.env.example` to `backend/.env` (this will enable db seed)
5. Run dev server: `npm run dev`
6. Verify that the seed script runs correctly. If it does you should see the following messages on your terminal:
    Screenshot 2021-12-01 at 12 03 06 
7. Log into local Strapi instance (http://localhost:1337/admin) with email `strapi@ifixit.com` and password `Password1`
8. Verify that a US store exists
9. Verify that US store has the header menu field set to "US Main"
10. Verify that menu "US Main" contains 3 submenus
11. Visit Vercel preview a verify that collection page still works

### CODE REVIEW

**Comment by deltuh-vee** [comment]
dev_block ✊ 
Looks like the header field is empty
CleanShot 2021-12-01 at 11 23 33

**Comment by dhmacs** [comment]
@deltuh-vee can you print what's on your terminal? (step 6)

> ⚠️ Delete your db under `/backend/.tmp/data.db` to make sure you start from scratch

**Comment by deltuh-vee** [comment]
Here's the output:
[output.txt](https://github.com/iFixit/react-commerce/files/7637511/output.txt)

**Comment by dhmacs** [comment]
@deltuh-vee The output looks fine. I've done a clean install on another computer but I'm unable to reproduce the issue.. Can you try to delete the repo and clone it again? Perhaps if you record your steps I can get some insights on what's wrong

**Comment by dhmacs** [comment]
@deltuh-vee 
> deploy_block ❓ @dhmacs US Main has a few more than three sub menu options, is that OK? CleanShot 2021-12-02 at 09 44 43

This is a dropdown to select the menu to be used in the header. To see what that menu looks like, you have to click the **"Details"** link. You'll be redirected to the "US Main" menu page, that should look like this:

image

**Comment by GrantMatejka** [comment]
CR 🌽

**Comment by zdmitchell** [comment]
CR 🎸

**Comment by deltuh-vee** [comment]
un_deploy_block 👍

**Pull request merged**
