### PR TITLE
Add TikTok to footer

### PR DESCRIPTION
**Pull request by jordycosta**
### Overview:

socials

---

### Changes Made:
1. Added a TikTok SVG from [FontAwesome](https://fontawesome.com/icons/tiktok)
2. Added TikTok-related fields to **SocialMediaAccounts**

---
>### CR/QA Notes:
>
> **CR**: Review to https://github.com/iFixit/react-commerce/pull/905/commits/f03f53c828f1f6afd9ee5e12b4b52d8c3f917193
>
>**QA**:
>
>1. Navigate to [the Vercel preview](https://react-commerce-prod-d2x5n7xld-ifixit.vercel.app/)
>2. Check that **TikTok** is in the footer
>3. Ensure it links to our social media page
>
---

cr_req 2
Connects #44933

### CODE REVIEW

**Comment by jordycosta** [comment]
deploy_block 🟨 

https://github.com/iFixit/react-commerce/pull/926

**Comment by jordycosta** [comment]
un_deploy_block 🟩 

https://github.com/iFixit/react-commerce/pull/926 is merged 👍

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by deltuh-vee** [comment]
QA 🎬 
Tiktok icon is in the footer and links to our Tiktok account.

**Pull request merged**
