### PR TITLE
Avoid including the whole lodash

### PR DESCRIPTION
**Pull request by federicobadini**
connects #105 
connects #1015

Curly braces import implies including the whole lib (see [here](https://www.blazemeter.com/blog/import-lodash-libraries))

### CODE REVIEW

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 So interesting!

It would be nice to add a custom ESLint rule to forbid the curly syntax for lodash specifcally. I have a feeling future devs will not be aware of/forget about this pitfall.

**Comment by masonmcelvain** [comment]
(But, way beyond the scope of this PR. Not asking for you to implement that here.)

**Comment by federicobadini** [comment]
I can definitely add that here too

**Review by davidrans — APPROVED** [review]
CR :coffee:

**Comment by danielbeardsley** [comment]
CR :+1: --  [Same commit](https://github.com/iFixit/react-commerce/pull/1092/commits/7ef569cabbd0fcb37266972c24a5e4cbee13b729) I did in my other pull, but let's merge this by itself.

**Comment by davidrans** [comment]
We can add the eslint rule in a followup pull

**Pull request merged**
