### PR TITLE
Remove buggy input price

### PR DESCRIPTION
**Pull request by dhmacs**
~~🚨 Blocked by #332 deploy_block~~

This PR removes the buggy input price. Eventually we'll come up with something better and fix it.

## QA

1. Visit the Vercel PR preview (replace vercel.app with cominor.com)
2. Verify that we show the price range facet values without the the min and max price range input

### CODE REVIEW

**Comment by dhmacs** [comment]
dev_block 🚫 on removing tests for the max and input fields

**Comment by dhmacs** [comment]
Tests have been removed

un_dev_block 🟢

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by danielbeardsley** [comment]
CR :+1:

**Comment by danielbeardsley** [comment]
QA :+1:

**Pull request merged**
