### PR TITLE
Hide out of stock alerts from product cards

### LINKED ISSUE #218: Hide out of stock alerts from product cards
### Context:
Having "Sold out" on the product cards is a deterrent to getting users to visit the product page and have access to the "Notify Me" button. 

### To do:
Remove the `Sold Out` flare and "Out of Stock" note from product cards where the product is out of stock.
image

CC: @jeffsnyder

### PR DESCRIPTION
**Pull request by dhmacs**
fixes #218   

## QA

1. Visit the Vercel PR preview (replace `vercel.app` with `cominor.com`)
2. Visit all parts product list 
3. Verify that out of stock alerts are not visible anymore

### CODE REVIEW

**Review by davidrans — APPROVED** [review]
CR :coffee:

**Comment by deltuh-vee** [comment]
QA 🎬 
Out of stock alerts are no longer visible.

**Comment by danielbeardsley** [comment]
CR :+1:

**Comment by danielbeardsley** [comment]
CR :+1:

**Pull request merged**
