### PR TITLE
Hotfix: Install dependencies with pnpm 7

### PR DESCRIPTION
**Pull request by masonmcelvain**
We think that we accidentally installed dependencies with pnpm 6 in #747.

### CODE REVIEW

**Comment by danielcliu-ifixit** [comment]
CR :v:

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Comment by masonmcelvain** [comment]
Resolved https://sentry.io/share/issue/52136ebe1d124c91b40c29f0dcf752a7/

**Comment by dhmacs** [comment]
@masonmcelvain I didn't realize the switch to pnpm 7 was merged, sorry about that!

**Comment by masonmcelvain** [comment]
No worries! I didn't catch it in CR either, it was an easy mistake to make. Definitely something CI should have caught, @sterlinghirsh made a couple issues: https://github.com/iFixit/react-commerce/issues/754, https://github.com/iFixit/react-commerce/issues/753

**Pull request merged**
