### PR TITLE
Troubleshooting: Add styling to links

### PR DESCRIPTION
**Pull request by andyg0808**
This makes links the blue color shown in the mockup.

## QA Notes
Try https://react-commerce-git-vulcan-add-link-style-ifixit.vercel.app/Vulcan/troubleshooting-test as a page which should include a link.

Closes https://github.com/iFixit/ifixit/issues/46334

### CODE REVIEW

**Comment by andyg0808** [comment]
deploy_block :+1: on https://github.com/iFixit/react-commerce/pull/1306

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by andyg0808** [comment]
Sorry for the force-push; had the wrong branch checked out and accidentally pushed here instead of the grandparent pull.

**Comment by andyg0808** [comment]
un_deploy_block :+1: 
https://github.com/iFixit/react-commerce/pull/1306 went out.

**Review by jarstelfox — DISMISSED** [review]
CR 🌵

**Comment by erinemay** [comment]
>https://react-commerce-git-vulcan-add-link-style-ifixit.vercel.app/Vulcan/troubleshooting-test

love this ☝️ 

QA 👍 Links are blue like the mockup ✔️ 

deploy_block ❔ @andyg0808, this might be out of scope here, but I'd expect them to be underlined on hover. Are you defining hover behavior in this pull?

**Comment by andyg0808** [comment]
un_deploy_block :+1: 
@erinemay Thanks for catching the missing hover style! That should be fixed now.

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by erinemay** [comment]
Looks good. QA 👍

**Pull request merged**
