### PR TITLE
Improve separation between server and client code

### PR DESCRIPTION
**Pull request by dhmacs**
This is the first of a series of PRs that aim at improving overall site performance (#1156). Here we just refactor a little bit the code so that Next.js knows what code belongs to `getServerSideProps` and what code belongs to the page component. There are more things to do than these changes, but I'm trying to constraint the size of the PR so we can hopefully review it faster.

## QA

This change are basically splitting code into different files. To QA this I'd just perform a smoke test on product list pages and product pages to verify that these pages are still working.

### CODE REVIEW

**Comment by danielbeardsley** [comment]
This looks great!

I'm a little confused though and can't tell if this is on purpose or not. `templates/product-list/index.tsx` is nearly identical to `templates/ProductListView.tsx`. Like 10 lines different out of more than 100 lines total. Seems like we meant to switch from one to the other but forgot to finish the transition?

**Review by danielbeardsley — APPROVED** [review]
CR :+1: 

Nice!

**Comment by dhmacs** [comment]
un_dev_block 👍

**Comment by erinemay** [comment]
Checked desktop and mobile:

Product:
- Breadcrumbs
- Images (carrousel/zoom)
- Ratings/reviews
- Price
- Changing details with changing variants
- Add to cart
- OOS experience
- Shipping restrictions
- OEM badges
- Guides
- Compatibility
- Frequently bought together
- checkout

Checked [edge case guides](https://docs.google.com/spreadsheets/d/1Jx0HSfwEeu3VGc8Ylv61LTlAmWoKHyhDF0NTc3sva8M/edit?usp=sharing)

Product list:
- Filters
- Product cards
- Item type collections
- Search
- List view/tile view
- Breadcrumbs
- Footer/header
- /Parts and /Tools
- Nested collections
- mini cart
- checkout

General:
- Using back button
- Viewing pages and checking out as a pro
- Spot checked on Windows+Chrome, Android+Chrome, MacOS+Safari, iOS+Safari
- No new errors

qa 🚀

**Pull request merged**
