### PR TITLE
Refactor product grid item

### LINKED ISSUE #107: Refactor product list grid view

### PR DESCRIPTION
**Pull request by dhmacs**
This PR closes #107 

## Changelog

- Refactors product grid according to new design
- Adds links to product pages

## QA

1. Visit the Vercel PR preview
2. Visit the parts product list page
3. Verify that product grid new design adheres to [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit-Shopify-Working-Files?node-id=1528%3A6374)
4. Verify that product grid items link to product pages

### CODE REVIEW

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by ardelato** [comment]
QA 👍 

| Before vs. After	|
|:---:|
|Before After	|

## Steps Taken:
1. Checked out the Vercel preview
2. Then clicked on the Parts collection
3. I switched view from `List` to `Grid` 
4. I confirmed for the most part that `Grid` items matched the Figma design -- couldn't find any products that were on sale   
   Sold Out matches
5. I also confirmed that products now linked to their respective product pages
6. I confirmed that the SEO issues noted in https://github.com/iFixit/react-commerce/pull/121#issuecomment-961248503 were addressed
   -  [x] product titles are now **`h3`** 
   -  [x] product cards are now using **`article`** tags

**Comment by zdmitchell** [comment]
CR 🎸

**Comment by evannoronha** [comment]
CR 🔥

**Pull request merged**
