### PR TITLE
Vulcan Products: Update type to the result of the new api param

### PR DESCRIPTION
**Pull request by jarstelfox**
qa_req 0
Connects: https://github.com/iFixit/ifixit/pull/48641
Connects: https://github.com/iFixit/ifixit/issues/48101

### CODE REVIEW

**Comment by jarstelfox** [comment]
deploy_block 🌵 on https://github.com/iFixit/ifixit/pull/48641

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by jarstelfox** [comment]
un_deploy_block 🌵 https://github.com/iFixit/ifixit/pull/48641 went out

**Comment by jarstelfox** [comment]
deploy_block 🌵

**Comment by jarstelfox** [comment]
un_deploy_block 🌵 https://github.com/iFixit/ifixit/pull/48658 was shipped

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Pull request merged**
