### PR TITLE
Vulcan: Mark guide image data as optional

### PR DESCRIPTION
**Pull request by andyg0808**
Turns out that there might not be an image for a guide. This handles that case.

## QA Notes
1. Create a guide with no image (e.g., a new guide; make sure it's published).
2. Link the guide from a troubleshooting solution
3. Check that the page doesn't 500.

Here's an example that I've already put together:
https://react-commerce-git-troubleshooting-fix-500-on-noi-902ded-ifixit.vercel.app/Vulcan/imageless-guide-link

Closes https://github.com/iFixit/ifixit/issues/48470

### CODE REVIEW

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by andyg0808** [comment]
Blocked on https://github.com/iFixit/react-commerce/pull/1778 going out, because the no-image guide I created exposed a bug where we were crashing due to a missing heading value.

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by jarstelfox** [comment]
dev_block 🌵 I changed to a new guide type on master. The change here has no effect.

https://github.com/iFixit/react-commerce/blob/10cce00eb3f182e4ce7a621eb0fdfa8ac4b7ad1b/frontend/templates/troubleshooting/Resource.tsx#L23

Sorry for the merge conflict.

**Comment by andyg0808** [comment]
Thanks, @jarstelfox! Your change fixes https://github.com/iFixit/ifixit/issues/48470 in the current `main` version, so I'll just close it.

**Comment by jarstelfox** [comment]
Minor: Do we use the old guide type? If not, we probably should remove it

**Pull request closed without merging**
