### PR TITLE
Troubleshooting: Add meta title, description, keywords

### PR DESCRIPTION
**Pull request by jyee27**
These should match the `<meta>` tags on `/Wiki`.

Closes: https://github.com/ifixit/ifixit/issues/46901

### CODE REVIEW

**Comment by deltuh-vee** [comment]
dev_block ✊ 
image
@andyg0808 did you ever figure out what was causing these errors in https://github.com/iFixit/react-commerce/pull/1427?

**Comment by deltuh-vee** [comment]
QA 🎬 
The meta description and keywords match the ones on /Wiki.
❓ The title is different between the react-commerce page and the one on /Wiki
image
image
but the meta title tag does match the title on the Vulcan page.

**Comment by jyee27** [comment]
> The title is different between the react-commerce page and the one on /Wiki

It looks like the logic for that on /Wiki is to use the `display_title` and fall back to the `title`. @andyg0808 are we going to add the `display_title` to the troubleshooting API?

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by andyg0808** [comment]
@jyee27 Oh! That looks like a bug; I think I just didn't realize that we'd of course want the `display_title` not the `title`. Issue created: https://github.com/iFixit/ifixit/issues/46949

**Pull request merged**
