### PR TITLE
Reduce mobile product list excessive whitespace

### LINKED ISSUE #241: Excessive whitespace in mobile product list
On mobile, the product list view has a lot of whitespace.

| Amazon  | ebay  | Alibaba  | iFixit collection  |
| ------------- | ------------- | ------------- | ------------- |
| image  | image | image | image |

### PR DESCRIPTION
**Pull request by dhmacs**
fixes #241 
 
## Changelog

- Improve responsive styles for product list view

## QA

1. Visit the Vercel PR preview (replace vercel.app with cominor.com) 
2. Navigate to `/Store/Parts`
3. Verify that the problem described by #241 is fixed

cc @erinemay

### CODE REVIEW

**Review by bhuminson — APPROVED** [review]
CR :dagger:

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by dhmacs** [comment]
@erinemay let me know what you think of the latest changes

**Comment by erinemay** [comment]
QA 🎈 un_deploy_block 👍 
Yeah, that made a big difference! Thank you @dhmacs!!

This looks good, and it's still easy to tell the difference between cards on mobile devices. Sale prices and flair still look good.

| before | earlier commit | current commit |
| ------------- | ------------- | ------------- |
| image | image | image |

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by lithobraking** [comment]
CR ✨ 

looks good!

**Pull request merged**
