### PR TITLE
Fix broken fast refresh

### PR DESCRIPTION
**Pull request by dhmacs**
#348 broke [Fast Refresh](https://nextjs.org/docs/basic-features/fast-refresh), so here I'm proposing to drop `withUniversalOptimization` to fix it. This [comment](https://github.com/vercel/next.js/issues/8956#issuecomment-557871585) from Next.js core member says:

```
Minification is disabled by default for serverless bundles as it significantly increases 
build times and doesn't give any significant benefits when deploying serverless bundles.
```

@andyg0808 do you have better insights about this? 

## Changelog

1. Fix fast refresh
2. Update readme to reflect new dependencies install requirements

## QA

1. Clone the process locally
3. Install dependencies
4. Run dev server
5. Try to change a component and verify that you can see changes applied in the browser almost instantly (less than 1 sec)

### CODE REVIEW

**Comment by andyg0808** [comment]
CR :dog: through 5feefe
I'm fine with this, because I'm guessing it's holding up development, and it shouldn't currently be essential to performance. But I'd also like to know why it broke fast refresh eventually, because without it, the server-side bundle includes, like, _all_ the icons from the combined icon set we're using (it's like multiple megabytes of JS), and I'd rather drop the ones we don't need.

**Review by andyg0808 — APPROVED** [review]

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I'm unable to finish running `pnpm install:all`
CleanShot 2022-07-25 at 11 12 40

**Comment by federicobadini** [comment]
> CR 🐶 through [5feefed](https://github.com/iFixit/react-commerce/commit/5feefed41d19583753bd747a1912daa8ba41b809) I'm fine with this, because I'm guessing it's holding up development, and it shouldn't currently be essential to performance. But I'd also like to know why it broke fast refresh eventually, because without it, the server-side bundle includes, like, _all_ the icons from the combined icon set we're using (it's like multiple megabytes of JS), and I'd rather drop the ones we don't need.

It was "breaking" fast refresh because it was applying minification even during development on every file save.

However Next v.12 has radically changed the way in which it deals with dependencies during compilation: 
the `target` option itself has been deprecated and a new [dependency tracing util](https://github.com/vercel/nft) has been introduced.

I'm confident that just upgrading to v.12 will resolve the problem that inspired #348 without any webpack tuning on our side.

Here some reference:

- [Target option deprecation](https://nextjs.org/docs/upgrading#target-option-deprecated)
- [New dependency tracing approach](https://nextjs.org/docs/advanced-features/output-file-tracing)

**Comment by sterlinghirsh** [comment]
CR :zap: secondary un_dev_block :zap: @deltuh-vee I think you ran into a problem with missing an auth token for NPM. @danielcliu-ifixit just dealt with it so he should be able to help if you can't figure it out.

**Comment by deltuh-vee** [comment]
>I'm confident that just upgrading to v.12 will resolve the problem that inspired https://github.com/iFixit/react-commerce/pull/348 without any webpack tuning on our side.

Do we still need this pull?

**Comment by sterlinghirsh** [comment]
I think until we update to next 12 then yes

**Comment by deltuh-vee** [comment]
QA 🎬 
Changes to components are instantly applied.

**Comment by danielbeardsley** [comment]
If this was making development slow, why didn't we disable optimization in development?

> Minification is disabled by default for serverless bundles as it significantly increases 
build times and doesn't give any significant benefits when deploying serverless bundles.

I'm sure this core member was talking about *minification* (i.e. variable renaming, whitespace removal, ...), but tree-shaking is done too and we can easy measure its affect on bundle size.

**Comment by andyg0808** [comment]
I believe I saw a _massive_ effect on bundle size: I think it went from ~2MB to a few hundred KB. I don't find the team member's argument convincing (I saw that post before I made the original change), but I also can't prove that tree shaking actually makes a meaningful difference on the server.

**Comment by danielbeardsley** [comment]
> but I also can't prove that tree shaking actually makes a meaningful difference on the server.

We can prove that the bundle size decreases, but proving a reduction in cold-start-time is harder and definitely not a given.

**Pull request merged**
