### PR TITLE
Fix type errors in `@ifixit/ui`

### PR DESCRIPTION
**Pull request by masonmcelvain**
Reverts iFixit/react-commerce#750

Reintroduces changes from https://github.com/iFixit/react-commerce/pull/738

## QA

Do a quick browse of the site, and make sure images load as usual and there are no new console errors related to images.

@hcutrone @ardelato

### CODE REVIEW

**Comment by jordycosta** [comment]
dev_block 🟥 
Running into a 500: INTERNAL_SERVER_ERROR on both previews

**Comment by masonmcelvain** [comment]
un_dev_block ✌🏻 Thanks @jordycosta, this branch was out of date with main. Should be fixed now.

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Comment by jordycosta** [comment]
QA 🟢 

Images continue to load, with no errors regarding images are shown in the console ✔️ 

Tested via [`react-commerce-prod`](https://react-commerce-prod-git-revert-750-revert-738-fix-db82d6-ifixit.vercel.app/)

**Pull request merged**
