### PR TITLE
Update Chakra to v1.8.3

### LINKED ISSUE #171: Upgrade Framer motion and Chakra

### PR DESCRIPTION
**Pull request by dhmacs**
closes #171 

This PR updates Chakra so that we can make use of up to date frame motion for animations in the upcoming new store home page.

> **Note**: The are also a couple of minor changes that have been attached to this PR as detailed in the changelog below

## Changelog

- Update Chakra and a few related packages
- Refactor code to fix warnings due to updated dependencies
- Mention use of NVM in readme
- Remove default JWT secret from Strapi Admin config: This is to prevent us from relying on a token stored in version control

## QA

1. Visit the Vercel PR preview
2. Visit parts product list page
3. Verify that the product list page still work

### CODE REVIEW

**Comment by erinemay** [comment]
QA 👍 
- [Vercel preview](https://react-commerce-git-update-dependencies-ifixit.vercel.app/store/parts) appears and behaves the same as [master](https://react-commerce.vercel.app/store/parts) (filters, parts models buttons, news stories, header, footer)
- No new errors on page

Note:
I noticed a bug in the accessibility highlighting of the breadcrumbs, but it's present on the master branch so I'll write up a separate issue. 
image

**Comment by ianrohde** [comment]
@dhmacs, I'm not a fan of NVM's need to manually define the node version. It can lead to unnecessary confusion. Have you seen (or used) Volta? https://docs.volta.sh/guide/

**Review by ianrohde — COMMENTED** [review]
CR ⚪ 

IIRC, Chakra 1.8.x also added types! 🎉

**Comment by dhmacs** [comment]
> @dhmacs, I'm not a fan of NVM's need to manually define the node version. It can lead to unnecessary confusion. 

What do you mean by "manually define"? Thanks to the `.nvmrc` file you just need to type `nvm use` and it'll correctly pick up the right version.
You can also add a zsh/bash script to do that automatically for you whenever you switch a project: https://github.com/nvm-sh/nvm#calling-nvm-use-automatically-in-a-directory-with-a-nvmrc-file

> Have you seen (or used) Volta? https://docs.volta.sh/guide/

Never heard about it but looks nice 👍 It seems to work quite similar to NVM, but requires less config.. Maybe we can open another PR to switch to it

**Review by evannoronha — APPROVED** [review]
CR 🔥

**Pull request merged**
