### PR TITLE
Revert back to original header logo

### PR DESCRIPTION
**Pull request by jordycosta**
### Overview:

original-blue

The original blue iFixit logo 🔵 is replacing the UA logo 🇺🇦 

---

### Changes Made:
1. Reverted https://github.com/iFixit/react-commerce/pull/563

---

### CR/QA Notes:

>**CR**: Review to https://github.com/iFixit/react-commerce/pull/676/commits/317e29996f9b2e1b493174646aab5b0eb7cafc9f

>**QA**:
>
>1. Navigate to [`revert-ua-logo`](https://react-commerce-prod-git-revert-ua-logo-ifixit.vercel.app/Parts)
>2. Ensure that the header logo is as shown above on /Parts and /Tools

---

cr_req 2
Connects [#444](https://github.com/iFixit/ifixit/issues/44461)

### CODE REVIEW

**Comment by jordycosta** [comment]
deploy_block 🟨 

Once this is ready, we can merge https://github.com/iFixit/ifixit/pull/44463 at the same time

**Comment by k0rvusk0r4x** [comment]
The logo is, indeed, reverted to blue.

QA 😺

**Review by hcutrone — COMMENTED** [review]
CR :burrito:

**Review by sumukhipandey — APPROVED** [review]
CR 🦋

**Comment by jordycosta** [comment]
un_deploy_block 🟩 

Merge with https://github.com/iFixit/ifixit/pull/44463

**Pull request merged**
