### PR TITLE
Troubleshooting: Add nav tabs

### PR DESCRIPTION
**Pull request by andyg0808**
Both these URLs may be missing if there's not a sensible place to link to, so this will disable the tab if there's no URL for it.

## QA Notes
Please confirm that the tabs look reasonable and link to the appropriate places.

Example URL which should have both a Parts and a Guide link:
https://react-commerce-git-vulcan-add-area-links-ifixit.vercel.app/Vulcan/iPhone_Won't_Turn_On
Example URL which should have a working Guide link and a disabled Parts link:
https://react-commerce-git-vulcan-add-area-links-ifixit.vercel.app/Vulcan/Washing_Machine_Not_Spinning
Example URL which should have both a disabled Guide link and a disabled Parts link:
https://react-commerce-git-vulcan-add-area-links-ifixit.vercel.app/Vulcan/troubleshooting-test

Closes iFixit/ifixit#46652

### CODE REVIEW

**Comment by andyg0808** [comment]
deploy_block :+1: on https://github.com/iFixit/ifixit/pull/46654 (which is the API changes this needs).

**Review by jarstelfox — APPROVED** [review]
CR 🌵 Did you copy pasta from [here](https://github.com/iFixit/ifixit/blob/cea967b8d0b57e789fdafc070c244c688be9446e/carpenter-frontend/Guide/Guide/GuideProducts/GuideNav.tsx#L101)?

**Comment by k0rvusk0r4x** [comment]
While the tabs look reasonable, they are disabled, and hovering over them does not show a preview link. 
image

dev_block 😿

**Comment by andyg0808** [comment]
@jarstelfox Yes.
@k0rvusk0r4x Sorry, yeah. They're disabled until https://github.com/iFixit/ifixit/pull/46654 goes out; I'd wanted to allow CR on this before then, but I forgot that QA would also try to look at it.

**Comment by andyg0808** [comment]
un_deploy_block :+1:

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by deltuh-vee** [comment]
QA 🎬 
The tabs look fine and have appropriate links.

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Pull request merged**
