### PR TITLE
Revert "Noindex dev domains via middleware"

### PR DESCRIPTION
**Pull request by masonmcelvain**
Reverts iFixit/react-commerce#771

This is noindexing www.ifixit.com/Parts, yikes!

image

### CODE REVIEW

**Comment by masonmcelvain** [comment]
QA ✌🏻 the previews are still noindexed

**Comment by sctice-ifixit** [comment]
CR :flags:

**Review by sterlinghirsh — APPROVED** [review]

**Comment by danielcliu-ifixit** [comment]
Is this because the `react-commerce` app is a different host or something?

**Comment by masonmcelvain** [comment]
I'm not sure what went wrong. I'm debugging it in #779 if you wanna follow along there.

**Pull request merged**
