### PR TITLE
Logs: add colorless option

### PR DESCRIPTION
**Pull request by danielbeardsley**
### Problem: (logs can't be parsed from these `[m33` lines)
image

### With Env variable
image

### CODE REVIEW

**Comment by danielbeardsley** [comment]
QA :+1: 

Colors still show in dev when the env var isn't set:
image

**Comment by danielbeardsley** [comment]
QA :+1: 

With colors
image

without
image

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Review by danielcliu-ifixit — APPROVED** [review]
CR :v:

**Pull request merged**
