### PR TITLE
Fix product list bugs

### LINKED ISSUE #175: Bug: Accessibility button border cut off in device breadcrumbs
### Description:
When a user has stepped into a child part category and clicks on the the `All Parts` breadcrumb, the accessibility border is cut off. 
image

### Steps to repro:

1. Go to https://react-commerce.vercel.app/store/parts
2. Click on any of the parts under `Choose a model of All Parts`
3. Click on the `All Parts` button to return to that page and observe that behavior.

### Additional context:
Doesn't appear to be present in Safari, but is present in Chrome and FF on Windows and MacOS

### LINKED ISSUE #193: In Stock can have a negative value
The lowest value for "in stock" should be 0. 
CleanShot 2022-03-08 at 11 48 44

### LINKED ISSUE #195: On Sale items have the same regular price
The regular price for on sale items is the same as their sale price. I would expect the regular price to be higher.
CleanShot 2022-03-08 at 13 15 39

### LINKED ISSUE #196: Parts Page: no zoom in/out or scrolling for product filters (mobile)
## Overview:

When on the parts page on mobile, I am unable to pinch to zoom in/out or scroll horizontally/vertically while on the `Filters` UI

If the user is zoomed in before they use the filters feature, the filters UI will display based on how much the user was already zoomed in. This becomes an issue if the user is unable to zoom out by leaving them unable to close the filters and navigate the page further. Any sort of filter that requires the user to enter a custom value _(e.g. price range)_ will also zoom in the UI; leaving it more difficult to navigate since the pinch to zoom or horizontal/vertical scroll has not been implemented.

### Device Information:
iOS > iPhone SE _(2nd gen)_

---

### Screen Captures:

https://user-images.githubusercontent.com/95656772/157328621-5dfb3271-9b57-41a0-b1ee-ab5b3a8c413a.MP4

https://user-images.githubusercontent.com/95656772/157328723-c1bd7845-9f59-4a84-90c9-fd9a711d0dca.MP4

### LINKED ISSUE #197: Mobile collection page description section slightly too small for our standard copy
### Description
Our text-description on /parts and /tools is just too long to fit into the required space on standard mobile viewports. When viewing these pages on an average mobile device, the user has to click "show more" to show one to three more words. 

### Details
Standard description: `iFixit has you covered with parts, tools, and free repair guides. Repair with confidence! All of our replacement parts are tested to rigorous standards and backed by our industry-leading warranty.`

### Devices/Browsers
Confirmed on the following:
- iPhone 12, 13 - Safari
- Samsung Galaxy 21, 22 - Chrome

### Screenshots
| Collapsed  | Expanded |
| ------------- | ------------- |
|  image | image |

Suggestions:
- Increase the accepted space on mobile to include one more line of text. 
- Change the copy

### LINKED ISSUE #198: Searching for certain items leaves white space in grid results
Where there are a small number of search results in the grid view, the results can be unevenly spaced and extra whitespace appears at the end of the results row.
CleanShot 2022-03-08 at 14 18 29

### LINKED ISSUE #199: Product quantity present on all product cards
Currently, every product card has a "# in stock" message. This means that very large stock quantities are displayed, and there is a double alert for out of stock (`sold out` tag as well as "0 in stock" message)

image
image

We should definitely still keep the case where stock is low and the "Only..." message is displayed.

@Annika29, were you envisioning stock quantities displayed for all products in https://github.com/iFixit/react-commerce/issues/66

Is there any value in displaying high inventory counts directly on the product card?

cc: @lithobraking

### PR DESCRIPTION
**Pull request by dhmacs**
fixes #195 
fixes #193 
fixes #197 
fixes #198 
fixes #199 
fixes #196 
fixes #175 

## QA

1. Visit the Vercel PR preview
2. Visit parts product list page
3. Verify that all of the above bugs are fixed

### CODE REVIEW

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I think the [tools section](https://react-commerce-git-fix-product-list-bug-ifixit.vercel.app/store/tools) is broken. I get a 404 error when visiting it.
CleanShot 2022-03-11 at 14 51 47
Also did you mean to remove the copy from All Parts?
CleanShot 2022-03-11 at 14 58 06

**Comment by dhmacs** [comment]
@deltuh-vee the tools product list is not in the db seeds yet. I've added the product list on Strapi so now you should be able to see it 👍

**Comment by deltuh-vee** [comment]
QA 🎬 
- [x]  On Sale items have a sale price that’s different than the regular price
- [x]  In Stock values are never negative
- [ ]  Mobile collection page description section fits without expansion. This is still cut off on the iPhone SE, but it’s also an uncommon phone size nowadays. deploy_block ✋
- [x]  Searching for certain items doesn’t leave extra white space at the end of grid results
- [x]  Product quantity is gone on high stocked product cards
- [x]  Product Filters don’t prevent scrolling
- [x]  Accessibility button border isn’t cut off in device breadcrumbs

**Comment by deltuh-vee** [comment]
un_dev_block 👍

**Comment by dshehbaj** [comment]
CR 💯

**Comment by cdcline** [comment]
CR 👍

**Comment by dhmacs** [comment]
@deltuh-vee this PR is deploy blocked on iPhone SE issue, but I'm not sure how you want me to act on that. Should we add one more line to the description?

**Pull request merged**
