### PR TITLE
Upgrade Strapi to v4.6.2

### LINKED ISSUE #1364: Draft ProductList showing up in list of Children
For some reason, [Nut Drivers](https://www.ifixit.com/Tools/Nut_Drivers) ([Strapi](https://strapi.ifixit.com/admin/content-manager/collectionType/api::product-list.product-list/2388)) is showing up in the list of Children on [Drivers and Wrenches](https://www.ifixit.com/Tools/Drivers_and_Wrenches) ([Strapi](https://strapi.ifixit.com/admin/content-manager/collectionType/api::product-list.product-list/2285)) despite being in Draft _and_ being marked `ExcludeFromHierarchyDisplay = True`. 

image

I made `ExcludeFromHierarchyDisplay = False` and I saw no change. 

I checked another similar situation ([Apple Thunderbolt Display](https://strapi.ifixit.com/admin/content-manager/collectionType/api::product-list.product-list/589?plugins[i18n][locale]=en) is in Draft but is a Child of [Mac Parts](https://www.ifixit.com/Parts/Mac)) but could not find the same behavior/bug. 

I tried publishing and unpublishing the ProductList. No change. 

I tried removing the Parent/Child relationship. That worked! But when the Draft page was added back to the Parent/Child relationship it showed up again in the list of Children. 

I'm going to remove the Parent/Child relationship until you can test/fix. 

image

CC @ifixitmaxb @dhmacs

### PR DESCRIPTION
**Pull request by dhmacs**
closes #1364 

❗❗❗After this PR is merged Strapi should be redeployed in production ❗❗❗

cc @sterlinghirsh @danielbeardsley @masonmcelvain 

## QA

1. Login into the [strapi instance for this branch](https://fix-draft-content-type-visibility.govinor.com/admin)
2. Go to settings and check that the Strapi version is `v4.6.2`
3. Verify that bug described by #1364 is fixed, meaning that draft product lists are not rendered among children of their parents

### CODE REVIEW

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Review by masonmcelvain — APPROVED** [review]

**Comment by deltuh-vee** [comment]
QA 🎬
 * Strapi is now at v4.6.2
 * draft product lists are not rendered among children of their parents

**Comment by deltuh-vee** [comment]
Redeploying Strapi

**Comment by dhmacs** [comment]
@deltuh-vee I see strapi still is at `v4.6.1` in production

cc @sterlinghirsh @danielbeardsley @masonmcelvain

**Comment by masonmcelvain** [comment]
I just replaced the machine, we're on 4.6.2 now 👍🏻

**Pull request merged**
