### PR TITLE
Use production .env values

### PR DESCRIPTION
**Pull request by djmetzle**
The current `.env.production` values point towards development/testing instances of strapi and the main site.

CC @dhmacs

### CODE REVIEW

**Comment by djmetzle** [comment]
deploy_block :stop_sign:

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 4666edc

**Review by Michelle5102 — APPROVED** [review]
CR :octocat:

**Comment by dhmacs** [comment]
This will break all staging instances running on Govinor. 

Let's instead make the override on AWS Amplify. I think it should be done like this:

Screenshot 2022-04-13 at 17 41 36

**Comment by erinemay** [comment]
dev_block 🕐 on some incoming changes ⬆️

**Comment by djmetzle** [comment]
We're going to configure this with `.env.local` on deploy, per @dhmacs 's suggestion. :+1: 

Closing this PR...

**Pull request closed without merging**
