### PR TITLE
Make pro only products not for sale for non pro users

### LINKED ISSUE #897: Make pro only products not for sale
Example product: https://react-commerce.vercel.app/products/20-lb-steel-shot-bag
image

### PR DESCRIPTION
**Pull request by dhmacs**
closes #897 

This PR shows a "not for sale" alert on pro only products when viewed by non pro users. We're hiding also non relevant sections, such as product reviews and cross sell.

## QA

1. Open [Vercel preview](https://react-commerce-git-make-pro-only-not-for-sale-ifixit.vercel.app/products/20-lb-steel-shot-bag)
2. Visit a pro-only product (e.g. https://react-commerce-git-make-pro-only-not-for-sale-ifixit.vercel.app/products/20-lb-steel-shot-bag) as an anonymous / not-pro user
3. Verify that the add to cart section is replaced by an alert
4. Login on cominor as a pro user
5. Visit the same pro-only product page an verify that you can add the product to cart

deploy_block 🛑  on a question:

- This PR identifies pro only products by looking for a "Pro Only" product tag. Is this correct?

cc @sterlinghirsh @erinemay

### CODE REVIEW

**Comment by jordycosta** [comment]
QA 🟢 

"Not for sale" alert on pro only products when viewed by non pro users 👍 

anonymous

### Testing Procedure:

1. Navigate to [a pro-only product](https://react-commerce-git-make-pro-only-not-for-sale-ifixit.vercel.app/products/20-lb-steel-shot-bag) as an anonymous user
2. Ensure that the alert is displayed, and you cannot add to cart
3. Sign in as a pro-user (login to cominor, then replace vercel.app with cominor.com)
4. Ensure no alert is displayed, and you can add to cart

1HtOh3lBQu

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Comment by sterlinghirsh** [comment]
un_deploy_block :zap: yes "Pro Only" tag is the correct signal here.

**Comment by sterlinghirsh** [comment]
I resolved a merge conflict here so please give a brief re-qa @jordycosta

**Comment by jordycosta** [comment]
QA 🟢 

Followed the testing procedure shown [here](https://github.com/iFixit/react-commerce/pull/903#issuecomment-1292299899)

---

deploy_block 🟨 on a question

I noticed a brief flash of the non-pro alert box before it shows the add to cart button on load

firefox_d2V14ntRbB

**Comment by danielbeardsley** [comment]
I'm gonna fix the conflicts here.

**Comment by danielbeardsley** [comment]
> I noticed a brief flash of the non-pro alert box before it shows the add to cart button on load

That sure is ugly. I have an idea though.

**Review by sterlinghirsh — APPROVED** [review]
CR :zap: @danielbeardsley and I talked about it and I think the flash is acceptable for now, since this only applies to 4 products anyway. We have an optimization that caches the return value of the user in localstorage that will mitigate the flash, but I think we should do that in a followup pull.

**Comment by sterlinghirsh** [comment]
QA :zap:

**Comment by dhmacs** [comment]
Mmm, it wasn't so noticeable while I was developing it. An easy fix would also be to render nothing while the user is loading (aka `return null`)

cc @sterlinghirsh @danielbeardsley

**Pull request merged**
