### PR TITLE
TOC: Polish 2

### PR DESCRIPTION
**Pull request by jarstelfox**
QA
---

* Update feedback on https://github.com/iFixit/ifixit/discussions/48967#discussioncomment-6870061
* Ensure the Prod version looks around the same

>1. First steps only seems to be highlighted in the TOC when the header First Steps is visible. It makes for a brief flash of highlighting as you scroll down. It looks like the other sections are highlighted when their headers are out of view.

Mostly solved. This was due to the causes list appearing when the TOC was enabled on desktop. The causes list will now only appear on mobile

>2. Related problems goes nowhere and is never highlighted. I assume this is WIP, but I'm not excluding anything here.

Solved.

>3. Scrolling issue in comment above is present on desktop as well.

Not solved. This is due to the browser controlling scroll vs my code controlling scroll. If you click a header, the browser determines which pixel needs to be shown. If you click the TOC, I am determining which pixel to scroll into view.

>4. Mobile First steps #Section_First_Steps doesn't accommodate the height of the header, so it's obscured by the TOC

I am not sure this is something we can solve for. Namely, the math to scroll to an item does not take into account the height of the header. In fact, it does not know about a header existing.

>5. I don't love it when cut off text can be so close to other cut off text.

I added back a fade on mobile, but we can remove it if Mattia is not a fan. Personally, I like it as well.

>6. I can see a pixel or two of scrolling above the TOC.

I think this is solved now that we no longer have the scroll percentage at the top of the page

### CODE REVIEW

**Comment by jarstelfox** [comment]
> getting an inconsistent scroll behavior when clicking on `Similar <device> problems`

Can you link the URL you are using?

**Comment by jarstelfox** [comment]
un_dev_block 🌵 @jordycosta I am not able to repro this. Can you provide more info?

**Comment by erinemay** [comment]
@jarstelfox it's happening on Chrome + Windows. Here it is on browserstack. 

https://github.com/iFixit/react-commerce/assets/72166715/f24829bc-5ee7-47ba-8a02-3e541856ab1c

dev_block 🌵, but I'm gonna keep testing to try to get you as much feedback as I can on this iteration.

**Comment by jordycosta** [comment]
> un_dev_block 🌵 @jordycosta I am not able to repro this. Can you provide more info?

My environment is Windows + Firefox 115.0.3 (64-bit)

**Comment by erinemay** [comment]
QA 👍 deploy_block 🌵 
Over all, the biggest problem I'm still seeing with the TOC is the index we scroll to when a TOC item is clicked (mobile and desktop). Since it wasn't included in this pull, maybe this should just address what it's addressing and deal with the scroll issue in another pull? 

It looks like it's actually just all the same issue. The issue @jordycosta found is the same as the one mentioned in the [discussion](https://github.com/iFixit/ifixit/discussions/48967).

> > 3. Scrolling issue in comment above is present on desktop as well.
> 
> Not solved. This is due to the browser controlling scroll vs my code controlling scroll. If you click a header, the browser determines which pixel needs to be shown. If you click the TOC, I am determining which pixel to scroll into view.

By header, do you mean clicking on the anchor links on an individual solution card? That's ok. 

I'm seeing issues clicking on the TOC. Is this controlled by the browser?

<details><summary>Browserstack Mobile screen recording</summary>

https://react-commerce-git-toc-polish-2-ifixit.vercel.app/Troubleshooting/iPhone_X/Won't+Turn+On/405163

https://github.com/iFixit/react-commerce/assets/72166715/49a091fd-ffa3-45e6-9a4e-f8960e91ebb7

</details>

OTHERWISE: 
---

> > 1. First steps only seems to be highlighted in the TOC when the header First Steps is visible. It makes for a brief flash of highlighting as you scroll down. It looks like the other sections are highlighted when their headers are out of view.
> 
> Mostly solved. This was due to the causes list appearing when the TOC was enabled on desktop. The causes list will now only appear on mobile

<details><summary>It looks like the cause list is present on desktop and missing on mobile right now. </summary>

https://react-commerce-git-toc-polish-2-ifixit.vercel.app/Troubleshooting/Mac_Laptop/MacBook+Keyboard+Not+Working/505002
image

image


</details>

The issue is fixed, but we're not seeing the cause list on mobile.

> > 4. Mobile First steps #Section_First_Steps doesn't accommodate the height of the header, so it's obscured by the TOC
> 
> I am not sure this is something we can solve for. Namely, the math to scroll to an item does not take into account the height of the header. In fact, it does not know about a header existing.

That's ok. I think it's minor enough.

> > 5. I don't love it when cut off text can be so close to other cut off text.
> 
> I added back a fade on mobile, but we can remove it if Mattia is not a fan. Personally, I like it as well.

I like it a lot better this way. 

2 and 6 are fixed ✔️

**Comment by erinemay** [comment]
A couple things we noticed during our conversation. Does not need to be addressed here, but documenting.

1. We start to lose the TOC when scrolling down to the bottom of the page.
https://react-commerce-git-toc-polish-2-ifixit.vercel.app/Troubleshooting/iPhone_X/Won't+Turn+On/405163#Section_iPhone_Needs_a_Force_Restart
image

2. Fast clicking keeps the highlight

https://github.com/iFixit/react-commerce/assets/72166715/8ef25df7-335f-4269-a06f-9d12f6cb0e35

These don't need to be addressed here. BUT deploy_block 🌵 on checking the prod preview links to make sure this doesn't affect the production pages (that don't have the TOC yet)

**Comment by jordycosta** [comment]
QA 🟢 

I confirmed the prod preview remains unchanged (no TOC, functionality isn't lost)

[Test Page](https://react-commerce-prod-git-toc-polish-2-ifixit.vercel.app/Troubleshooting/iPhone_X/Won't+Turn+On/405163)

**Comment by erinemay** [comment]
Actually deploy_block 🌵 on inverting the mobile cause list logic. Right now, the cause list is present on desktop and absent on mobile with the TOC enabled. It should be the other way around.

**Comment by jarstelfox** [comment]
I am going to dev_block 🌵 and implement some changes to the scroll logic after discussions with Erin and some rubber ducking

**Comment by jarstelfox** [comment]
un_dev_block 🌵 I think I addressed all the known issues 😅

**Comment by jarstelfox** [comment]
Sorry about the force push, I was looking to sign all these commits, but I messed up slightly. I am going to leave it as is

**Comment by jarstelfox** [comment]
>We start to lose the TOC when scrolling down to the bottom of the page.

@ianrohde both spent ~4 hours trying to solve this one.

This is actually quite hard / possibly impossible to solve 😓.

We both decided to call it and let this issue slide as it is minor.

**Comment by erinemay** [comment]
### Confirmed
- [x] Cause links present on mobile, absent on desktop
- [x] Scrolling behavior discussed https://github.com/iFixit/react-commerce/pull/1976#issuecomment-1720198690
    - Desktop
         - Clicking on a TOC item now goes to the top of the solution at the top of the viewport. 
    - Mobile
       - Clicking on a TOC item now goes to the top of the solution at the top of the viewport. 
       - There's now the minor difficulty of highlighting the exact item in the TOC when at the bottom of the page and several problems are visible on the page, but this is very minor.  
       - Issue 1 noted below that @jarstelfox and I discussed yesterday.
- [x] Bug: Quick clicking keeps highlighting https://github.com/iFixit/react-commerce/pull/1976#issuecomment-1720240066
- [x] Related problems link gone
- [x] Fade on mobile TOC
- [x] Losing TOC as we scroll down
     - Not fixed, but addressed: https://github.com/iFixit/react-commerce/pull/1976#issuecomment-1721962394  
- [x] Production preview (without TOC) appearance and behavior unchanged in desktop and mobile - all the following are the same as production
    - Cause link jump location 
    - Presence of cause links on desktop
    - Appearance

The epic has been converted into individual issues. Everything not addressed here is an individual issue on the project. 



@jarstelfox I know we talked about this yesterday. I wanted to make sure and document them somewhere.

<details><summary>1. The first time clicking on a TOC item, it doesn't add the padding and accommodate for the space of the heading. </summary>

On first scroll to a page with a #index on mobile, the padding for the cause title is not accommodated. On any subsequent click to a TOC item, it is.

https://github.com/iFixit/react-commerce/assets/72166715/bc6a7c59-e9d2-453d-9b31-f891e0c1501a

</details>


AND ❓ I'm noticing some behavior with long causes I don't think we saw yesterday. 

<details><summary>2. What's highlighted issue for long causes</summary>


I think when we talked about the which-toc-item-is-highlighted logic yesterday, it was roughly: highlight the highest cause whose top of cause box is within the viewport. It looks like it's selecting a cause outside of the current field of view. See the first cause on this list: https://react-commerce-git-toc-polish-2-ifixit.vercel.app/Troubleshooting/Mac_Laptop/MacBook+Keyboard+Not+Working/505002
image

</details>

As always, since this is safely behind a feature flag and the production previews are unchanged from production, QA 👍 deploy_block 🧷  if you want to merge and address in another issue.

**Comment by jarstelfox** [comment]
> The first time clicking on a TOC item, it doesn't add the padding and accommodate for the space of the heading

This is expected. I can add logic to handle this state, but I'd rather not. The short version is I will have to override the browser's default behavior, which I'd rather not do.



> 2. What's highlighted issue for long causes

Fair point here. I am considering an item "passed" if one pixel is off the top of the screen.

We could do something like the center is off-screen, but I am unsure if that is really required.

**Review by ianrohde — DISMISSED** [review]
CR ⚪

**Review by ianrohde — DISMISSED** [review]
CR ⚪

**Comment by deltuh-vee** [comment]
dev_block ✊ 
There's some issues when clicking on TOC links at the bottom of the page.
On Chrome + macOS, I get shifted up a bit, but not to the correct location:

https://github.com/iFixit/react-commerce/assets/5289715/d38b0cd2-c3b1-4b03-abbd-d180f6755c45

On Firefox + macOS I get shifted up, then back down:

https://github.com/iFixit/react-commerce/assets/5289715/bdb631ce-a254-42d0-9f42-8852be754af0

Seems to take me to the correct spot if I click again though.

**Comment by jarstelfox** [comment]
un_dev_block 🌵 nice find @deltuh-vee

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Review by ianrohde — APPROVED** [review]
CR ⚪

**Comment by kthaler** [comment]
I've tested all the items in the checklist here https://github.com/iFixit/react-commerce/pull/1976#issuecomment-1721974313

Ive tested this issue https://github.com/iFixit/react-commerce/pull/1976#issuecomment-1726258008 and confirm it was fixed

Compared production preview to iFixit.com and it looks near identical. Production actually fixed a little bug where the Introduction label is missing. 

The number 1 bug noted here https://github.com/iFixit/react-commerce/pull/1976#issuecomment-1721974313 is still present, but addressed by comment.

I think this was mentioned before, but I'm having this issue when near the bottom of the screen.
https://github.com/iFixit/react-commerce/assets/145375039/5a8a5792-59e1-4c3d-b3ef-d30ae6d3242e

Scrolling behavior is intuitive and feels good.

QA 👍 

@jarstelfox Okay to address anything else in follow up

**Comment by erinemay** [comment]
un_deploy_block 🌵

**Comment by jarstelfox** [comment]
Whew, thanks everyone, we should be close!

**Pull request merged**
