### PR TITLE
View Stats: Add a base component to troubleshooting pages

### PR DESCRIPTION
**Pull request by jarstelfox**
QA
---

* Ensure the view stats show up on troubleshooting pages
* Ensure they look decent at all screen sizes
	* Note: I made some minor improvements to the styling  when compared to view stats on the rest of the site

Connects: https://github.com/iFixit/ifixit/issues/49127

### CODE REVIEW

**Comment by jarstelfox** [comment]
deploy_block 🌵 on https://github.com/iFixit/ifixit/pull/49201 going out first as adding external block since this is required for QA

**Comment by ianrohde** [comment]
https://github.com/iFixit/ifixit/pull/49201 merged. I'll update this branch, but leave the block for your discretion.

**Comment by ianrohde** [comment]
I didn't move forward with the `Intl.NumberFormat` changes we discussed. After looking at the API data populating, they seemed like premature optimization.

**Comment by jordycosta** [comment]
QA 🟢 

View stats are showing up on [troubleshooting page(s)](https://react-commerce-prod-git-add-view-statistics-to-tr-0744f8-ifixit.vercel.app/Troubleshooting/Nintendo_Switch/Will+Not+Turn+On/481634) 👍 

Looks good on various screen sizes & orientations ✔️ 

**Desktop**

firefox_ysiy1px7L9

**Mobile**

firefox_OvFz0KD2gC

**Comment by jarstelfox** [comment]
image
@ianrohde Is it meant to look like this? I suspect you wanted to grow the content a bit more.

deploy_block 🌵 on answering this

**Comment by ianrohde** [comment]
> Is it meant to look like this? I suspect you wanted to grow the content a bit more.

Nope. @jordycosta what OS/browser?

**Comment by jarstelfox** [comment]
> Nope. what OS/browser?

See:
https://react-commerce-prod-git-add-view-statistics-to-tr-0744f8-ifixit.vercel.app/Troubleshooting/Nintendo_Switch/Will+Not+Turn+On/481634

I am on Chrome at 1870 wide

**Comment by ianrohde** [comment]
My bad! Chakra uses em for `sizes` units. I switched to px in https://github.com/iFixit/react-commerce/pull/1898/commits/649e2cf43db956e031085ba12bf908f695b8f695

<details>
Screenshot 2023-08-10 at 10 53 57 AM

</details>

**Comment by jordycosta** [comment]
@ianrohde Firefox Browser 116.0.2 (64-bit)

**Comment by ianrohde** [comment]
Rendering consistently now in Chromium, Firefox, and Safari

**Comment by jarstelfox** [comment]
un_deploy_block 🌵 I would CR, but I can't CR my own pull which is now mostly yours @ianrohde. Thanks again for the eyes here.

**Review by hcutrone — APPROVED** [review]
CR :burrito:

**Comment by erinemay** [comment]
QA 🦖 view stats look good on desktop/mobile Windows/Android/iOS/MacOS

image
image
image

**Pull request merged**
