### PR TITLE
Use DeviceTitle As Device Replacement in Item Type Overrides

### PR DESCRIPTION
**Pull request by danielcliu-ifixit**
## Overview

Lets use the deviceTitle to replace `[DEVICE]` in all cases. If deviceTitle doesn't exist for that productlist, we will no longer skip the override we will instead replace `[DEVICE]` with `title` instead.

## QA
Pretty much just check that it does what the overview says it will.

Connects: #https://github.com/iFixit/react-commerce/issues/589

### CODE REVIEW

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I think another strapi instance is being used for this react-commerce deploy
https://react-commerce-git-item-type-overrides-frontend-f-85a45b-ifixit.vercel.app/Parts/iPhone_12?disableCacheGets=1
https://item-type-overrides--frontend-fix-getitemoverrideattribute.govinor.com/admin/content-manager/collectionType/api::product-list.product-list/2006?plugins[i18n][locale]=en

It looks like there's an itemOverride on the react-commerce page
image
but not in Strapi
image

image

**Comment by danielcliu-ifixit** [comment]
gonna reopen with a smaller branch name

**Comment by masonmcelvain** [comment]
Double dashes don't matter after all, it was just a coincidence.

**Comment by danielcliu-ifixit** [comment]
from Curtis on slack 
```
It doesn't look like the unexpected itemType overrides were limited to your pull. The issue is also occurring on main for me.  https://main.govinor.com/admin/content-manager/collectionType/api::product-list.product-list/2003?plugins[i18n][locale]=en
https://react-commerce.vercel.app/Parts/iPhone_11
```
so i think were having a govinor issue still

**Pull request closed without merging**
