### PR TITLE
Add footer

### LINKED ISSUE #76: Add footer

### PR DESCRIPTION
**Pull request by dhmacs**
Closes #76 

## Changes

- Added GraphQL codegen to autogenerate typescript types from Strapi GraphQL (stuff under `lib/api/strapi/generated` does not need to be CR since it's auto generated by graphql codegen)
- Added footer components
- Refactored layout component to account for footer data requirements
- Refactored collection folder to get data from Strapi

## QA

1. Visit the Vercel PR preview
2. Visit a collection page and verify that the footer renders correctly
3. Verify that the footer data comes from the us store settings in Strapi

### CODE REVIEW

**Comment by ardelato** [comment]
@dhmacs I understand this is still a draft, therefore I am going to label it with an `external_block` so other QA members don't try to QA this just yet. This pull shows up in Pulldasher as ready to QA even though it is still a draft. 

Once, this pull is ready, feel free to remove the `external_block` label

**Comment by cdcline** [comment]
There's a lot going on in this pull!

It seems to be looking well. I'd vote for trying to make smaller pull request, it's very difficult to follow when they get this large.

**Comment by dhmacs** [comment]
> There's a lot going on in this pull!
> 
> It seems to be looking well. I'd vote for trying to make smaller pull request, it's very difficult to follow when they get this large.

I know this looks like a lot, but although many files have been touched it's not that bad as it looks since most changes are just renamed or moved files, and autogenerated code..
Here a brief description of the changes: 

- Added GraphQL codegen to autogenerate typescript types from Strapi GraphQL (stuff under `lib/api/strapi/generated` does not need to be CR since it's auto generated by graphql codegen)
- Added footer components
- Refactored layout component to account for footer data requirements
- Refactored collection folder to get data from Strapi

That being said, I'll try to do my best to open smaller PR 👍

**Comment by ardelato** [comment]
QA 👍 

## Steps Taken:
1. Checked out the Vercel Preview
2. In a new tab went to strapi.cominor.com
3. Then I confirmed on the collections page that the footer had all the links set within Strapi-> Menus

**Comment by cdcline** [comment]
CR 👍

**Comment by sterlinghirsh** [comment]
CR :zap:

**Pull request merged**
