### PR TITLE
Add compatibility accordion panel + compatibility section

### LINKED ISSUE #706: Add compatibility panel + section

### PR DESCRIPTION
**Pull request by federicobadini**
closes #706 

This PR adds the compatibility accordion panel - just below the product variant selector - and the compatibility section in the lower part of the page.

The accordion panel shows the first 3 compatible devices at most. If there are more than 3 compatible devices it also show an anchor link that points to the compatibility section on the bottom of the page

The compatibility section always list all the possible compatible devices in a grid layout. 

Accordion panel:

Screenshot 2022-09-20 at 11 38 08

Section:

Screenshot 2022-09-20 at 11 38 24

## QA

1. Visit Vercel preview
2. Navigate to a [product with compatibilities](https://react-commerce-git-add-compatibility-panel-and-section-ifixit.vercel.app/Products/iphone-11-screen)
3. Verify that everything is like in the mockup
4. Check also products with a different number of compatible devices

### CODE REVIEW

**Comment by jordycosta** [comment]
QA 🟢 
deploy_block 🟨 on alignment

Product with one device -> [iPhone 11 Screen](https://react-commerce-git-add-compatibility-panel-and-section-ifixit.vercel.app/Products/iphone-11-screen)
Product with two devices -> [MacBook Replacement Battery](https://react-commerce-git-add-compatibility-panel-and-section-ifixit.vercel.app/Products/macbook-replacement-battery)
Product with 3+ devices -> [MacBook Air 13" (Late 2010-2017) Battery](https://react-commerce-git-add-compatibility-panel-and-section-ifixit.vercel.app/Products/macbook-air-13-late-2010-2017-replacement-battery#compatibility)

---

The compatibility panel and section are present if applicable ✔️ 

Products with 3+ compatible devices show **See all compatible devices** in the panel ✔️ 
_(which directs to the compatibility section)_

Both the panel and section look good across various viewports ✔️ 

---

I noticed a slight alignment issue on the product page that has two devices shown above

section

**Comment by jordycosta** [comment]
QA 🟢 
deploy_block 🟨 

Product with one device -> [`iPhone 11 Screen`](https://react-commerce-git-add-compatibility-panel-and-section-ifixit.vercel.app/Products/iphone-11-screen)
Product with two devices -> [`MacBook Replacement Battery`](https://react-commerce-git-add-compatibility-panel-and-section-ifixit.vercel.app/Products/macbook-replacement-battery)
Product with 3+ devices -> [`MacBook Air 13" (Late 2010-2017) Battery`](https://react-commerce-git-add-compatibility-panel-and-section-ifixit.vercel.app/Products/macbook-air-13-late-2010-2017-replacement-battery)

The accordion panel and compatibility section are present if applicable ✔️ 

The accordion panel includes **"See all compatible devices"** if there are 3+ devices compatible with the product ✔️ 
_(this links to the compatibility section)_

The accordion panel and compatibility section both look good on various viewports ✔️ 

---

I noticed a slight alignment bug on the product page with two compatible devices

section

**Review by masonmcelvain — DISMISSED** [review]
CR ✌🏻

**Comment by federicobadini** [comment]
> I noticed a slight alignment issue on the product page that has two devices shown above

I made a small css adjustment to handle also this case:

Screenshot 2022-09-22 at 09 54 06

**Comment by jordycosta** [comment]
QA 🟢 
un_deploy_block 🟩 

I no longer see any alignment issues for compatible devices ✔️ 

long-list


looks-good

**Review by sterlinghirsh — APPROVED** [review]
CR :zap:

**Pull request merged**
