### PR TITLE
Add automation bot

### PR DESCRIPTION
**Pull request by dhmacs**
This is a second step to address #1017 

The generation of a delegate token is a little bit cumbersome since Shopify doesn't provide any UI to get a delegate token, we need to generate it via API.
To make this convenient, I'm introducing a bot package that will host every little automated script that we might need down the road.

## QA

1. Clone the project and follow the readme setup instructions
2. Run the following command:

    ```console
    pnpm bot shopify create delegate-token
    ```
    Follow the instructions and verify that you can successfully get a delegate token

    image

🚨 **Please note that the delegate token should be considered a secret, and thus should not be shared, nor posted on Github.**

### CODE REVIEW

**Comment by jordycosta** [comment]
Screenshot 2022-11-17 113730

Am I missing a step?
1. Clone react-commerce, setup
2. Checkout this branch
3. Run the command shown above

**Comment by dhmacs** [comment]
> 1. Clone react-commerce, install pnpm

Did you literally did just these 2 things? Make sure you follow [install instructions](https://github.com/iFixit/react-commerce#install), and also make sure to check [prerequisites](https://github.com/iFixit/react-commerce#install-prerequisites).
Also, after you clone the repo you should immediately checkout this branch, and then follow the install instructions

**Comment by rickisXP** [comment]
Also facing the same issue, I already have the repo set up. I double checked that I meet the prerequisite versions.
image

Steps
--
1. Checked out branch `add-automation-bot`
2. Ran `pnpm install:all`
3. Ran `pnpm bot shopify create delegate-token`
4. Observed output above

**Comment by deltuh-vee** [comment]
QA 🎬 
I was able to generate a storefront delegate access token. 
deploy_block ❓ 
I was able to use the API password from the Storefront | inkOfPixel app. Should I be able to use the API password from the iFixit Backend app instead?
image

**Comment by dhmacs** [comment]
> QA 🎬 I was able to generate a storefront delegate access token. deploy_block ❓ I was able to use the API password from the Storefront | inkOfPixel app. Should I be able to use the API password from the iFixit Backend app instead? 

Yes, any private app with storefront permissions should be able to generate the token 👍 

un_deploy_block 🟢

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 Very user friendly, great work!

**Pull request merged**
