### PR TITLE
Merge hero sections components into one

### PR DESCRIPTION
**Pull request by dhmacs**
I'm trying to divide the work being done in #265 in small chunks that are easier to review. This PR aligns the hero section component to how sections are built in product page template and page template.

## QA

1. Open a [product list without hero image](https://react-commerce-git-refactor-product-list-hero-section-ifixit.vercel.app/Parts) and verify that the hero section looks the same of the [equivalent product list in production](https://www.ifixit.com/Parts) (saved for content differences in Strapi)
2. Open a [product list with hero image](https://react-commerce-git-refactor-product-list-hero-section-ifixit.vercel.app/Parts/Nokia_G22) and verify that the hero section looks the same of the [equivalent product list in production](https://www.ifixit.com/Parts/Nokia_G22) (saved for content differences in Strapi)

### CODE REVIEW

**Comment by deltuh-vee** [comment]
dev_block ✊ 
Breadcrumbs are incorrect. The last breadcrumb is missing and I see the dropdown button for the breadcrumbs even though there's enough space to display all of the breadcrumbs. As seen on https://react-commerce-git-refactor-product-list-hero-section-ifixit.vercel.app/Parts/Mac
image

**Comment by dhmacs** [comment]
@deltuh-vee it was due to the lack of data on Strapi. I took this opportunity to post also a small fix that is not related to the work on this PR. 

un_dev_block 🏎️

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 

> I'm trying to divide the work being done in https://github.com/iFixit/react-commerce/issues/265 in small chunks that are easier to review.

Thank you!

**Comment by deltuh-vee** [comment]
QA 🎬 
Products lists with and without hero images still look the same as on prod.

**Pull request merged**
