### PR TITLE
Align system font style to mockup

### PR DESCRIPTION
**Pull request by federicobadini**
This PR aligns the general website appearance (in terms of font sizes and weights) to the Figma mockup

### QA

1. Visit Vercel Preview
2. No functional difference should be present. Only a look and feel more adherent to the mockup

### CODE REVIEW

**Review by andyg0808 — APPROVED** [review]
CR :+1:

**Review by andyg0808 — APPROVED** [review]
CR :+1:

**Comment by jordycosta** [comment]
QA 🟢 

The [Vercel preview](https://react-commerce-git-align-system-font-style-to-mockup-ifixit.vercel.app/) looks and feels more adherent to the Figma mockup [here](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=6374%3A80034&t=izx42U67wbpEXP6u-0) 👍

**Comment by k0rvusk0r4x** [comment]
Not sure why the previous sign off didn't take, but rechecked things. Looks good here.

QA 😺

**Pull request merged**
