### PR TITLE
Replace `postinstall` script

### PR DESCRIPTION
**Pull request by andyg0808**
This prevents it running on Rush installs, where it doesn't make any
sense anyhow.

I'm happy to help get Rush set up in this repo, if that would be desirable.

### CODE REVIEW

**Comment by danielbeardsley** [comment]
Did we move this into the mono repo?

**Comment by danielbeardsley** [comment]
CR :+1:

**Comment by Michelle5102** [comment]
CR :octocat:

**Comment by andyg0808** [comment]
@danielbeardsley Sorta. We pulled it in as a submodule so it'd still be available for third-party development.

**Comment by andyg0808** [comment]
I'm gonna deploy_block :+1: 
on @dhmacs taking a look, since I'm not sure what the exact implications are of this.

**Comment by dhmacs** [comment]
@andyg0808 

> on @dhmacs taking a look, since I'm not sure what the exact implications are of this.

There shouldn't be any issue other than breaking the convention that `npm install` install deps. I suggest to update the install instructions on the readme to specify that you need to run `npm run install:all`. 

> I'm happy to help get Rush set up in this repo, if that would be desirable.

Sure, let's do a call so you can explain me the setup 👍

**Comment by ardelato** [comment]
@andyg0808 any notes for QA on how to test this?

**Comment by ardelato** [comment]
QA 👍 

deploy_block 🎨  on updating the **README** with the new instructions

```diff
diff --git a/README.md b/README.md
index 72a3f78..a494874 100644
--- a/README.md
+++ b/README.md
@@ -14,7 +14,7 @@ You can run the backend both using SQLite and using Postgres with docker compose
 This command will install both backend and frontend dependencies:
 
 /```sh
-npm install
+npm run install:all
 /```
 
 ### Dev server

```

## Steps Taken:

Repeated the same steps as https://github.com/iFixit/react-commerce/pull/133#issue-1057170131
1. Cloned this repo locally
2. Made sure I was running node v14
3. Installed the dependencies `npm run install:all`
4. Renamed `backend/.env.example` to `backend/.env`
5. Ran dev server: `npm run dev`
6. Logged into strapi at `localhost:1337/admin` -- _which loaded_ 👍 
7. Visited the parts collection at `localhost:3000/collections/parts` -- _which loaded_ 👍

**Comment by andyg0808** [comment]
un_deploy_block :+1: 
Readme updated.

**Comment by ardelato** [comment]
@andyg0808 do you still want to mark this PR with QA Req 0 or do you still need to meet with @dhmacs to know about the implications of it?

**Review by dhmacs — APPROVED** [review]
CR 👍

**Comment by andyg0808** [comment]
@ardelato I think I'm fine on both points. Since it sounds like there's nothing expected to break from this, and since you've already given it QA, I'm fine to just merge it (if the final diff looks like what you'd expect).

**Comment by Michelle5102** [comment]
CR :octocat:

**Pull request merged**
