### PR TITLE
Fix product list meta title

### PR DESCRIPTION
**Pull request by masonmcelvain**
Connects https://github.com/iFixit/ifixit/issues/50741

## QA

Make sure the bug described in the issue is no longer present on the react-commerce-prod deployment. We never saw the bug on the react-commerce deployment.

### CODE REVIEW

**Comment by masonmcelvain** [comment]
Nope, 9cccffe4b58767823f79c04b206236220c4d5b75 didn't fix it

image

**Comment by masonmcelvain** [comment]
dev_block 👍🏻

**Comment by masonmcelvain** [comment]
12707f8b1747d5b2cdf8d8557e5a391d8e62712d didn't do it either

image

**Comment by masonmcelvain** [comment]
❌ a025fd67430f0ffd6c5b550e70c22496355b0829

image

**Comment by masonmcelvain** [comment]
❌ 7d71a13e4051994654801e8ac56a5b1c3ce5ff2d

image

**Comment by masonmcelvain** [comment]
Welp it's not a great solution, but b2785ba1a1fdbcf2f8780464bf9e69f77a3d0edd fixed it

image

**Review by jarstelfox — APPROVED** [review]
CR 🌵 but deploy_block 🌵 you may need to update https://github.com/iFixit/react-commerce/blob/25834427f6ae7ca8fb5ce9ad95c517ba81feced4/frontend/app/layout.tsx#L115 which is the copied code for the App router

**Comment by masonmcelvain** [comment]
Hm I don't know how we'd update that since it's static. It does seem like a bridge we'd need to cross when we move the product list page to the app router.

**Review by sterlinghirsh — APPROVED** [review]
CR :zap: this is weird but maybe we can come up with a less weird fix later

**Comment by masonmcelvain** [comment]
QA 👍🏻 

image

**Comment by jarstelfox** [comment]
un_deploy_block 🌵 we chated and I agree there is not an issue for the App router code

**Pull request merged**
