### PR TITLE
Sentry: Make previews report to dev

### PR DESCRIPTION
**Pull request by masonmcelvain**
- Prevents previews from reporting to prod Sentry
- Prevents previews from reporting to prod analytics urls.

## QA
- Make sure errors in the previews are reported to `react-commerce-dev` Sentry, not the prod Sentry.
  - Idk how to do this. You might have to push a commit to this branch that throws an error somewhere, check that it gets reported properly, then remove the commit from this branch.
- Make sure analytics data for previews is sent to matomo.ubreakit.com instead of minerva.ifixit.com

## Before deploy

Update the prod Vercel dashboard with the env vars that were changed.

### CODE REVIEW

**Comment by masonmcelvain** [comment]
deploy_block ✌🏻 on updating the prod Vercel dashboard

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I'm still not seeing any events show up on matomo.ubreakit.com.

**Comment by masonmcelvain** [comment]
Hm that's annoying. But I have a feeling that it's a configuration problem in Matomo, and not a code problem here, since we're successfully reporting to minerva.ifixit.com in prod.

I'm going to un_dev_block ✌🏻 because I think we're more interested in not reporting to prod Sentry/minerva than we are in successfully reporting to dev Sentry/matomo

**Comment by masonmcelvain** [comment]
I think I figured out how to get analytics to go to matomo.ubreakit.com. You need to add the url of the preview to the list of urls in matomo:
image

It took like 10 minutes for my visits to show up, but they eventually did:
image

**Comment by jarstelfox** [comment]
When it comes to Matomo:

Think of it as a third-party product. The App team is responsible for it's configuration and making it work.

All you need to check is:

1. Are you pinging the right URL
2. Did you get a 200 / 204 HTTP code

If so, just assume the data will arrive in Matomo unless you hear otherwise

**Review by jyee27 — DISMISSED** [review]
CR ☕

**Comment by masonmcelvain** [comment]
un_deploy_block ✌🏻 @danielbeardsley added the env vars to prod Vercel dashboard

image

**Comment by deltuh-vee** [comment]
QA 🎬 
* Errors in the previews are reported to react-commerce-dev Sentry, and not the prod Sentry.
* Analytics data for previews is sent to matomo.ubreakit.com instead of minerva.ifixit.com

**Review by danielbeardsley — COMMENTED** [review]
CR :+1:

**Review by danielbeardsley — APPROVED** [review]
CR :+1:

**Pull request merged**
