### PR TITLE
Breadcrumbs: Add missing dependencies

### PR DESCRIPTION
**Pull request by andyg0808**
Seems I missed some dependencies when I set this up previously. I'm assuming this is because we don't have PNPM set to particularly strict settings in this repo, so I didn't notice that they were missing. It could also be because the code wasn't actually being used yet, so there wasn't any build to break.

qa_req 0
This is dependency-only, and this code is currently unused. We'll test it when we integrate it on the monorepo side.

### CODE REVIEW

**Review by dhmacs — COMMENTED** [review]
@andyg0808 What do you think about specifying strict versions? Imo it'd be easier to know which versions we're relying on, and it would be more predictable to recreate lock files

related #1346

**Comment by andyg0808** [comment]
@dhmacs Yeah, I'll do that. I initially was thinking that I'd want it to just use whatever peer version was available,but as I think about it, it'll throw errors if there's a version mismatch, so we shouldn't have problems with different-version copies of libraries floating around.

**Comment by danielbeardsley** [comment]
I have a guess about the failures. Maybe this package was getting a different version of chakra previously and adding these explicit dependencies changed which version it ended up being resolved to?

The failure is the same across seemingly all the failures which makes me thing it's not a one-off temporary thing. That said, I'm having a hard time imagining what could be wrong about this...

**Review by danielbeardsley — APPROVED** [review]
CR :+1: 

That looks better. How did we previously arrive at the versions such that they didn't match the ones in other packages?

**Comment by andyg0808** [comment]
@danielbeardsley The first time, I don't remember how I chose the version ranges; I might have referred to another `package.json`. The second time, when I made them fixed versions, I think I used whatever the ranges had resolved to in the `pnpm-lock.yaml`. The third time, I tried to find the existing version numbers in the `pnpm-lock.yaml` which weren't being added by my changes. And then this time, I mostly just made sure to get _all_ the versions to match existing entries in the `pnpm-lock.yaml`.

**Pull request merged**
