### PR TITLE
GitHub Actions: Resolve deprecation warnings

### PR DESCRIPTION
**Pull request by batbattur**
## Summary
Resolves all github action deprecation warnings.

## QA notes
Check summaries for all CI workflows and make sure we don't get deprecation warnings anymore.
Also, make sure the bundle analysis comment shows up on the pull.

connects https://github.com/iFixit/ifixit/issues/47011

### CODE REVIEW

**Comment by batbattur** [comment]
dev_block 🚛 the bundle analysis comment got messy

**Comment by batbattur** [comment]
un_dev_block 🚛

**Comment by jordycosta** [comment]
QA 🟢 

_Next,js_ bundle analysis comment was posted https://github.com/iFixit/react-commerce/pull/1587#issuecomment-1509227356 ✔️ 
There are no longer warnings shown in the CI logs ✔️

**Review by mlahargou — APPROVED** [review]
CR 📱

**Pull request merged**
