### PR TITLE
Add Cypress Cart Test To Product Page

### PR DESCRIPTION
**Pull request by danielcliu-ifixit**
## Overview

We want to add some tests to the repo to cover cart functionality. This adds several tests that make sure that several actions go as expected.

## QA
Should be covered by tests qa_req 0;

Closes: #843

### CODE REVIEW

**Comment by danielbeardsley** [comment]
CR :+1: 

But the CI failures are relevant.

**Comment by danielbeardsley** [comment]
Very likely that it will never finish. Maybe there's an error with the cart api. Maybe there's a CORS problem and the request is denied. Any idea what the url looks like for these cypress tests?

**Comment by danielcliu-ifixit** [comment]
@danielbeardsley i considered that but if its a cors problem i assume that the vercel previews wouldn't work either right? The dev one works and the prod one doesn't seem to be the one being tested against

**Comment by danielbeardsley** [comment]
> i considered that but if its a cors problem i assume that the vercel previews wouldn't work either right?

CORS is about exempting certain domains from cross-origin request limitations. We have to explictly exempt certain origins: https://github.com/iFixit/ifixit/blob/master/iFixit/Auth/CORSMiddleware.php#L58-L72

Looks like the dev server is run at `http://localhost:3000` which should be trusted:
https://github.com/iFixit/react-commerce/blob/main/frontend/cypress.config.ts#L26

But it's hard to know. Do these pass locally?

**Comment by danielcliu-ifixit** [comment]
@danielbeardsley yes they pass locally

**Comment by danielcliu-ifixit** [comment]
un_deploy_block :v:

**Review by danielbeardsley — APPROVED** [review]
CR :+1: 

Good work!

**Pull request merged**
