### PR TITLE
Product page: start adding tests

### PR DESCRIPTION
**Pull request by batbattur**
## Background
Previously, we weren't setting the `NODE_ENV` properly in the `main.yml` workflow, therefore, it was using the `frontend/.env.production` ([example](https://github.com/iFixit/react-commerce/actions/runs/3107844588/jobs/5036395179#step:6:24)) instead of `frontend/.env.test`.
## Summary of changes
In this pull:
1. Now we're using `frontend/.env.test` to run cypress test in E2E workflow ([example](https://github.com/iFixit/react-commerce/actions/runs/3108801290/jobs/5038391640#step:6:24)).
2. Turned on `FLAG__PRODUCT_PAGE_ENABLED` to true in `.env.test` to start testing product pages. 
3. Unskipped a test that was skipped which tests clicking on `View` button from `/Parts` page and verifies if the view button link matches the clicked product page link. 

## CR notes
In `frontend/.env.test` I had to switch `NEXT_PUBLIC_DEFAULT_STORE_CODE`  from `us` to `test` because I was getting the `Store not found` error:  here's an [example](https://github.com/iFixit/react-commerce/actions/runs/3108295882/jobs/5037334565#step:6:112). 

However, there is an issue with using `us` as `STORE_CODE` because all products become `out-of-stock` when running the app locally. To resolve `out-of-stock` issue locally, we can duplicate the `us` store and rename it to `test` with the correct credentials, [more details here](https://ifixit.slack.com/archives/C01K32B4FPX/p1663260330576119?thread_ts=1663259552.812549&cid=C01K32B4FPX). However, I don't think we can do manually duplicate it in CI when the workflow is running. 

Question: @dhmacs which store do we ideally want to use for `NEXT_PUBLIC_DEFAULT_STORE_CODE` in `.env.test` when running the cypress tests in Github Actions? If it's the `test` store, is it possible to add the `test` store in production so it would be copied to local dev?

## QA notes
Please make sure the `E2E tests` ci check is passing.
Also, make sure the previews are still working. 

Connects #452

### CODE REVIEW

**Comment by batbattur** [comment]
deploy_block 🚛 on question in description for `NEXT_PUBLIC_DEFAULT_STORE_CODE` in `frontend/.env.test`

**Comment by dhmacs** [comment]
@batbattur No, we shouldn't add the test store in production. it seems like it's about time to automate the store setup for previews environments 😁 I'm working on it, I'll open a PR soon

**Comment by jordycosta** [comment]
QA 🟢 

E2E tests CI check is passing ✅ 
[`react-commerce-prod`](https://react-commerce-prod-git-unskip-cypress-test-ifixit.vercel.app/) preview is working ✔️ 

e2e

---

deploy_block 🟨 

I'm getting a 500: INTERNAL_SERVER_ERROR on the [react-commerce](https://react-commerce-git-unskip-cypress-test-ifixit.vercel.app/) preview, is this expected?

**Comment by batbattur** [comment]
> @batbattur No, we shouldn't add the test store in production. it seems like it's about time to automate the store setup for previews environments 😁 I'm working on it, I'll open a PR soon

@dhmacs Sounds good, thank you! Then let's keep the `STORE_CODE` as `us` in `.env.test` for the moment since it was already using the `us` (`.env.production`) in CI. 


> I'm getting a 500: INTERNAL_SERVER_ERROR on the [react-commerce](https://react-commerce-git-unskip-cypress-test-ifixit.vercel.app/) preview, is this expected?

@jordycosta I don't think that is expected and I'm not sure if it's related to changes in this pull. 
Unless the preview uses the `frontend/.env.test`, I think everything should be working fine.

**Comment by jordycosta** [comment]
un_deploy_block 🟩 

https://github.com/iFixit/react-commerce/pull/725#issuecomment-1256515436

**Comment by batbattur** [comment]
> Nope, we should use STORE_CODE=test. The change I'm making to the seed file will create strapi instances with the test store correctly seeded.

Oh okay, that's better. Then I'll hold off this change for the moment until it's correctly seeded. 

dev_block 👍

**Comment by batbattur** [comment]
> This is because there's no "test" store currently set on https://unskip-cypress-test.govinor.com/admin

I'm not sure if I understand this but does this mean we manually have to duplicate the `us` store to `test` in each govinor branch as well? (sorry for my confusion 😓)

It looks like the [preview](https://react-commerce-git-footer-update-deps-ifixit.vercel.app/Parts) on this [pull](https://github.com/iFixit/react-commerce/pull/709), is working even though the `test` store is not set in the https://footer--update-deps.govinor.com/admin/.

**Comment by dhmacs** [comment]
> > This is because there's no "test" store currently set on https://unskip-cypress-test.govinor.com/admin
> 
> I'm not sure if I understand this but does this mean we manually have to duplicate the `us` store to `test` in each govinor branch as well? (sorry for my confusion 😓)

Nope, I'm changing the seed so that is done automatically

> It looks like the [preview](https://react-commerce-git-footer-update-deps-ifixit.vercel.app/Parts) on this [pull](https://github.com/iFixit/react-commerce/pull/709), is working even though the `test` store is not set in the https://footer--update-deps.govinor.com/admin/.

This PR is some 80 commits behind the main branch, it's missing the latest store-related changes.

**Comment by batbattur** [comment]
Set the `STORE_CODE` back to `test` in `frontend/.env.test`.

@dhmacs Thank you for doing https://github.com/iFixit/react-commerce/pull/740 🙌 

un_dev_block 👍

**Comment by jordycosta** [comment]
QA 🟢 

E2E tests CI check is passing ✅ 
[`react-commerce-prod`](https://react-commerce-prod-git-unskip-cypress-test-ifixit.vercel.app/) preview is working ✔️ 

e2e

**Review by dhmacs — APPROVED** [review]
lgtm 

CR 👍

**Pull request merged**
