### PR TITLE
Move react-components into react-commerce monorepo

### LINKED ISSUE #288: Move Chakra Theme into react commerce monorepo

### PR DESCRIPTION
**Pull request by dhmacs**
fixes #288 
 
## Changelog

- Move chakra theme into monorepo
- Move pagination component into monorepo
- Drop `react-components` dependency

## QA

1. Visit the Vercel PR preview (replace vercel.app with cominor.com) 
2. Navigate to `/Store/Parts`
3. Verify that the product list page still looks the same as main branch

### CODE REVIEW

**Comment by danielbeardsley** [comment]
Thank you!!  CR :+1:

**Review by danielbeardsley — APPROVED** [review]
Thank you!! CR :+1:

**Comment by rickisXP** [comment]
QA :rocket: but deploy_block :question: on one question
- Product list page looks visually identical to master :heavy_check_mark: 

Question
--
- Collection subtitles/descriptions are not exactly the same as on master. Is this expected?
<details><summary>Screenshots</summary>

MASTER

image

BRANCH

image

</details>

Steps taken
--

1. Visited [the branch preview's part page](https://react-commerce-git-move-chakra-theme-into-monorepo-ifixit.cominor.com/Store/Parts?)
2. Navigated to random collections, observed no formatting diffs with master
3. Checked formatting when filters are applied, search filter is used, and displaying in block view

**Comment by erinemay** [comment]
@rickisXP, yeah there's a data discrepancy between [main strapi](https://main.govinor.com/admin) and the [branch strapi](https://move-chakra-theme-into-monorepo.govinor.com/admin). You can manually copy over the content for a page so to make sure it looks the same on both.

**Comment by dhmacs** [comment]
@rickisXP as @erinemay said you can manually copy the content. The seed data for branches is an old subset of what's on the main branch. I've also laid out some work to make it easier to get fresh content on branches 👍 

un_deploy_block 🐎

**Pull request merged**
