### PR TITLE
Refactor product list items

### LINKED ISSUE #1370: Refactor product list items
connects https://github.com/iFixit/design/issues/510

We want to refactor collection list and grid items to align to the new mockups.

### PR DESCRIPTION
**Pull request by federicobadini**
closes #1370 

This PR update the spacing and measures in the product list and grid items to adhere to https://github.com/iFixit/design/issues/510

### QA

1. Visit [Vercel preview](https://react-commerce-git-refactor-product-list-items-ifixit.vercel.app/Parts)
2. Verify that the page is correctly working and that grid and list items are aligned to the mockup

### CODE REVIEW

**Review by masonmcelvain — DISMISSED** [review]
CR ✌🏻 styling looks reasonable and consistent, gonna rely on QA to make sure it matches the design spec

**Comment by federicobadini** [comment]
Aligned with main to include the test fix

**Review by masonmcelvain — DISMISSED** [review]
CR ✌🏻

**Comment by k0rvusk0r4x** [comment]
On desktop the lists view, the mockup has the view button the same as it in on the main branch, but here it is wider (Note that the button is the same size on mobile, but that is the same as master.): 
This branch: 
image
Main branch and mockup: 
image

dev_block 😿 to either fix the desktop list button to be smaller again, like the mockup, or to officially decide we like the larger button

**Comment by federicobadini** [comment]
The width of the button in the mockup was set to adapt to text and its resulting width was `Hug (71px)`.
Discussing with @mmarcon91 we expanded it to 80px, which is the nearest chakra size available larger than `71px`.

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by erinemay** [comment]
un_dev_block 👍 this is ready for qa again

**Comment by erinemay** [comment]
@federicobadini, what's the scope of this? Is it just the spacing around the list items? I'm still seeing some major differences between the list items here and those on the mockup.

It looks like the image is still centered vertically aligned and the price/view/stock warning are still top aligned

Mockup:
image

https://react-commerce-prod-git-refactor-product-list-items-ifixit.vercel.app/Parts/iPhone?p=8:
image

**Comment by erinemay** [comment]
Desktop at lg screen width (Chrome and Safari):
- Spacing is tighter 
- Images are top aligned (looks good with images with different aspect ratios)
- Flair/reviews look the same (as mockup)
- Low stock warning is now to the side of the view button
- (and at xl, we get 4 columns on the grid view)

Overall, looks good. dev_block 🧷 a couple of things. 
<details><summary>Can you add some space between the discount price and the regular price on the grid view?</summary>

Screenshots from Android+Chrome, but present on desktop and mobile Safari
This branch:
image

Main:
image

</details>


<details><summary>Mobile grid view font sizes</summary>

It looks like from the mockup that the product title and price are the same font, but on the page, I see the price is set to medium and the product title is set to small.

This is from mobile Chrome:

Branch: 
image


Mockup:
image


</details>

**Comment by federicobadini** [comment]
> Can you add some space between the discount price and the regular price on the grid view?

Done

> It looks like from the mockup that the product title and price are the same font, but on the page, I see the price is set to medium and the product title is set to small.

Good catch! The discrepancy here is due to the fact that the component rendering the price is shared among several other parts of the website (it supports pro badges, discount badges, different content dispositions etc). 
I discussed the thing with @mmarcon91 and we agreed that it is reasonable to keep it as it is right now.

un_dev_block 👍

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Pull request merged**
