### PR TITLE
Refactor product list children cleanup

### LINKED ISSUE #1361: Refactor product list children
connects https://github.com/iFixit/design/issues/510

We want to refactor product list children to align to the new mockups.

### PR DESCRIPTION
**Pull request by federicobadini**
🚫 blocked by #1373 
🚫 blocked because we wanna check that removing fields from Strapi does not cause any issue in production

closes #1361

This PR is updating the productList model in Strapi to eliminate the childrenHeading field which is not needed anymore 

❗ ❗ ❗ After this PR is merged Strapi should be redeployed in production ❗ ❗ ❗
cc @sterlinghirsh @danielbeardsley 

### QA

1. Navigate to [Strapi](https://refactor-product-list-children-cleanup.govinor.com/admin)
2. Verify that the `childrenHeading` field is not present anymore in the `productList` model
3. Visit [Vercel preview](https://react-commerce-git-refactor-product-list-children-ifixit.vercel.app/Parts)
4. Verify that the product list page still renders correctly

### CODE REVIEW

**Comment by jordycosta** [comment]
QA 🟢 

Confirmed that the childrenHeading field is no longer present ☑️ 
Confirmed that the product list page still renders correctly ✅ 

---

### Testing Procedure:
1. Navigate to the Strapi Content Type Builder (main)
2. Load up the Strapi Content Type Builder (refactor-product-list-children-cleanup)
3. Compare the fields, ensure that `childrenHeading` is no longer present on this branch
4. Navigate to the [/Parts](https://react-commerce-git-refactor-product-list-children-ifixit.vercel.app/Parts) page for this branch
5. Ensure that the product list page is still rendering correctly

---

**Before**
before

**After**
after

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by masonmcelvain** [comment]
QA ✌🏻 I checked that the `childrenHeading` field is still absent on Strapi for this branch, and that product list pages are still functioning normally on the react-commerce preview.

**Comment by deltuh-vee** [comment]
Redeployed Strapi

**Pull request merged**
