### PR TITLE
Implement pro pricing on product page

### LINKED ISSUE #689: Support pro pricing
Similar to how we do on the collection page, we'll want to support pro pricing with a price_tiers metafield. This will be added in https://github.com/iFixit/ifixit/issues/44583

We can load the page with the original price and then swap the display after we get the user's discount tier.

### PR DESCRIPTION
**Pull request by dhmacs**
closes #689 

## Changelog

- Introduces support for pro prices in the product page and in the drawer
- Refactors some price related dependencies into monorepo packages so that they can be used by the cart drawer
- Refactors the cart sdk to abstract away cart api implementation details and provide a consistent interface to manipulate the cart line items

## Known issues

- We noticed that the cart api returns different pro prices. Most likely this is due to data being out of sync in the product variant metafield cc @sterlinghirsh 
- https://github.com/iFixit/ifixit/issues/44855

## QA

1. Visit Vercel preview
2. Login on cominor as a pro user
3. Visit a [product page](https://react-commerce-git-add-product-page-pro-pricing-ifixit.vercel.app/Products/pro-tech-toolkit)
4. Verify that discounted prices have the pro badge (check the product price, the cross sell items and the featured products)
5. Add something to the cart and verify that the cart drawer also displays pro prices
6. Play with the cart drawer and verify that it keeps working correctly
7. Try to checkout and verify that you are correctly redirected to the Shopify checkout
8. Repeat previous step but logged out (or logged as a non-pro user)

### CODE REVIEW

**Comment by erinemay** [comment]
dev_block 🏷️ 

I'm not seeing pro pricing for every pro product. I see it for the PTT linked in the description, but it's not present for https://react-commerce-git-add-product-page-pro-pricing-ifixit.vercel.app/Products/samsung-galaxy-note20-5g-rear-camera-lens-cover. The discount price is shown in the mini cart for this product, it just doesn't have the pro badge and discount shown on the product page. Is this not a pro part? I double checked algolia and it looks like this product isn't set as pro, but it's showing up on the [cominor php](https://www.cominor.com/Store/Android/Samsung-Galaxy-Note20-5G-Rear-Camera-Lens-Cover/IF463-000?o=1) product page as pro. So I don't actually know if it's pro or not 🤷 

The calculation for the non-discounted price in each product card in the mini cart is not multiplied by the number of items. Screenshots below are from the same cart, but one more of each product is added. The discounted price doubles appropriately, but the original price is not. It looks like the difference between the crossed out original price and the displayed price for that product will always be the single-item discount amount.
image
image

Note: The saved price calculated at the bottom updates as expected. The issue appears to just be on each individual price card.
image



Steps to set up pro user: Made a test user and set their discount level in [customer-manager](https://www.cominor.com/Admin/CustomerManager?userid=) to Tier 2

**Comment by dhmacs** [comment]
> I'm not seeing pro pricing for every pro product. I see it for the PTT linked in the description, but it's not present for https://react-commerce-git-add-product-page-pro-pricing-ifixit.vercel.app/Products/samsung-galaxy-note20-5g-rear-camera-lens-cover. The discount price is shown in the mini cart for this product; it just doesn't have the pro badge and discount shown on the product page. Is this not a pro part? I double checked algolia and it looks like this product isn't set as pro, but it's showing up on the [cominor php](https://www.cominor.com/Store/Android/Samsung-Galaxy-Note20-5G-Rear-Camera-Lens-Cover/IF463-000?o=1) product page as pro. So I don't actually know if it's pro or not 🤷

This is a data issue, the metafield for the variant is not populated https://ifixit-test.myshopify.com/admin/products/6738211111002/variants/39942178078810

cc @sterlinghirsh 

> The calculation for the non-discounted price in each product card in the mini cart is not multiplied by the number of items. Screenshots below are from the same cart, but one more of each product is added. The discounted price doubles appropriately, but the original price is not. It looks like the difference between the crossed out original price and the displayed price for that product will always be the single-item discount amount. image image

Wow I didn't notice 🤦‍♂️  Seems this issue is present also in production. Anyway I've fixed it 👍 

un_dev_block 🟢

**Comment by k0rvusk0r4x** [comment]
- The calculations are no working properly.
- Other concerns have been noted as data issues.

QA 😺

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Pull request merged**
