### PR TITLE
Fix troubleshooting page markup error

### PR DESCRIPTION
**Pull request by federicobadini**
This PR fix a markup nesting issue.
I think it was the reason why Sentry showed an high number of non crash-free sessions recently.

Screenshot 2023-10-19 at 19 25 39

### QA

1. Visit Vercel preview
2. No visible change should be present.
3. As soon as released we should see crash-free sessions going back to normal

### CODE REVIEW

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Comment by ianrohde** [comment]
Is there any way we can add an alert for vercel crash-free sessions in slack? This is too easy to miss when Chakra components render various elements.

**Comment by erinemay** [comment]
There are a couple visual changes on the page. dev_block 🌵on fixing those. Otherwise, looks pretty much unchanged.

<details><summary>1. Desktop: Device summary is no longer truncated</summary>

Main/Live
https://react-commerce-prod.vercel.app/Troubleshooting/PlayStation_4/Black+Screen/483709
image

This branch
https://react-commerce-prod-git-fix-troubleshooting-page-b4ba20-ifixit.vercel.app/Troubleshooting/PlayStation_4/Black+Screen/483709
image

</details>

<details><summary>2. Desktop and mobile: Change in space between cause card title and beginning of text as well as introduction H2 and start of text</summary>

Main/Live
https://react-commerce-prod.vercel.app/Troubleshooting/PlayStation_4/Black+Screen/483709#Section__PS4_Console_Did_Not_Power_Up_Correctly


This branch
https://react-commerce-prod-git-fix-troubleshooting-page-b4ba20-ifixit.vercel.app/Troubleshooting/PlayStation_4/Black+Screen/483709#Section__PS4_Console_Did_Not_Power_Up_Correctly


| Main | This branch | 
| - | - |
| image | image |
| image | image |
| image | image |







</details>

**Comment by jarstelfox** [comment]
The new alert is here: https://ifixit.sentry.io/alerts/metric-rules/react-commerce/183354/

We may need to adjust the thresholds once this is merged:

image

**Comment by ianrohde** [comment]
I bet https://github.com/iFixit/react-commerce/pull/2037 was merged right around this was created. Probably just needs master merge to fix.

**Comment by danielbeardsley** [comment]
Soo... if we were reporting a bunch of errors to sentry... why haven't we seen them? Or are "crashes" different than "issues" in sentry? Also, this seems like confusing terminology... there weren't this many broken pages right? 

Sentry has something to say about it but it's fairly generic.
https://blog.sentry.io/what-is-crash-reporting

**Review by danielbeardsley — DISMISSED** [review]
CR :+1:

**Comment by federicobadini** [comment]
It seems that `Text` appies line clamping via `-webkit-line-clamp` and that approach work only in conjunction with display `-webkit-box` which effectively is the display it applies by default if not overridden.
Now you should see the `noOfLines` property working correctly

**Comment by erinemay** [comment]
un_dev_block 🍰

**Comment by ianrohde** [comment]
Odd choice in default display on Chakra's part.

CR ⚪

**Comment by erinemay** [comment]
QA 👍 everything I noted is fixed. I spot checked several Vulcan pages with different elements. They look identical to main on desktop and mobile.

**Review by masonmcelvain — APPROVED** [review]

**Comment by federicobadini** [comment]
Can confirm that the graph is back to the usual crash free rate 

Screenshot 2023-10-20 at 08 56 18

**Pull request merged**
