### PR TITLE
Featured Products: fix unbounded width

### PR DESCRIPTION
**Pull request by davidrans**
| Before | After |
| --------- | ------ |
| image | image |

CR
---
Ignore whitespace

Closes https://github.com/iFixit/react-commerce/issues/1206

### CODE REVIEW

**Review by sumukhipandey — APPROVED** [review]
CR 🦋

**Comment by deltuh-vee** [comment]
QA 🎬 
The width of the Featured Products section is now limited.

**Comment by dhmacs** [comment]
@davidrans I think probably we should have solved this by increasing image resolution. And if a design change is really needed, imo this should have prompted a design iteration, because the design looks a bit odd now that the cards do not take the full width of the page

**Comment by davidrans** [comment]
I've re-opened the issue :+1: https://github.com/iFixit/react-commerce/issues/1206

**Pull request merged**
