### PR TITLE
Add subscribe to newsletter collection section

### LINKED ISSUE #12: Add subscribe to newsletter section into collection page
Screen Shot 2021-05-12 at 17 10 54

## ❓Questions

- [x] What is the API that I need to use to implement this section?

### PR DESCRIPTION
**Pull request by dhmacs**
This PR adds a subscribe to newsletter section to the collection page.

## QA

1. Visit the Vercel PR preview
2. Visit any collection page (other than `/parts` and `/tools`)
3. Verify that the newsletter section is displayed and looks like the mockup (see below for reference):

    Screen Shot 2021-06-03 at 20 04 25

4. Verify that the section is responsive
5. Try to subscribe an email, and verify that email is successfully subscribed ( cc @zdmitchell on how to verify correct subscription ). We're using the production endpoint, so you may want to remove the email after the workflow has been verified.

Closes #12

### CODE REVIEW

**Comment by zdmitchell** [comment]
I assume this closes https://github.com/iFixit/react-commerce/issues/12?

**Comment by deltuh-vee** [comment]
Is the email subscription supposed to work? It looks like a 405 error is given in the GET request to https://www.ifixit.com/api/2.0/cart/newsletter/subscribe

**Comment by deltuh-vee** [comment]
deploy_block ☝️

Some of the email validation alerts look squashed when viewed in landscape smaller iPhones.
CleanShot 2021-06-03 at 14 06 54

**Comment by dhmacs** [comment]
> Is the email subscription supposed to work? It looks like a 405 error is given in the GET request to https://www.ifixit.com/api/2.0/cart/newsletter/subscribe

It should work, but apparently the production api is handling requests differently from the dev api. @zdmitchell do you know why?

**Comment by dhmacs** [comment]
> deploy_block ☝️
> 
> Some of the email validation alerts look squashed when viewed in landscape smaller iPhones.
> CleanShot 2021-06-03 at 14 06 54

Unfortunately this is native browser validation, so it's a bug of the browser. Not much we can do here until Safari resolves the issue. You can see that you have the same issue on https://ifixit.com newsletter form

**Comment by zdmitchell** [comment]
> It should work, but apparently the production api is handling requests differently from the dev api. @zdmitchell do you know why?

The production API isn't allowing POST requests from that URL. Only certain URLs are allowed, including all the Shopify stores.

**Comment by dhmacs** [comment]
> The production API isn't allowing POST requests from that URL. Only certain URLs are allowed, including all the Shopify stores.

@zdmitchell How do we validate this PR? Do you want to allow both the preview URL and https://react-commerce.vercel.app ?
You can remove the preview URL from whitelist once the PR is merged.

**Comment by zdmitchell** [comment]
> How do we validate this PR?

Shouldn't this preview only be making requests to the development API? I think we only want real requests from the real Shopify stores. That being said, even if you change this preview to now make requests to the development API, you'll still fail but with a 422 for the reason I described here: https://github.com/iFixit/react-commerce/issues/12#issuecomment-852469402. I can make the same change that I did with localhost to force this URL to map to a development Shopify store if you'd like. Let me know.

**Comment by dhmacs** [comment]
> I can make the same change that I did with localhost to force this URL to map to a development Shopify store if you'd like. Let me know.

Yeah I think it's the best option. This way when this goes into production you just need to allow the domains and no changes are required here.

**Comment by dhmacs** [comment]
@zdmitchell I made the change on my side. Let us know when you got the Vercel urls whitelisted, so that @deltuh-vee can review again

**Comment by zdmitchell** [comment]
All dev newsletter requests from non-Shopify origins map to the dev Shopify store for the purposes of Active Campaign now. Everything should be good to review.

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by deltuh-vee** [comment]
QA 🎬 
Email subscription works and the banner is responsively displayed.

**Comment by masonmcelvain** [comment]
CR 👍🏻

**Comment by masonmcelvain** [comment]
Looks like @deltuh-vee's comment was addressed, un_deploy_block ✌🏻

**Pull request merged**
