### PR TITLE
Troubleshooting: Add main image

### PR DESCRIPTION
**Pull request by jyee27**
Add the image from the wiki, styled similarly to Guide pages.
This also adds a spacer (gray line) between the header and introduction section.

<details>
<summary>Images</summary>

Desktop/Tablet
image

Mobile
image

</details>

Closes: https://github.com/iFixit/ifixit/issues/48078

### CODE REVIEW

**Comment by deltuh-vee** [comment]
QA 🎬 
Main image and spacer line are now added.

**Review by danielcliu-ifixit — DISMISSED** [review]
CR :v:

**Review by danielcliu-ifixit — APPROVED** [review]
CR :v:

**Comment by deltuh-vee** [comment]
Carry Over QA 🎬

**Pull request merged**
