### PR TITLE
Adjust layout background color

### LINKED ISSUE #189: Header spacing and color are off
Current site header:
image

Current react-commerce header:
image

Note:
- The site logo is further right.
- The text "Fix you stuff" is further left on the site.
- The workbench, notifications, and cart icons are missing (I would expect us to at least want the cart back on the store).
- The react-commerce header is bluer. (Note, I can see this on my laptops regular 1080p monitor, but it's easier to see on my 2k oled set to gaming)

Windows browsers

### PR DESCRIPTION
**Pull request by dhmacs**
~~deploy_block 🚨 Blocked by #290~~

fixes #189 
 
## Changelog

- Use `black` token for header and footer background color

## QA

1. Visit the Vercel PR preview (replace vercel.app with cominor.com) 
2. Navigate to `/Store/Parts`
3. Verify that header and footer background colors are the same as ifixit.com

### CODE REVIEW

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by dhmacs** [comment]
un_deploy_block 🏎️

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Review by sumukhipandey — COMMENTED** [review]
CR 🦋

**Comment by k0rvusk0r4x** [comment]
The header and footer are now the same color as the header on ifixit.com.

QA 😺

**Pull request merged**
