### PR TITLE
Vulcan: fix mobile table overflow

### PR DESCRIPTION
**Pull request by ianrohde**
## Issue

We added containers to our wiki tables to handle overflow in https://github.com/iFixit/ifixit/pull/48424. Now let's get the tables looking nice on Vulcan 💅 

## Modified

1. [fix overflow: block elements for parent wrappers](https://github.com/iFixit/react-commerce/commit/5ad243dc73f7ccda0477c0e6e036e1189b78f8f2)
2. [remove unnecessary DOM elements](https://github.com/iFixit/react-commerce/commit/b5c0da956846718cf8dc7c57f06430b286ebf445)
3. [add mobile overflow styling from pr 48424](https://github.com/iFixit/react-commerce/commit/7f25abb9e3186126e64d86bd82237b6fe58765ec)
4. [fix imageBox layout & tweak table styling](https://github.com/iFixit/react-commerce/commit/d4c6dd63999c657521cb5bc51c2cdd43bbb6eabe)
5. [remove unnecessary fontWeight applications](https://github.com/iFixit/react-commerce/commit/972a5131739db058d291a13830a37869de7928ef)

## QA

`/Vulcan/iPhone_Black_Screen` has three nested images. It's a good test-case.

<details>
<summary>Post-fix video</summary>

https://github.com/iFixit/react-commerce/assets/1634505/1904b3ac-65e8-41a8-9669-a7babbec79ec

</details>

Closes https://github.com/iFixit/react-commerce/issues/1750

### CODE REVIEW

**Comment by deltuh-vee** [comment]
QA 🎬 
Mobile tables in Vulcan can now overflow.

**Comment by deltuh-vee** [comment]
dev_block ✊ 
The contributors section is now misaligned. As seen on: https://react-commerce-git-vulcan-fix-mobile-table-overflow-ifixit.vercel.app/Vulcan/Google_Pixel_Overheating
image

**Comment by ianrohde** [comment]
> The contributors section is now misaligned.

Thanks for the catch @deltuh-vee. That led me to spot a few other bugs that I fixed 👍 

Typo in https://github.com/iFixit/react-commerce/pull/1769/commits/f6d95cd8159f5da86ff905708cc3b156f0d0cf51 commit: sub-text should read `- the nested span wasn't getting the same **fontSize** applied`

un_dev_block 🟢

**Review by hcutrone — APPROVED** [review]
CR :burrito:

**Comment by deltuh-vee** [comment]
@ianrohde 
Would it be possible to disable the fading on the right, once you reach the end? Also, could fading be introduced on the left once you start to scroll away?

**Comment by ianrohde** [comment]
@deltuh-vee I can, but I'm limited in my control since we're rendering the whole card contents html string as-is on the page.

Here's what I can up with given the limitations. It is admittedly a hack.

<details>

https://github.com/iFixit/react-commerce/assets/1634505/038d0217-5023-4f7e-923b-785d0f7af5a2

</details>

It uses negative and positive margins to offset the gradients on either side of the table.

Keep in mind my main goal here was to fix the layout overflow that was breaking the page.

**Comment by sctice-ifixit** [comment]
> Would it be possible to disable the fading on the right, once you reach the end? Also, could fading be introduced on the left once you start to scroll away?

Without an obvious solution, I don't think this is worth the effort.

**Comment by deltuh-vee** [comment]
un_deploy_block 👍

**Pull request merged**
