### PR TITLE
FPP Switch to Strapi: Remove redirect and logic from `/products`

### PR DESCRIPTION
**Pull request by sumukhipandey**
First PR that for https://github.com/iFixit/ifixit/issues/48697. Here we are just getting rid of the redirects and cleaning up `/products` logic that included `pro-tech-toolkit` and `manta-driver-kit-112-bit-driver-kit`

## QA

Make sure when we visit `/products/pro-tech-toolkit` and `/products/manta-driver-kit-112-bit-driver-kit` the page loads to the normal product pages.

CC: @sterlinghirsh

### CODE REVIEW

**Comment by sumukhipandey** [comment]
deploy_block 🦋  because we do not want to merge this PR before the strapi pages are ready.

**Comment by batbattur** [comment]
Merged main to skip a broken test, [ref](https://github.com/iFixit/react-commerce/pull/1845).

**Comment by deltuh-vee** [comment]
QA 🎬  
Pro Tech Toolkit and Manta Driver Kit pages are now normal product pages.

**Review by masonmcelvain — DISMISSED** [review]
CR ✌🏻 This looks right!

deploy_block ✌🏻 until we get the ok to deploy this

**Comment by masonmcelvain** [comment]
It's time!

> the PTT and Manta Strapi pages are published!

https://ifixit.slack.com/archives/C02KMFEHX62/p1692134313979769

un_deploy_block ✌🏻

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by masonmcelvain** [comment]
QA ✌🏻 

`/products/pro-tech-toolkit` and `/products/manta-driver-kit-112-bit-driver-kit` render Next.js product pages on react-commerce and react-commerce-prod

**Pull request merged**
