### PR TITLE
Vulcan: Fix narrow imageBox image issues (Part 1)

### PR DESCRIPTION
**Pull request by ianrohde**
## Issue
Fix the .imageBox styles so when we come across an abnormally narrow image, we don't squash the caption making it unreadable.

## CR/QA
I have react-commerce loading my cominor from `frontend/.env.local` with `NEXT_PUBLIC_IFIXIT_ORIGIN=https://irohde.cominor.com` so I can sync the inlined `min-width` change I needed to make on that end.

<details>
<summary>Video Overview</summary>

https://github.com/iFixit/react-commerce/assets/1634505/9b66b579-e131-4e3e-9e62-e534ac31974f

</details>

The main offending image/caption was here: https://www.ifixit.com/Troubleshooting/Garbage_Disposal/Hums/491105#Section_Jammed_Motor

Closes https://github.com/iFixit/react-commerce/issues/1876

Relates to https://github.com/iFixit/ifixit/pull/49088

### CODE REVIEW

**Comment by ianrohde** [comment]
deploy_block 🛑 to coordinate with the mono change needed

**Review by aburke07 — DISMISSED** [review]
CR :alien:

**Comment by ianrohde** [comment]
CR 👽 (carrying over Alex's CR - no changes, but not registering on pulldasher)

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I think this might cause the other image to go beyond the card on mobile. As seen on iPhone SE 2nd Gen.
Screen Shot 2023-08-03 at 16 22 14

I had `Vulcan--fix-narrow-imageBox-issues` checked out for my code directory and for the embedded react-commerce repo inside my code directory.

**Comment by ianrohde** [comment]
https://github.com/iFixit/react-commerce/pull/1878/commits/34ba03f8129040bea9b09413cb5157eaf3034f83 should clean up mobile issues while keeping existing functionality.

<details>

https://github.com/iFixit/react-commerce/assets/1634505/d1212119-545e-4fe3-9421-c1d60337e1ad

</details>

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by ianrohde** [comment]
un_dev_block 🟢

**Comment by deltuh-vee** [comment]
QA 🎬 
* Narrow image captions are no longer cut off
* Images stay within the boundaries of their container card

**Comment by ianrohde** [comment]
un_deploy_block 🟢

**Pull request merged**
