### PR TITLE
Remove featured product list section from product list page - backend changes

### PR DESCRIPTION
**Pull request by federicobadini**
🛑 deploy_block on #1488

This PR aim at cleaning up Strapi after the removal of the featured-product-list section.

❗❗❗After this PR is merged Strapi should be redeployed in production ❗❗❗

cc @sterlinghirsh @danielbeardsley @masonmcelvain

### QA

1. Visit Vercel preview
2. Verify that product list pages are still working correctly

### Before merge

To be sure not having any sort of downtime and allowing Strapi to restart smoothly, we should take care that the production data do not include any featured-product-list section at all.
The fastest way I can think of is seeding local environment with production data and checking in the sqlite db that the `product_list_components` collection is not referencing any featured-product-list section at all.
This should be performed just before merge to be sure no section of this kind is present, not even due to testing or by chance.

To do so you have to:

1. On your local machine, make sure that the `backend` folder `.env` includes the following environment variable: `STRAPI_ADMIN_ENABLE_ADDONS_DANGEROUS_ACTIONS=true`
2. Start the dev environment and navigate to `http://localhost:1337/admin/plugins/addons`
3. You should see an interface with an input field - if not try to delete your `.cache`, `.tmp` and `.dist` folders from your local `backend` folder and restart the dev environment.
4. Input https://strapi.ifixit.com/ and press `Reset feed` to overwrite your local data with production data
5. Connect to the local sqlite instance located in `{project-folder}/backend/.tmp/data.db`
6. Inspect the `product_list_components` table to check for the presence of any featured-product-list

### CODE REVIEW

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by deltuh-vee** [comment]
QA 🎬 
Product List pages are still working

To seed the local sqlite database:
* I switched over to this branch
* deleted the old data.db file in backend/.tmp/data.db 
* Ran `pnpm dev`
 
I found these two featured-product-list entries that might have to be removed.
image

**Comment by federicobadini** [comment]
> I found these two featured-product-list entries that might have to be removed.

I feel these are still data from main.govinor.com since starting the dev server locally always pulls from there - no matter the current branch.
I've add some steps above to describe how to pull production data into a running local environment.

At the moment I don't see any featured-product-list in production data

**Comment by masonmcelvain** [comment]
I followed the steps in the PR comment, and this query has no results. un_deploy_block ✌🏻 

```sql
select component_type from product_lists_components where component_type = 'product-list.featured-product-list';
```

**Comment by masonmcelvain** [comment]
Redeployed Strapi ✔️

**Pull request merged**
