### PR TITLE
Sentry: temp disable production check

### PR DESCRIPTION
**Pull request by danielbeardsley**
This won't work the same way once this code is in a private repo.

Let's disable this while we move this code instead of trying to re-solve this problem beforehand.

qa_req 0

### CODE REVIEW

**Review by jarstelfox — APPROVED** [review]
CR 🌵 but you will need to solve the import as well

**Review by masonmcelvain — APPROVED** [review]
CR 👍🏻

**Comment by danielbeardsley** [comment]
> but you will need to solve the import as well

Thanks! Fixed.

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Review by masonmcelvain — APPROVED** [review]
CR 👍🏻

**Pull request merged**
