### PR TITLE
Troubleshooting: Add html5 video styling

### PR DESCRIPTION
**Pull request by jyee27**
Add styles for non-YouTube videos and add styles for videos on mobile to prevent horizontal overflow.

QA
---
Check both YouTube and non-YouTube video styling at desktop and mobile.

Closes: https://github.com/iFixit/ifixit/issues/46894

### CODE REVIEW

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by deltuh-vee** [comment]
Is there any expected visual difference between the videos on Vulcan/troubleshooting-test? They look the same as on master.

**Comment by jyee27** [comment]
> Is there any expected visual difference between the videos on Vulcan/troubleshooting-test? They look the same as on master.

The YouTube videos should be the same for desktop and different for mobile. The HTML5 videos should follow left/right/center alignment in the `[video]` tag.

**Comment by erinemay** [comment]
QA 👍 looks good. 
- Alignment and sizing is reflected on https://react-commerce-git-vulcan-style-html5-videos-ifixit.vercel.app/vulcan/troubleshooting-test
- Youtube an html5 videos continue to play without isse

image

this branch: 
image


deploy_block ❔ @jyee27, I'm seeing a console error I haven't seen before and am not seeing on the main branch. It's happening on page load. LMK what other details I can provide. 
https://react-commerce-git-vulcan-style-html5-videos-ifixit.vercel.app/vulcan/troubleshooting-test
image

**Comment by jyee27** [comment]
> I'm seeing a console error I haven't seen before and am not seeing on the main branch. It's happening on page load. LMK what other details I can provide.

Weird, this pull only touches styles. I'll see if I can repro.

**Comment by jyee27** [comment]
When running locally, I could only get a 404 for the `.small` image on the small videos, and it was the same between branch and master. I did see the `net::ERR_ABORTED 404` error on https://react-commerce-git-vulcan-style-html5-videos-ifixit.vercel.app/vulcan/troubleshooting-test. It looks like it's coming from `feedback.js` which seems to be Vercel's live feedback.
I think it's safe to assume this is unrelated.

**Comment by jyee27** [comment]
un_deploy_block ☕

**Pull request merged**
