### PR TITLE
Problems List: Finalize UI

### PR DESCRIPTION
**Pull request by ianrohde**
## Issue

Mattia made some final updates to the Problems List page. We'll need another style pass for design/UI parity.

## CR/QA

https://react-commerce-prod-8wehk7717-ifixit.vercel.app/Troubleshooting/Dryer

**UI:**

- [x] Update design to match [Figma](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9/iFixit---Problems?node-id=1417%3A53803&mode=dev) https://github.com/iFixit/react-commerce/pull/2219/commits/5d0188bc554862e2b281fe906cfb906689160e1f

**Breadcrumbs:**

- [x] Show full paths https://github.com/iFixit/react-commerce/pull/2219/commits/52f3526318ca8528cfcf326813ad4c1c8690b546

**NavBar:**

- [x] Carry over `Answers -> Troubleshooting` text changes from https://github.com/iFixit/react-commerce/pull/2213 https://github.com/iFixit/react-commerce/pull/2219/commits/706043b6726209ace261d8de5837a0c709a74958

**API:**

- [x] Pass `problemUrl` and link Problem Card components https://github.com/iFixit/ifixit/pull/51739

Connects https://github.com/iFixit/ifixit/issues/51698

### CODE REVIEW

**Comment by ianrohde** [comment]
We may have one additional API modification to enable the `Guide` breadcrumb, but let's not hold the rest up.

**Comment by deltuh-vee** [comment]
Are the breadcrumbs supposed to be longer?
CleanShot 2024-01-23 at 14 05 47

**Review by hcutrone — APPROVED** [review]
CR 🌯 Looks good to me!

**Comment by ianrohde** [comment]
> @ianrohde Are the breadcrumbs supposed to be longer?

<details>
<summary>According the API response, no. It's just two entries for the Switch:</summary>

Screenshot 2024-01-23 at 2 15 19 PM

</details>

**Comment by deltuh-vee** [comment]
QA 🎬
- Design matches Figma a little more closely now
- Breadcrumbs are showing
- Changes from https://github.com/iFixit/react-commerce/pull/2213 have been carried over
- Troubleshooting links now work

**Pull request merged**
