### PR TITLE
Troubleshooting: Use `lite-youtube-embed` to render videos

### PR DESCRIPTION
**Pull request by andyg0808**
This is really simple, because the videos are custom elements, so as long as the JS ends up on the page somewhere it should do the trick. We don't have to do any of the finding and triggering on the elements; the browser does that.

## QA Notes
This won't work until https://github.com/iFixit/ifixit/pull/46740 goes out. Once that's done, you should see YouTube videos on /Vulcan/troubleshooting-test.

Closes https://github.com/ifixit/ifixit/issues/46728

### CODE REVIEW

**Comment by deltuh-vee** [comment]
Visiting /Vulcan/troubleshooting-test seems to crash the page for me.
image

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by jordycosta** [comment]
dev_block 🟥 on https://github.com/iFixit/react-commerce/pull/1427#issuecomment-1460945381

**Comment by andyg0808** [comment]
un_dev_block :+1: 
Whoops! Don't know exactly how that happened, but the 500s should be fixed now.

**Comment by jordycosta** [comment]
QA 🟢 

I am able to see YouTube videos when on [/Vulcan/troubleshooting-test](https://react-commerce-git-troubleshooting-make-youtube-v-ccc34f-ifixit.vercel.app/Vulcan/troubleshooting-test) ✅ 

Screenshot 2023-03-09 160549

**Comment by jordycosta** [comment]
QA 🟢 Carry-over

See https://github.com/iFixit/react-commerce/pull/1427#issuecomment-1463016291

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Pull request merged**
