### PR TITLE
Match Device Navigation Tab styling

### PR DESCRIPTION
**Pull request by aburke07**
## Overview
Extracts and reuses a styled nav tab component on /Parts, /Troubleshooting/device, and /Troubleshooting pages. Reuses the components from the Troubleshooting nav tabs on parts and problem list view pages. Now the styles are consistent across the tabs.

## QA
- The navtabs on [/Parts](http://localhost:3000/Parts/Mac) should now match the tabs on [/Troubleshooting pages](http://localhost:3000/Troubleshooting/iPhone/Won't+Turn+On/405189) and [problem list pages](http://localhost:3000/Troubleshooting/iPhone).
   - All three should now match the updated [figma](https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?type=design&node-id=125-13254&mode=design&t=pGlQ2ObPeeoZ0bti-0).
- When there is no /Parts or /Guides for a device, we disable the link.
- Please check this across all browser widths.

Closes https://github.com/iFixit/ifixit/issues/51876

### CODE REVIEW

**Comment by jordycosta** [comment]
dev_block 🟥 

On mobile, there seems to be a small box to the left of the nav bar

I think this should be flushed to the left to match the nav bar on `ifixit`

mobile

**Comment by aburke07** [comment]
Un_dev_block :alien: Whoops, good catch. Fixed in [f692b5f](https://github.com/iFixit/react-commerce/pull/2234/commits/f692b5f3433d0a4be15abbe0710f4ad0480ed59f)

**Comment by erinemay** [comment]
QA 🦖 
- https://github.com/iFixit/react-commerce/pull/2234#issuecomment-1934712608 is fixed.
- The navigation styling is now similar across /Parts, Troubleshooting, and Problem List pages. Padding, font bolding now matches /Troubleshooting. 
- Disabled states are consistent. I couldn't find a /Parts page that doesn't have a corresponding device page. On /Troubleshooting, if there are no parts, the button is disabled. 
- Checked on desktop, tablet, and mobile,  Safari and Chrome.

**Review by jarstelfox — APPROVED** [review]
CR 🌵

**Pull request merged**
