### PR TITLE
Sentry: upgrade to 7.29.0

### PR DESCRIPTION
**Pull request by davidrans**
We were quite a few (minor) versions behind here. The last release added some performance improvements for NextJS: https://github.com/getsentry/sentry-javascript/releases/tag/7.29.0

### CODE REVIEW

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by erinemay** [comment]
I'm having local-dev troubles, even on main. I'm gonna remove my qaing label, but I assume we should be able to add and trigger an error and see it in Sentry still.

Are there any little gotchas like needing to bypass sampling ifixit/ifixit?

**Comment by masonmcelvain** [comment]
I don't think we sample at all for react-commerce, meaning all errors should go to the react-commerce-dev project on Sentry.

**Comment by deltuh-vee** [comment]
QA 🎬 
Still able to send errors to Sentry.

**Pull request merged**
