### PR TITLE
Fix Images and Part Collections API calls

### PR DESCRIPTION
**Pull request by danielcliu-ifixit**
## Overview

We introduced logs in #457, and this makes sure that the places that use `iFixtAPIClient` now can handle the response's format. Before our failures were basically nulling out and thus making it so no information gotten from the api was being used in the pages. This makes sure that we expect the appropriate data formats so we don't default to nulls.

## CR

Uh I think this should work but make sure that nothing I'm doing is funky. You know, the usual.

## QA
Make sure the normal pages work and load the pictures for the children again. Also make sure that pages that aren't in strapi are loading correctly from the iFixit API and stuff. You can use `Asus_Phone` and `Phone` for this. 
You also need to test authenticating a user in react-commerce.

Closes: #577

### CODE REVIEW

**Review by sterlinghirsh — APPROVED** [review]

**Comment by sterlinghirsh** [comment]
CR :zap: so the problem was that we already return the resulting object from parsing the json from client.get() but we were then checking that object's `.ok` value which wouldn't exist? Weird one. Hopefully we can figure out a test to cover this in the future.

**Comment by jordycosta** [comment]
Non-strapi loading:
- [ ] /Asus_Phone
- [ ] /Phone

**Comment by sterlinghirsh** [comment]
CR :zap:

**Review by sterlinghirsh — APPROVED** [review]

**Comment by masonmcelvain** [comment]
@jordycosta was that QA? Or are you still working on it?

**Comment by jordycosta** [comment]
> @jordycosta was that QA? Or are you still working on it?

Double-checking on the user authentication part

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by danielbeardsley** [comment]
CR :+1: 

Nice work!

**Pull request merged**
