### PR TITLE
Update cypress workflow

### PR DESCRIPTION
**Pull request by batbattur**
## Summary of changes

1. Dropped recording for cypress videos because they weren't working properly (frozen at the beginning) and slowing down the ci. Seems like an [existing cypress issue for this](https://github.com/cypress-io/github-action/issues/483). We still have the screenshots on failures, so I believe this should be fine.

## QA 

In `E2E tests / cypress-run` ci check, `Cypress run` step, make sure there are no video processing logs like the following:
```
  (Video)
-Started processing:Compressing to 32 CRF
-Finished processing:/home/runner/work/react-commerce/react-commerce/frontend/te(36 seconds)
st/cypress/videos/product-list/collections_scroll.spec.ts.m
p4
    Compression progress:  100%
```

### CODE REVIEW

**Comment by batbattur** [comment]
dev_block 👍

**Comment by batbattur** [comment]
un_dev_block 👍 updated the description

`Cypress run` step now takes about [`~3m`](https://github.com/iFixit/react-commerce/runs/7330964380?check_suite_focus=true) whereas on master it takes [`~13m`.](https://github.com/iFixit/react-commerce/runs/7330440273?check_suite_focus=true)
branch

**Comment by batbattur** [comment]
QA 👍 Checked the [logs](https://github.com/iFixit/react-commerce/runs/7330964380?check_suite_focus=true) and made sure there are no videos.

**Review by mlahargou — APPROVED** [review]
Holy cow 10 minutes saved... People could still turn on the video option if they want to debug a test, right?

CR 📱

**Comment by batbattur** [comment]
> People could still turn on the video option if they want to debug a test, right?

Currently, on ci, the recordings are broken/frozen. If people want to record it locally, we would have to change the setting back to `"video": true`, which is not ideal 😕.

However, if running locally, people will be able to see the cypress ui and the test screen if they want to debug. 

screen

We also have screenshots on failure like here https://github.com/iFixit/react-commerce/actions/runs/2672884714, so it might help the debugging. 
image

**Comment by danielbeardsley** [comment]
CR :+1:

**Pull request merged**
