### PR TITLE
Split product model code

### PR DESCRIPTION
**Pull request by dhmacs**
~~Blocked by #1175~~ 

This PR separate server only code from the product model. The intent of this PR is to start introducing a convention to signal server only dependencies using the `server` suffix.

## QA

Just a smoke test

un_dev_block 🟢

### CODE REVIEW

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by masonmcelvain** [comment]
Small merge conflict introduced by https://github.com/iFixit/react-commerce/pull/1183

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by k0rvusk0r4x** [comment]
Smoke test looks good.

QA 😺

**Pull request merged**
