### PR TITLE
Add SSR support to algolia collection search results

### LINKED ISSUE #48: Add SSR support to Algolia collection search results

### PR DESCRIPTION
**Pull request by dhmacs**
Closes #48 

## Changes

- Renders the collection products server side
- Adds cache control header for caching optimization using stale while revalidate

## QA

1. Visit the Vercel PR preview
2. Visit a collection page and verify that products are already rendered when the page is served

### CODE REVIEW

**Comment by erinemay** [comment]
I'm currently getting a 500 from `/collections/tools` and `/collections/parts` when checking out the [preview](https://github.com/iFixit/react-commerce/pull/79#issuecomment-920084321) right now.

**Comment by dhmacs** [comment]
> I'm currently getting a 500 response from `/collections/tools` and `/collections/parts` when checking out the [preview](https://github.com/iFixit/react-commerce/pull/79#issuecomment-920084321) right now.

@erinemay The Strapi deploy is down apparently: https://strapi.cominor.com/graphql

Can you ping someone that can fix this?

**Comment by deltuh-vee** [comment]
The Strapi deploy should be back up now: https://github.com/iFixit/ifixit/pull/39831

**Comment by cdcline** [comment]
CR 👍

**Comment by deltuh-vee** [comment]
QA 🎬 
I disabled javascript for the Parts collection page and verified that products were still loaded.

**Comment by masonmcelvain** [comment]
CR ✌🏻

**Pull request merged**
