### PR TITLE
chore(deps): bump strapi to `v4.12.1`

### PR DESCRIPTION
**Pull request by masonmcelvain**
Closes https://github.com/iFixit/react-commerce/issues/1867

## QA

Make sure strapi still works and is on the correct version, and smoke test product pages and product list pages.

Try running `pnpm install:all` locally and confirm you don't get a diff.

### CODE REVIEW

**Review by dhmacs — DISMISSED** [review]
@masonmcelvain can you update also the packages in the addons plugin, as well as the version references in the docker compose? I suggest to perform a project search for the version we're using, to make sure we're replacing it everywhere

dev_block 🔢

**Comment by masonmcelvain** [comment]
Good catch! Will do

**Comment by masonmcelvain** [comment]
un_dev_block ✌🏻 There are now no results for `git grep "4\.11\.5"`

**Review by dhmacs — APPROVED** [review]
Thanks for the PR!

CR 👍

**Comment by deltuh-vee** [comment]
QA 🎬 
* Strapi works and is on the correct version
* Product Pages and Product List Pages still work
* Running`pnpm install:all` doesn't produce a diff

I think there's something broken with the Strapi deploy cause I see this when visiting /Parts from the preview link.
image

**Comment by masonmcelvain** [comment]
CR ✌🏻 carry forward. I'll carry forward QA assuming the strapi deployment succeeds

**Pull request merged**
